/**
 * One-shot writer for agent-authored shelf banks.
 * Run: node scripts/lib/agent-banks/_write-banks.mjs
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const DIR = dirname(fileURLToPath(import.meta.url));

function emit(name, drafts) {
  const body = `/** Agent-authored ${name} encyclopedia drafts — workplace only, no exam marketing. */\nexport const ${name.toUpperCase()}_DRAFTS = ${JSON.stringify(drafts, null, 2)};\n`;
  writeFileSync(join(DIR, `${name}.mjs`), body, "utf8");
  console.log(name, drafts.length);
}

/** @returns {[title, topic, definition, example, trap, formula?]} */
function t(title, topic, definition, example, trap, formula) {
  return formula
    ? [title, topic, definition, example, trap, formula]
    : [title, topic, definition, example, trap];
}

// ─── FRM ─────────────────────────────────────────────────────────────────────
const FRM = [
  t("Historical simulation VaR lookback window", "Market risk",
    "Historical simulation VaR lookback window sets how many past trading days form the P&L vector used to pick a percentile loss. A shorter window reacts faster to regime shifts; a longer window is smoother but can understate fresh volatility. The chosen window, confidence level, and change-control must sit in the market-risk model inventory and limit schedule.",
    "Risk compares 250-day vs 500-day 99% HS VaR on the same book: £4.2m vs £3.1m. ALCO confirms 250-day feeds desk limits after a documented methodology memo.",
    "Quietly shortening the lookback after a breach to make VaR look smaller without model-change approval.",
    "VaR_α = percentile_α({−ΔP_t}) over lookback N"),
  t("Parametric VaR normality assumption stress", "Market risk",
    "Parametric VaR normality assumption stress checks whether Gaussian σ-based VaR still fits the portfolio’s return shape under fat tails and skew. When returns are heavy-tailed, normal VaR understates true tail loss and must be challenged with HS, Student-t, or ES overlays.",
    "Equity book daily returns show kurtosis 8; 99% parametric VaR is £2.1m while HS VaR is £3.4m. Risk requires HS for limit utilisation until the model is recalibrated.",
    "Defending parametric VaR with calm-period σ while the book holds options with asymmetric payoffs."),
  t("Expected shortfall capital allocation by desk", "Market risk",
    "Expected shortfall capital allocation by desk assigns group ES to trading units using a coherent risk measure so diversified capital is shared fairly. Subadditivity means the sum of desk standalones exceeds group ES; allocation methods must be documented and stable through stress.",
    "Group 97.5% ES is £48m; two desks show standalones £30m and £28m. Risk allocates £25m and £23m using Euler contributions and publishes the split in the weekly capital pack.",
    "Charging each desk its standalone ES and ignoring diversification, then wondering why desks refuse hedges.",
    "ES_α = E[L | L ≥ VaR_α]"),
  t("VaR exception clustering review", "Market risk",
    "VaR exception clustering review examines whether breaches bunch in time rather than arriving independently. Clustering signals stale volatility, missing risk factors, or crisis correlation and usually fails independence backtests even when the raw exception count looks acceptable.",
    "Six 99% VaR exceptions occur in 12 sessions during a rates shock while the annual count is still inside Kupiec bounds. The validation pack flags Christoffersen failure and triggers a model remediation plan.",
    "Reporting only the annual exception count and ignoring a March cluster that coincided with a curve inversion."),
  t("Stressed VaR period selection governance", "Market risk",
    "Stressed VaR period selection governance documents which historical stress window feeds regulatory or internal stressed VaR and who can change it. The period should reflect significant stress relevant to the firm’s risk factors, not the calmest recent year.",
    "Market risk proposes updating the stressed VaR window from 2008–09 to a 2020 COVID window after factor mapping shows better coverage of the current book; the model risk committee minutes the decision.",
    "Cherry-picking a stress window that minimises capital without mapping the firm’s material risk factors."),
  t("Risk factor mapping completeness for VaR", "Market risk",
    "Risk factor mapping completeness for VaR ensures every material price risk in the book is represented in the VaR engine’s factor set. Gaps create phantom hedges and understated VaR when unmapped basis or idiosyncratic risk moves.",
    "A new exotic commodity curve is booked but not mapped; IPV shows £0.9m unexplained P&L. Risk blocks further growth until the factor is added and the proxy mapping is validated.",
    "Proxying an illiquid name to a liquid index without documenting residual basis risk in the mapping inventory."),
  t("Incremental VaR for new issue approval", "Market risk",
    "Incremental VaR for new issue approval measures how much portfolio VaR rises when a proposed trade is added. It supports limit headroom checks before execution and complements standalone VaR, which ignores diversification.",
    "Syndicate desk proposes a £200m corporate bond; incremental 99% VaR is £1.1m against £1.5m unused limit. The desk head approves with a same-day hedge plan.",
    "Approving on standalone VaR alone when the position is highly correlated with an existing overweight sector.",
    "IncVaR = VaR_with − VaR_without"),
  t("Component VaR concentration dashboard", "Market risk",
    "Component VaR concentration dashboard attributes portfolio VaR to names, sectors, or factors so concentration is visible before limits breach. It guides hedge prioritisation and board risk narratives.",
    "Top five names contribute 38% of desk VaR; the dashboard triggers a pre-emptive hedge when any name exceeds 12%. CRO cites the chart in the monthly pack.",
    "Showing only total VaR while a single issuer drives most of the risk."),
  t("Interest rate DV01 ladder by tenor bucket", "Market risk",
    "Interest rate DV01 ladder by tenor bucket reports sensitivity of P&L to one-basis-point moves along the curve, not just parallel shift. Bucket ladders reveal steepener/flattener risk that parallel DV01 hides.",
    "Banking book shows +£120k/bp at 2y and −£95k/bp at 10y. ALCO funds a partial flattener hedge after the ladder exceeds policy gaps.",
    "Managing only parallel DV01 while the 2s10s gap widens through the quarter.",
    "DV01_bucket ≈ −ΔP / 1bp"),
  t("CS01 credit spread sensitivity limits", "Market risk",
    "CS01 credit spread sensitivity limits cap P&L impact from a one-basis-point widening in credit spreads for trading or banking books. Limits should reflect liquidity of the names and correlation with rates hedges.",
    "Trading book CS01 is £85k/bp against a £70k limit after a new HY package. Desk reduces by selling CDS protection overlays the same day.",
    "Netting CS01 across uncorrelated names without a concentration overlay."),
  t("FX delta and vega joint limit utilisation", "Market risk",
    "FX delta and vega joint limit utilisation tracks directional FX exposure alongside option volatility risk so desks cannot exhaust vega while appearing delta-flat. Joint dashboards prevent silent vol concentration.",
    "EM FX options book is delta-neutral but vega uses 92% of limit ahead of an election. Risk requires vega reduction before adding new straddles.",
    "Approving new options on delta alone while vega sits near the ceiling."),
  t("Basis risk between futures and cash hedge", "Market risk",
    "Basis risk between futures and cash hedge is the residual P&L when the hedge instrument does not perfectly track the cash exposure. Delivery baskets, cheapest-to-deliver switches, and calendar rolls all create basis.",
    "Cash gilt hedged with bond futures shows £0.4m adverse basis through a CTD switch week. Desk documents the basis VaR add-on in the weekly pack.",
    "Treating a futures hedge as perfect and omitting basis from VaR and limit reports."),
  t("Liquidity horizon adjustment in internal VaR", "Market risk",
    "Liquidity horizon adjustment in internal VaR scales or floors risk for positions that cannot be exited in the base VaR horizon. Illiquid names need longer horizons so capital and limits reflect exit difficulty.",
    "Private placement bonds get a 10-day liquidity horizon vs 1-day for liquid sovereigns; internal VaR rises £2.6m. Desk limit is restated accordingly.",
    "Applying one-day VaR to a thinly traded loan trading book without a liquidity add-on."),
  t("Market risk limit breach escalation clock", "Market risk",
    "Market risk limit breach escalation clock defines how quickly a VaR, DV01, or stress breach must be notified, remediated, or formally accepted. Clear clocks stop informal overnight overstays.",
    "Soft VaR breach at 10:15 must be notified by noon and remediated or accepted by close; hard breach requires same-hour CRO alert. Compliance samples the timestamps monthly.",
    "Allowing repeated soft breaches to roll overnight without a logged acceptance."),
  t("Backtesting P&L clean vs unclean definition", "Market risk",
    "Backtesting P&L clean vs unclean definition separates hypothetical P&L attributable to market moves from actual P&L that includes fees, new trades, and intraday activity. Clean P&L is required for unbiased VaR exception tests.",
    "Validation rebuilds clean hypothetical P&L and finds two extra exceptions vs unclean actual P&L. The model inventory is updated to mandate clean P&L for regulatory backtesting.",
    "Using actual P&L with intraday trading noise to claim the VaR model passes."),
  t("Non-modellable risk factor NMRF capital", "Market risk",
    "Non-modellable risk factor NMRF capital applies a conservative capital treatment when a risk factor lacks sufficient real price observations for modellable status. NMRF identification must be inventory-driven and evidenced.",
    "An exotic inflation factor fails modellability; capital switches to NMRF stress add-on of £6m. Product control retains the observation evidence pack for audit.",
    "Claiming modellable status with broker runs that are not executable real prices."),
  t("Trading book boundary daily attestation", "Market risk",
    "Trading book boundary daily attestation confirms positions are correctly classified between trading and banking books under the firm’s policy. Misclassification distorts capital, VaR, and hedge accounting outcomes.",
    "Desk head attests that a hold-to-collect loan was never intended for short-term resale after Ops flagged a trading-book booking. Finance reclasses before month-end.",
    "Leaving intent undocumented so positions migrate books to chase a lower capital charge."),
  t("IRC incremental risk charge concentration", "Market risk",
    "IRC incremental risk charge concentration captures default and migration risk in the trading book beyond VaR. Concentration in single names or correlated sectors inflates IRC and needs issuer limits.",
    "IRC jumps £9m after three same-sector HY bonds are added. Desk cuts two names to restore IRC inside the weekly capital budget.",
    "Managing only VaR while IRC silently consumes the desk’s capital envelope."),
  t("Correlation stress for multi-asset VaR", "Market risk",
    "Correlation stress for multi-asset VaR replaces calm-period correlations with stressed matrices so diversification benefit does not vanish only after a crisis. Stress ρ should be approved and version-controlled.",
    "Equity–credit ρ stressed from 0.25 to 0.70 lifts diversified VaR from £12m to £17m. The stress matrix is locked for the quarter after MRC approval.",
    "Continuing to use 0.1 correlations in a risk-off week when cash equities and CDS gap together."),
  t("Gamma and cross-gamma risk in option books", "Market risk",
    "Gamma and cross-gamma risk in option books measures second-order P&L from large spot moves and joint moves across underlyings. Linear delta limits alone miss convexity losses in short-gamma books.",
    "Short dated FX options show gamma P&L −£1.8m on a 2% spot jump despite flat delta. Risk introduces a gamma stress limit of £2m per 2% move.",
    "Calling the book hedged because net delta is near zero while short gamma is large."),

  t("Through-the-cycle vs point-in-time PD", "Credit risk",
    "Through-the-cycle vs point-in-time PD distinguishes long-run average default probability from current-condition PD used in IFRS 9 staging and short-horizon pricing. Mixing the two misstates provisions and economic capital.",
    "Credit uses PiT PD 180 bps for Stage 2 ECL and TTC PD 95 bps for IRB capital on the same SME portfolio. The monthly pack reconciles both with a clear purpose label.",
    "Feeding TTC PD into lifetime ECL and understating Stage 2 provisions in a downturn."),
  t("LGD downturn calibration evidence pack", "Credit risk",
    "LGD downturn calibration evidence pack documents how loss given default is stressed for capital versus expected-loss accounting. Collateral haircuts, recovery lags, and cure rates need vintage evidence.",
    "IRB LGD downturn is 45% vs long-run 32% on residential mortgages; validation cites 2008–10 recoveries. The pack is filed with the model inventory ID.",
    "Haircutting collateral by a flat 10% with no downturn recovery study."),
  t("EAD conversion factor for undrawn lines", "Credit risk",
    "EAD conversion factor for undrawn lines estimates how much of a committed facility becomes exposure at default. Low CCF on revolving lines understates credit risk when utilisation spikes before default.",
    "RCF CCF set at 55% after observing pre-default drawdowns; EAD on a £40m line becomes £22m undrawn plus drawn. Credit committee adopts the factor for limit utilisation.",
    "Assuming zero drawdown on undrawn commitments in stress because current utilisation is low.",
    "EAD ≈ drawn + CCF × undrawn"),
  t("Credit migration matrix annual refresh", "Credit risk",
    "Credit migration matrix annual refresh updates transition probabilities used in credit VaR, IFRS 9, and stress testing. Stale matrices miss rating inflation or sector deterioration.",
    "2025 refresh shows BB→B transitions up 30% in commercial real estate; credit VaR rises £4m. The new matrix is versioned and linked to the stress engine.",
    "Running multi-year credit VaR on a pre-pandemic migration matrix without challenge."),
  t("Obligor concentration Herfindahl monitor", "Credit risk",
    "Obligor concentration Herfindahl monitor tracks name concentration in the credit portfolio beyond single-name limits. A rising HHI signals that granular EL understates true unexpected loss.",
    "Top-20 HHI rises after a large acquisition financing; credit capital add-on of £3m is booked and single-name limit headroom is frozen for that sector.",
    "Relying only on ‘top 10 = 25%’ while mid-tier names become highly correlated."),
  t("Wrong-way risk trade booking flag", "Credit risk",
    "Wrong-way risk trade booking flag marks derivatives or financing where exposure tends to rise as counterparty creditworthiness falls. Specific wrong-way risk needs tighter collateral, shorter tenor, or hedges.",
    "Commodity prepay with a producer shows exposure rising when the commodity price—and producer credit—falls. CVA desk applies a wrong-way multiplier and cuts tenor to 12 months.",
    "Pricing CVA with independent exposure and PD when the underlier drives the counterparty’s solvency."),
  t("CVA hedge effectiveness desk review", "Credit risk",
    "CVA hedge effectiveness desk review checks whether CDS or index hedges offset counterparty credit valuation movements within policy. Ineffectiveness belongs in P&L explain, not silent residual.",
    "Single-name CDS hedges cover 70% of CVA move on a dealer; residual £1.2m is explained by index basis. Desk proposes adding a CDX overlay.",
    "Buying index protection and calling CVA fully hedged without measuring name-level residual."),
  t("Collateral dispute ageing and exposure add-on", "Credit risk",
    "Collateral dispute ageing and exposure add-on increases counterparty exposure when margin calls remain unsettled past agreed timelines. Aged disputes are credit events in all but name.",
    "A £15m VM dispute ages past T+2; exposure add-on is applied and escalated to the counterparty credit officer. Trading is restricted until resolved.",
    "Leaving disputed margin outside exposure while continuing to add risk with the same name."),
  t("Credit limit tenor bucket structure", "Credit risk",
    "Credit limit tenor bucket structure caps exposure by maturity band so long-dated risk cannot hide under a single notional limit. Longer buckets usually carry tighter capacity.",
    "Counterparty limit is £50m <1y, £30m 1–5y, £10m >5y. A proposed 7y swap is declined until a shorter structure is agreed.",
    "Approving a 10-year exposure against a limit defined only on current MTM."),
  t("Shadow rating for unrated counterparties", "Credit risk",
    "Shadow rating for unrated counterparties assigns an internal grade using financials, qualitative factors, and peer mapping when no external rating exists. The grade must feed PD, limits, and watchlist rules.",
    "Unrated supplier gets shadow BB- after cash-flow and governance review; PD 220 bps feeds the limit model. Annual review date is diarised.",
    "Parking unrated names in an ‘other’ bucket with a flat optimistic PD."),
  t("Forbearance flag linkage to Stage 2 ECL", "Credit risk",
    "Forbearance flag linkage to Stage 2 ECL ensures modified loans with financial difficulty are identified for lifetime expected credit loss. Forbearance without staging understates provisions.",
    "A covenant holiday on a CRE loan triggers forbearance and Stage 2; lifetime ECL rises from £0.4m to £1.7m. Credit and finance reconcile the watchlist weekly.",
    "Granting payment holidays without updating IFRS 9 stage or disclosure."),
  t("Credit stress overlay for CRE LTV shocks", "Credit risk",
    "Credit stress overlay for CRE LTV shocks revalues commercial real estate collateral under price declines and higher yields to test LGD and covenant headroom. Overlays should be portfolio-wide, not deal-by-deal anecdotes.",
    "−25% CRE price shock lifts portfolio Stage 2 ECL by £22m; board risk pack shows the bridge. Lending pauses on >70% LTV until overlays ease.",
    "Stressing income only while holding collateral values flat in a rising-rate CRE market."),
  t("Netting set enforceability legal opinion log", "Credit risk",
    "Netting set enforceability legal opinion log tracks jurisdictions and agreement types where close-out netting is recognised for exposure and capital. Missing opinions force gross exposure treatment.",
    "Legal confirms netting opinion expired for one emerging-market annex; exposure switches to gross (+£40m). New trades in that jurisdiction are blocked until refreshed.",
    "Assuming ISDA netting everywhere because the master agreement looks standard."),
  t("Settlement risk Herstatt window limit", "Credit risk",
    "Settlement risk Herstatt window limit caps principal risk when payment legs settle in different time zones or systems. PvP and CLS membership reduce but do not eliminate all settlement risk.",
    "FX settlement risk limit £80m; a large USD/JPY ticket would peak at £95m during the window. Desk splits settlement or uses CLS-eligible pairs.",
    "Ignoring principal settlement risk because replacement-risk MTM is small."),
  t("Sovereign ceiling on corporate credit grades", "Credit risk",
    "Sovereign ceiling on corporate credit grades constrains borrower ratings when country risk dominates transfer and convertibility. Breaking the ceiling needs explicit exception governance.",
    "Local AA corporate capped at sovereign BBB+ for group PD; exception requires CRO and country-risk sign-off. Two exceptions are logged this quarter.",
    "Rating a corporate above the sovereign without documenting transfer-risk mitigants."),

  t("Operational risk loss data threshold policy", "Operational risk",
    "Operational risk loss data threshold policy sets the amount above which internal loss events must be captured for RCSA, capital, and board reporting. Thresholds that are too high hide chronic process failure.",
    "Threshold cut from £20k to £5k; capture rises 40% and reveals a payments repair theme. Op risk redesigns the control with Ops.",
    "Keeping a high threshold so the loss database looks clean while near-misses pile up."),
  t("RCSA residual risk scoring calibration", "Operational risk",
    "RCSA residual risk scoring calibration aligns inherent risk, control effectiveness, and residual scores so colours mean the same across divisions. Uncalibrated scores make heat maps incomparable.",
    "Group workshops re-anchor ‘amber residual’ to defined frequency/impact bands; 18 processes are rescored. Internal audit later samples calibration evidence.",
    "Letting each business invent its own residual scale and then ranking them as if comparable."),
  t("Key risk indicator threshold breach protocol", "Operational risk",
    "Key risk indicator threshold breach protocol defines amber/red triggers, owners, and time-to-action for KRIs such as failed settlements, system downtime, or complaint volumes. KRIs without protocols are vanity metrics.",
    "Failed payment KRI hits red at 2.5%; Ops must root-cause within 48 hours and report to the risk committee if unresolved in a week.",
    "Raising KRI thresholds after breaches instead of fixing the process."),
  t("Scenario analysis workshop for cyber outage", "Operational risk",
    "Scenario analysis workshop for cyber outage estimates severe-but-plausible operational loss from a multi-day core-system or cyber event. Scenarios need business, IT, and finance co-ownership of assumptions.",
    "Workshop estimates £35m loss from five-day payments outage including compensation and remediation. The figure feeds ICAAP op-risk stress and resilience investment cases.",
    "Writing a cyber scenario with IT alone and no customer-impact or financial loss estimate."),
  t("External loss data scaling to firm size", "Operational risk",
    "External loss data scaling to firm size adjusts industry loss events for relevance when internal data are sparse. Scaling must consider business mix, not just revenue multiples.",
    "An external £200m trading-fraud event is scaled to £18m for the firm’s markets footprint and included as a scenario. Validation challenges the scale factor.",
    "Copying headline external losses into capital without scaling or relevance filters."),
  t("Conduct risk complaint-to-loss bridge", "Operational risk",
    "Conduct risk complaint-to-loss bridge links customer complaint themes to operational and conduct loss estimates for product remediation. Bridges stop conduct being treated as a pure compliance narrative.",
    "Complaint spike on a packaged product maps to £6m expected remediation; finance books a provision and product governance pauses sales.",
    "Tracking complaint volumes with no estimated financial remediation exposure."),
  t("Change-the-bank operational risk gate", "Operational risk",
    "Change-the-bank operational risk gate requires residual risk assessment before major system or process go-lives. Gates should include rollback criteria and control evidence, not only delivery milestones.",
    "Payments platform go-live delayed one sprint after the gate finds incomplete reconciliation controls. Residual risk accepted only with dual-run evidence.",
    "Skipping the risk gate because the project steering committee wants the original date."),
  t("Third-party concentration operational dependency", "Operational risk",
    "Third-party concentration operational dependency maps critical services to a small set of vendors so exit and resilience plans are realistic. Concentration is an op-risk and resilience issue, not only procurement savings.",
    "Two cloud regions and one payments processor cover 80% of critical journeys; board requests a diversification plan with 18-month milestones.",
    "Green-rating every vendor individually while ignoring that they share the same subprocessor."),
  t("Internal fraud typology control testing", "Operational risk",
    "Internal fraud typology control testing designs tests around known fraud schemes—collusion, false accounting, mandate fraud—rather than generic sampling. Typologies keep control testing adversarial.",
    "Audit and op risk jointly test supplier master changes against a mandate-fraud typology; two SOD gaps are closed before year-end.",
    "Testing only happy-path approvals and never the override or dual-control bypass paths."),
  t("Business resilience impact tolerance link", "Operational risk",
    "Business resilience impact tolerance link connects operational disruption metrics to board-approved impact tolerances for important business services. Breach of tolerance is a risk event, not only an IT incident.",
    "Payments IBS tolerance is 4 hours; a 6-hour outage is reported as a tolerance breach with customer harm metrics. Remediation is tracked to the risk committee.",
    "Reporting uptime percentages without mapping outages to impact tolerances."),

  t("LCR HQLA eligibility daily certification", "Liquidity risk",
    "LCR HQLA eligibility daily certification confirms assets counted as high-quality liquid assets meet level, haircut, and operational requirements. Ineligible assets silently inflate the ratio.",
    "Treasury removes £120m Level 2 assets that breached the 40% cap after a ratings downgrade; LCR falls from 128% to 119% but remains above policy.",
    "Leaving downgraded bonds in HQLA because the portfolio system still tags them Level 1.",
    "LCR = HQLA / stressed net outflows"),
  t("NSFR ASF factor challenge for deposits", "Liquidity risk",
    "NSFR ASF factor challenge for deposits reviews available stable funding factors applied to deposit segments. Misclassified wholesale deposits overstate NSFR stability.",
    "Ops reclasses £300m brokered deposits from retail ASF 90% to wholesale 50%; NSFR drops 4 points. ALCO adjusts term issuance plans.",
    "Treating all deposits under £100k as stable retail without product-feature review.",
    "NSFR = ASF / RSF"),
  t("Intraday liquidity peak usage dashboard", "Liquidity risk",
    "Intraday liquidity peak usage dashboard tracks maximum daylight liquidity needed across payment systems so buffers cover peaks, not just end-of-day balances. Peaks often occur mid-morning.",
    "Peak intraday usage hits £1.1bn vs £0.9bn buffer on month-end Thursday; Treasury pre-positions collateral the prior evening thereafter.",
    "Managing only closing cash and missing a noon peak that stresses payment queues."),
  t("Contingency funding plan playbook drill", "Liquidity risk",
    "Contingency funding plan playbook drill rehearses activation triggers, communication trees, and monetisation steps under a liquidity stress. Drills expose stale contacts and impractical asset sales.",
    "Annual CFP drill sells £200m HQLA in simulation and finds two counterparties unreachable; contacts and haircuts are updated within a week.",
    "Filing a CFP that has never been drilled and assumes frictionless asset sales."),
  t("Deposit runoff segmentation for stress", "Liquidity risk",
    "Deposit runoff segmentation for stress applies different outflow rates to operational, retail, and wholesale deposit types. Flat runoff assumptions understate wholesale flight risk.",
    "Stress uses 5% retail operational vs 40% non-operational wholesale; modelled outflows rise £450m. LCR still clears 110% after buffer actions.",
    "Applying a single 10% runoff to all deposits regardless of stickiness."),
  t("Encumbrance ratio board limit", "Liquidity risk",
    "Encumbrance ratio board limit caps the share of assets pledged for funding, clearing, or secured borrowing so unencumbered buffers remain. Rising encumbrance shrinks true liquidity optionality.",
    "Encumbrance hits 28% vs 25% board limit after a repo surge; Treasury unwinds £150m repo and reports remediation in five days.",
    "Celebrating cheap secured funding while unencumbered HQLA quietly disappears."),
  t("Funds transfer pricing liquidity premium", "Liquidity risk",
    "Funds transfer pricing liquidity premium charges businesses for the term liquidity they consume and credits stable funding they provide. Without FTP liquidity premia, products look falsely profitable.",
    "FTP adds 35 bps liquidity premium to 5-year fixed-rate loans; product ROE falls and pricing is adjusted. ALCO reviews the curve quarterly.",
    "Leaving FTP as a pure interest curve with no liquidity or contingent commitment charge."),
  t("Early warning indicators for liquidity stress", "Liquidity risk",
    "Early warning indicators for liquidity stress are market and behavioural signals—spread widening, deposit beta shifts, facility drawdowns—that precede formal CFP triggers. EWIs need owners and escalation.",
    "Wholesale CD spreads +40 bps and sticky deposit beta rising trigger EWI amber; Treasury shortens issuance and raises HQLA target by £100m.",
    "Waiting for LCR to breach before acting on market early-warning signals."),
  t("Committed facility undrawn liquidity outflow", "Liquidity risk",
    "Committed facility undrawn liquidity outflow recognises that clients draw revolving credit in firm stress exactly when funding is scarce. Undrawn commitments need realistic draw assumptions in LCR and internal stress.",
    "Corporate RCF undrawn £2bn stressed at 30% draw; liquidity outflow £600m is pre-positioned in the buffer plan.",
    "Assuming undrawn facilities stay undrawn because current utilisation is low."),
  t("Collateral reuse and rehypothecation inventory", "Liquidity risk",
    "Collateral reuse and rehypothecation inventory tracks where received collateral has been re-pledged so recall risk and encumbrance are visible. Opaque reuse creates sudden liquidity gaps.",
    "Prime services inventory shows 62% reuse of hedge-fund collateral; a recall stress needs £180m incremental HQLA. Desk reduces reuse on less stable names.",
    "Counting received collateral as unencumbered liquidity after it has already been rehypothecated."),

  t("Model inventory completeness attestation", "Model risk",
    "Model inventory completeness attestation is the periodic confirmation that all models in use—credit, market, AML, pricing, AI—are listed with owner, materiality, and validation status. Shadow models outside the inventory are uncontrolled risk.",
    "Q2 attestation finds three pricing spreadsheets used for IPV but absent from inventory; they are onboarded as tier-2 models within 30 days.",
    "Attesting completeness while known Excel calculators remain ‘temporary’ for years."),
  t("Model validation independence firewall", "Model risk",
    "Model validation independence firewall keeps validators organisationally and incentive-separate from model developers and profit-taking desks. Independence must be real in reporting lines and performance goals.",
    "Validator of the market VaR model reports to the head of model risk, not markets; findings are issued without desk edit rights. Two high findings remain open with dated actions.",
    "Letting the developing desk rewrite adverse validation findings before MRC sees them."),
  t("Model performance monitoring drift alert", "Model risk",
    "Model performance monitoring drift alert detects when a model’s predictions, rankings, or calibrations deteriorate versus champion benchmarks. Drift without action turns validated models into silent failures.",
    "PD model Gini falls from 0.42 to 0.31 on recent vintages; monitoring raises a red alert and freezes challenger promotion until recalibration.",
    "Reviewing models only on the annual validation anniversary while monthly metrics deteriorate."),
  t("Champion challenger model governance", "Model risk",
    "Champion challenger model governance runs an alternate model in parallel to detect champion bias and prepare succession. Challengers need the same data lineage and fair comparison rules.",
    "Challenger ECL model shows £8m higher Stage 2 than champion for three months; MRC commissions a root-cause before any switch.",
    "Declaring a challenger ‘failed’ because it is more conservative without analysing why."),
  t("Pricing model IPV independent verification", "Model risk",
    "Pricing model IPV independent verification compares desk marks to independent consensus or observed prices. Material unexplained differences indicate model, calendar, or valuation control failure.",
    "IPV variance on bermudan swaptions hits £2.3m; product control escalates and trading reduces risk until the smile calibration is fixed.",
    "Accepting desk marks as IPV because the model is ‘approved’ without independent prices."),
  t("Overlay and expert judgement model register", "Model risk",
    "Overlay and expert judgement model register lists manual adjustments that override model outputs for capital, provisions, or pricing. Overlays need owners, expiry dates, and evidence—otherwise they become permanent shadow models.",
    "Credit overlay +£5m ECL for CRE uncertainty is registered with a 90-day expiry and required exit criteria. Finance tracks expiry on the close checklist.",
    "Applying recurring ‘temporary’ overlays each quarter with no register or exit plan."),
  t("Model change materiality triage", "Model risk",
    "Model change materiality triage classifies proposed changes as immaterial, material, or new-model events so validation effort matches risk. Triage criteria must be pre-agreed, not invented after the change.",
    "A PD recalibration shifts portfolio EL by 8% and is triaged material; full validation is required before production. The change log cites the triage score.",
    "Pushing a recalibration as ‘parameter maintenance’ to avoid validation when EL moves materially."),
  t("AI credit decisioning explainability pack", "Model risk",
    "AI credit decisioning explainability pack documents features, adverse-action reasons, fairness tests, and override rights for machine-learning credit models. Explainability is a control, not a brochure.",
    "ML scorecard ships with top-three reason codes per decline and a monthly fairness dashboard by segment. Compliance samples 50 declines each month.",
    "Deploying a black-box score with no reason codes because accuracy looked strong in backtest."),
  t("Vendor model reliance assessment", "Model risk",
    "Vendor model reliance assessment evaluates third-party models for data opacity, validation rights, and exit options. Outsourcing the model does not outsource model risk accountability.",
    "Market data vendor VaR engine assessed as high reliance; firm negotiates annual validation rights and builds an internal challenger for material books.",
    "Accepting vendor ‘certified’ status as a substitute for firm validation."),
  t("Benchmark model for valuation control", "Model risk",
    "Benchmark model for valuation control is an independent simpler model used to challenge complex production pricers. Large unexplained gaps trigger deep dives before month-end sign-off.",
    "Benchmark bermudan values differ by 12% from production on two trades; both are booked to a prudent valuation adjustment until resolved.",
    "Using the same library for production and ‘independent’ benchmark with shared calibrations."),

  t("Risk appetite cascade to desk limits", "Risk governance",
    "Risk appetite cascade to desk limits translates board appetite statements into measurable desk VaR, credit, liquidity, and conduct limits. Cascade gaps leave appetite as prose without operational teeth.",
    "Board market-risk appetite maps to group VaR £60m and desk sub-limits summing with a diversification buffer. QBR shows utilisation vs appetite in one page.",
    "Publishing qualitative appetite while desks still run on legacy limits unrelated to the statement."),
  t("Principal risk owner accountability map", "Risk governance",
    "Principal risk owner accountability map names executive owners for each principal risk with metrics, appetite, and escalation paths. Shared ownership without a single accountable executive dilutes response.",
    "Cyber principal risk owned by CIO with CRO challenge; KRIs and investment budget sit in the same pack. Internal audit tests ownership clarity annually.",
    "Listing three ‘co-owners’ for a principal risk with no RACI for breach response."),
  t("Risk committee MI pack decision log", "Risk governance",
    "Risk committee MI pack decision log records decisions, acceptances, and follow-ups arising from the risk MI pack so actions do not vanish between meetings. Logs are part of the control evidence.",
    "Committee accepts elevated CRE risk for six months with three mitigating actions; the log tracks owners and due dates into the next agenda.",
    "Discussing red risks verbally with no minuted acceptance or action."),
  t("Three lines role clarity in product approval", "Risk governance",
    "Three lines role clarity in product approval defines first-line product ownership, second-line challenge, and third-line assurance for new products. Blurred lines create rubber-stamp approvals.",
    "New structured deposit requires first-line business case, second-line risk/compliance challenge memo, and post-launch audit within nine months. Launch is held until the challenge memo is closed.",
    "Letting second-line rewrite the business case instead of challenging it."),
  t("Emerging risk horizon scan quarterly", "Risk governance",
    "Emerging risk horizon scan quarterly gathers forward-looking threats—geopolitical, technological, regulatory—not yet in the principal risk register. Scans should feed scenario design and early KRIs.",
    "Horizon scan elevates AI model opacity and critical-mineral supply as watch items; two new KRIs are proposed for the next appetite review.",
    "Recycling last year’s emerging risks with no link to scenarios or investment decisions."),
  t("Risk culture survey to control outcomes bridge", "Risk governance",
    "Risk culture survey to control outcomes bridge connects survey themes (speak-up, priority conflicts) to actual control breaches and loss events. Culture without outcomes is a poster programme.",
    "Low speak-up scores in markets correlate with late risk-event reporting; remediation includes protected escalation channels and KPI changes.",
    "Reporting high culture scores while loss-event reporting timeliness deteriorates."),
  t("Capital contingency trigger framework", "Risk governance",
    "Capital contingency trigger framework pre-defines management actions when CET1, leverage, or internal capital ratios approach thresholds. Triggers convert recovery plans from documents into muscle memory.",
    "CET1 buffer trigger at +100 bps above MDA restricts buybacks and discretionary distributions automatically. Board is notified within 24 hours of breach of the internal trigger.",
    "Waiting for regulatory MDA breach before considering pre-planned capital actions."),
  t("Integrated stress testing assumption book", "Risk governance",
    "Integrated stress testing assumption book locks macroeconomic paths, overlays, and management actions used across ICAAP, IFRS 9, and liquidity stress so results are comparable. Unversioned assumptions destroy auditability.",
    "Assumption book v12 freezes unemployment and HPI paths for the annual stress cycle; late changes require MRC approval and a version bump.",
    "Letting each team pick its own severe path and then comparing results as if consistent."),
  t("Board risk appetite breach notification SLA", "Risk governance",
    "Board risk appetite breach notification SLA sets how fast breaches of board-level appetite metrics reach the chair or risk committee. Slow notification turns appetite into a rear-view report.",
    "Hard appetite breach must reach the risk committee chair within 24 hours; soft breaches within the weekly pack. Two soft breaches this month met the SLA.",
    "Bundling appetite breaches into the next quarterly board pack only."),
  t("Risk data aggregation lineage for BCBS 239", "Risk governance",
    "Risk data aggregation lineage for BCBS 239 documents how risk reports are sourced, transformed, and controlled so accuracy and timeliness can be evidenced. Lineage gaps are themselves a risk finding.",
    "Group VaR report lineage maps from trade capture through risk engine to the board pack with reconciliations at each hop. Internal audit rates lineage ‘satisfactory’ after remediation.",
    "Manually pasting risk numbers into board slides with no recon to source systems."),
];

// Expand FRM with additional workplace angles to reach ~130
const FRM_EXTRA = [
  t("Overnight gap risk limit for cash equities", "Market risk",
    "Overnight gap risk limit for cash equities caps exposure held through the close when overnight news can gap prices beyond intraday hedges. Gap limits complement intraday VaR.",
    "Asia desk overnight gap limit £8m; a proposed ADR overweight would use £9.5m. Position is cut before the New York close.",
    "Assuming stop-losses will work through an overnight trading halt."),
  t("Jump-to-default exposure on credit derivatives", "Credit risk",
    "Jump-to-default exposure on credit derivatives estimates instantaneous loss if the reference name defaults before hedges can be adjusted. It complements spread CS01 for discontinuous credit risk.",
    "Single-name short protection shows JTD £25m vs £15m limit; desk buys CDS protection to cut JTD overnight.",
    "Managing only CS01 while short protection carries large discontinuous default risk."),
  t("Recovery rate uncertainty in CVA", "Credit risk",
    "Recovery rate uncertainty in CVA recognises that LGD assumptions drive counterparty valuation as much as PD. Stressed recoveries should be sensitivity-tested for material counterparties.",
    "CVA rises £3m when recovery on a dealer is stressed from 40% to 20%. Desk hedges incremental CVA with CDS.",
    "Hard-coding 40% recovery for all counterparties regardless of seniority and collateral."),
  t("Operational resilience important business services map", "Operational risk",
    "Operational resilience important business services map identifies services whose disruption harms customers or market integrity and links them to processes, people, technology, and third parties.",
    "Fourteen IBS mapped with impact tolerances; two lack complete resource maps and are remediated before the regulatory self-assessment.",
    "Listing systems instead of customer services and calling the map complete."),
  t("Liquidity transfer pricing contingent commitment fee", "Liquidity risk",
    "Liquidity transfer pricing contingent commitment fee charges businesses for undrawn committed facilities that consume contingent liquidity. Without the fee, RCFs look cheaper than they are.",
    "FTP adds 15 bps on undrawn corporate RCFs; product pricing and limit demand adjust within one quarter.",
    "Charging FTP only on drawn balances while undrawn commitments drive stress outflows."),
  t("Model risk appetite statement metrics", "Model risk",
    "Model risk appetite statement metrics translate qualitative model-risk appetite into counts of overdue validations, high findings, and unapproved models in use. Metrics make appetite enforceable.",
    "Appetite allows zero unapproved material models and max five overdue high findings; current state is one unapproved pricing tool—blocked from new trades.",
    "Stating ‘low model risk appetite’ with no quantitative breach metrics."),
  t("Risk capacity versus risk appetite distinction", "Risk governance",
    "Risk capacity versus risk appetite distinction separates the maximum risk the firm can bear (capacity) from the risk it chooses to take (appetite). Appetite must sit inside capacity with a buffer.",
    "Capital capacity supports £80m market VaR but board appetite is £60m; the £20m buffer is reserved for stress. QBR shows both lines.",
    "Setting appetite equal to capacity with no buffer for estimation error or stress."),
  t("Desk-level stress P&L attribution", "Market risk",
    "Desk-level stress P&L attribution explains which risk factors drive stressed losses so hedges target the real drivers. Attribution turns stress from a single number into an action list.",
    "Rates shock −£12m attributed 70% to 10y DV01 and 20% to vega; desk hedges the 10y bucket first.",
    "Reporting only total stress loss with no factor breakdown."),
  t("Credit valuation adjustment wrong-way multiplier", "Credit risk",
    "Credit valuation adjustment wrong-way multiplier uplifts CVA when exposure and credit quality are adversely correlated. Multipliers should be name-specific where material.",
    "Energy producer counterparty gets 1.5× WWR multiplier; CVA rises £2.1m and is hedged. Methodology note filed in model inventory.",
    "Applying a flat 1.0 multiplier after a clear WWR relationship is identified."),
  t("Op risk capital SMA business indicator mapping", "Operational risk",
    "Op risk capital SMA business indicator mapping assigns P&L lines to the standardised approach business indicator components. Mapping errors distort capital and peer comparisons.",
    "Finance remaps fee income after a product reclass; BI falls 3% and SMA capital drops accordingly. Mapping evidence retained for audit.",
    "Leaving discontinued business revenue inside the BI without challenge."),
];

const FRM_ALL = [...FRM, ...FRM_EXTRA];
emit("frm", FRM_ALL);
console.log("banks written", { frm: FRM_ALL.length });
