import { expand } from "./wave3-shared.mjs";

/** Wave-3 tax drafts — unique vs waves 1–2. */
export const TAX_WAVE3 = expand([
  ["Current tax payable foreign balance FX", "current tax", "computes FX on foreign current tax balances in functional currency each close.", "FX on foreign payable £0.4m in P&L; tax pack explains.", "Ignoring FX on tax payables."],
  ["Deferred tax rate blend for multi-rate entities", "deferred tax", "blends substantively enacted rates when entities face graduated or special rates.", "Blend 24.2% used; sensitivity to 25% disclosed.", "Single headline rate for all temps."],
  ["DTA on share-based payment equity split", "deferred tax", "splits SBP deferred tax between P&L and equity per deduction versus cumulative expense.", "Excess deduction £0.6m to equity; pack ties IFRS 2.", "All SBP DTA through P&L."],
  ["Outside basis DTL probability assessment", "deferred tax", "assesses probability of outside basis reversal for DTL recognition.", "Planned sale makes reversal probable; DTL £3m booked.", "Control assertion after sale decision."],
  ["Pillar Two QDMTT interaction memo", "effective tax rate", "memos interaction of domestic minimum top-up taxes with GloBE top-up.", "QDMTT £1.1m reduces GloBE top-up; double count avoided.", "Accruing both fully."],
  ["ETR bridge discrete item tagging", "effective tax rate", "tags discrete items in the ETR bridge with owners and recurrence flags.", "Discrete R&D credit tagged non-recurring; guidance clear.", "Discrete items buried in 'other'."],
  ["UTP detection risk practice statement", "uncertain tax positions", "states whether measurement reflects detection risk practice under the applicable framework.", "Practice documented; £1.5m EV measurement.", "Silent detection risk assumptions."],
  ["TP true-up invoice and FX pack", "transfer pricing", "packs year-end TP true-ups with invoices, calcs, and FX effects into GL.", "True-up £0.9m fully packed; audit sample clean.", "Tax-comp-only true-ups."],
  ["IQR policy median versus any-point", "transfer pricing", "states whether tested parties target median or any point in the IQR.", "Median policy; below LQ→ £0.7m adjustment.", "Cherry-pick outside IQR."],
  ["DEMPE decision rights evidence diary", "transfer pricing", "diaries where DEMPE decisions are actually made after restructures.", "Diary shows UK decisions; Dutch routine confirmed.", "Contracts say one thing; decisions another."],
  ["Corporate interest restriction tax-EBITDA", "Tax", "computes tax-EBITDA with required adjustments for interest limitation.", "Tax-EBITDA £75m; restriction £6m c/f.", "Accounting EBITDA used raw."],
  ["Hybrid mismatch imported payment screen", "Tax", "screens payments that import hybrid mismatches from offshore structures.", "Imported mismatch denies £0.5m; structure change raised.", "Local-only hybrid review."],
  ["PE day-count alert system remote work", "Tax", "alerts when remote/onsite day-counts approach PE thresholds by country.", "Alert at 90/183 Germany; role changed.", "No day tracking."],
  ["VAT annual adjustment wash-up control", "VAT", "controls the annual partial exemption wash-up calculation and posting.", "Wash-up reclaim £380k; control signed.", "Provisional % all year."],
  ["VAT reverse charge construction domestic", "VAT", "controls domestic reverse charge on construction services where applicable.", "RC flagged on vendor master; sample clean.", "Standard VAT on RC supplies."],
  ["Capital allowances special rate pool review", "Tax", "reviews special rate versus main pool classification on additions.", "Integral features reclassed; AIA plan updated.", "All plant in main pool."],
  ["RDEC versus SME scheme gate test", "Tax", "gates whether SME or RDEC scheme applies before claim prep.", "Gate selects RDEC; claim £3.8m.", "Wrong scheme claimed."],
  ["Group relief capacity versus losses map", "Tax", "maps surrenderable losses to claimant capacity before filing.", "£5m surrendered optimally; none wasted.", "Late discovery of unused relief."],
  ["Tax cash instalment forecast refresh trigger", "Tax", "triggers instalment refresh when forecast taxable profit moves beyond threshold.", "Forecast +£10m → instalment +£1.5m; interest avoided.", "Stale instalments."],
  ["CbCR to consolidation recon control", "Tax", "recons CbCR figures to consolidation with explained plugs.", "Three plugs cleared; filed on time.", "Spreadsheet CbCR."],
  ["Board tax risk appendix standard", "Tax", "standards the board/AC tax risk appendix contents each meeting.", "Appendix covers enquiries, ETR, Pillar Two, controls.", "Ad-hoc tax slides."],
  ["APA critical assumption breach protocol", "transfer pricing", "protocols actions when APA critical assumptions breach.", "Breach → renegotiation started pre-filing.", "Ignore until audit."],
  ["Treaty WHT certificate vault", "Tax", "vaults residency certificates with expiry alerts before payment runs.", "Expired cert blocks reduced WHT.", "Expired certs used."],
  ["Share scheme NIC accrual calendar", "Tax", "calendars employer NIC on share events into payroll and tax.", "EMI exercise NIC £0.8m accrued same month.", "Expense without NIC plan."],
  ["DPT notification counsel log annual", "Tax", "logs annual diverted profits notification decisions with counsel.", "Not required memo filed; AC informed.", "Silent non-notification."],
  ["UTP versus contingent disclosure split", "uncertain tax positions", "splits recognised UTPs from contingent disclosures with criteria.", "£2.2m recognised; £4m contingent; letters align.", "All contingent to avoid P&L."],
  ["IFRS 16 deferred tax gross versus net", "deferred tax", "applies jurisdiction rules on gross/net presentation of lease DT.", "Net where permitted; note explains.", "Always net globally wrong."],
  ["ECL DTA recoverability link forecast", "deferred tax", "links ECL DTA recognition to profit forecast evidence.", "£2.5m DTA supported by approved forecast.", "DTA without recoverability."],
  ["Tax e-file identity control", "Tax", "controls who can submit e-filed returns and dual-controls release.", "Dual release; identity logged.", "Single person e-file."],
  ["Indirect tax finding closure evidence", "VAT", "requires closure evidence for indirect tax findings before green status.", "Credit notes filed; finding closed.", "Email 'fixed' closures."],
  ["Customs royalty dutiability screen", "Tax", "screens royalties and assists for customs dutiability.", "Royalty dutiable; value uplift £0.3m.", "Royalty ignored at import."],
  ["Tax residency minutes evidence pack", "Tax", "packs board minutes evidencing central management location.", "UK decision minutes filed; residency memo updated.", "Offsites as decision forums undocumented."],
  ["Patent box nexus fraction recompute", "Tax", "recomputes nexus fraction when R&D outsourcing changes.", "Nexus down; benefit −£0.25m.", "Stale nexus."],
  ["Enquiry response single owner RACI", "uncertain tax positions", "assigns single owner RACI for each tax enquiry response.", "Owner met 28-day clock; pack controlled.", "Multi-voice emails."],
  ["Intra-group service shareholder activity filter", "transfer pricing", "filters shareholder activities out of service recharges.", "Filter removes £1.2m non-benefiting costs.", "Shareholder costs recharged."],
  ["Tax cash scenario range for treasury", "Tax", "gives treasury base/up/down tax cash scenarios.", "Downside +£7m audit cash reserved.", "Point forecast only."],
  ["Dependent agent authority creep test", "Tax", "retests PE when commercial authorities creep toward contract conclusion.", "Authority creep reversed; PE risk cleared.", "Titles without authority tests."],
  ["DST gross versus net pricing impact", "Tax", "assesses whether DST is grossed in customer pricing or absorbed.", "DST £0.5m absorbed H1; pricing update H2.", "DST ignored in pricing."],
  ["Deferred tax note category roll system", "Tax", "ensures deferred tax system categories roll to note lines.", "Roll variance £3k cleared.", "Manual note."],
  ["CFC low-tax entity screen quarterly", "Tax", "screens low-tax entities quarterly for CFC inclusion.", "Screen catches financing CFC; £0.9m inclusion.", "Annual-only screen."],
  ["MAP status to accounting bridge", "transfer pricing", "bridges MAP case status to correlative relief accounting.", "MAP probable; receivable £1.8m.", "Double tax unrelieved."],
  ["Off-payroll SDS reason code quality", "Tax", "QA samples SDS reason codes for coherence with facts.", "QA fails 10%; statuses reworked.", "Rubber-stamp SDS."],
  ["Tax automation exception ageing gate", "Tax", "gates filings when tax automation exceptions age past SLA.", "Exceptions >14 days block e-file.", "Exceptions ignored."],
  ["Branch taxable profit conversion bridge", "Tax", "bridges branch accounting to taxable profit with diffs.", "Bridge complete pre-PE comp.", "Tax = accounts."],
  ["Land tax relief claim evidence file", "Tax", "files evidence for land/stamp tax reliefs at completion.", "Relief rejected; appeal pack ready.", "Relief assumed."],
  ["Tax KRI amber escalation path", "Tax", "paths amber tax KRIs to the tax committee with owners.", "Amber enquiry KRI escalated; action dated.", "KRIs decorative."],
  ["AT1 coupon hybrid analysis ALCO", "Tax", "brings AT1/hybrid coupon tax analysis to ALCO before issuance.", "Non-deductible coupons priced into instrument choice.", "Issuance without tax."],
  ["Post-balance tax event classification", "close process", "classifies post-balance tax rate/enquiry events under adjusting rules.", "Enactment after date → disclose only.", "Incorrect adjusting."],
  ["MLI PPT purpose contemporaneous file", "Tax", "files contemporaneous principal purpose evidence for treaty structures.", "PPT file supports relief.", "Retroactive PPT stories."],
  ["Carbon tax deductibility timing", "Tax", "confirms deductibility timing for carbon taxes/ETS costs locally.", "Deduction on settlement; deferred tax considered.", "P&L = tax always."],
  ["Tax CSA calibration annual workshop", "Tax", "calibrates tax CSA scores across regions annually.", "Workshop cuts inflated greens.", "Everyone green."],
  ["Exit tax instalment cash model", "Tax", "models instalment elections for exit taxes in cash plans.", "Five-year instalments elected; treasury updated.", "Full cash hit assumed."],
  ["Loss carry-back versus carry-forward EV", "Tax", "compares EV of carry-back refund versus carry-forward use.", "Carry-back EV higher; claim filed.", "Forward-only habit."],
  ["LOB active trade test file", "Tax", "files limitation-on-benefits active trade tests for treaty WHT.", "LOB fails; full WHT.", "BO cert only."],
  ["Partnership 704(c) tax capital bridge", "Tax", "bridges tax capital including 704(c) to investor reporting.", "Bridge explains investor notice diffs.", "GAAP as tax capital."],
  ["Thin-cap arm's length capacity study", "Tax", "studies debt capacity for thin-cap beyond safe harbours.", "Capacity supports debt; limitation still binds £2m.", "Safe harbour max only."],
  ["Disclosure committee tax appendix v2", "Tax", "uses versioned tax appendix for disclosure committee.", "v2 adds Pillar Two quantitative where ready.", "Ad-hoc appendix."],
  ["Remote worker payroll nexus matrix", "Tax", "matrices payroll nexus triggers by remote worker location.", "Matrix registers five workers; PE separate.", "Contract UK = no nexus myth."],
  ["Locked-box tax leakage schedule SPA", "Tax", "schedules tax leakage items in locked-box SPA negotiations.", "Leakage £0.7m chipped.", "No leakage schedule."],
  ["VAT code SOD and UAT evidence", "VAT", "evidences SOD and UAT for VAT code changes.", "UAT + dual approve; live change clean.", "AP edits codes."],
  ["Tax provision qualitative materiality examples", "close process", "examples when qualitative factors override quantitative tax materiality.", "Reputational enquiry booked below threshold.", "Quantitative only."],
  ["Dual consolidated loss structure screen", "Tax", "screens structures for dual consolidated / dual-use loss risk.", "Screen blocks dual use plan.", "Dual use assumed OK."],
  ["Tax transparency basis of preparation", "Tax", "states basis of preparation for voluntary tax transparency metrics.", "Basis note with AC review; published.", "Naked totals."],
  ["UTP roll-forward system integrity", "uncertain tax positions", "ensures UTP subledger rolls opening to closing with settlements.", "Roll ties to note; settlement £0.8m.", "Note not rollable."],
  ["TP local file event trigger list", "transfer pricing", "lists mid-year events that force local file refresh.", "IP move triggers refresh; margins restored.", "Year-end-only files."],
  ["Tax lake to GL daily recon", "Tax", "recons tax analytics lake tables to GL daily for risk scores.", "Break aged; scores paused.", "Unreconciled scores."],
  ["Imported services RC vendor flag", "VAT", "flags vendors for imported services reverse charge in master data.", "Flag drives RC; 100% sample OK.", "Manual RC each time."],
  ["First-year allowance capex taxonomy", "Tax", "taxonomises capex forms for FYA/green allowances.", "Taxonomy lifts FYA claims £0.5m.", "No tax flags on capex."],
  ["Group relief digital consent workflow", "Tax", "workflows digital consents before group relief filing.", "Consents T-5; relief safe.", "Missing consents."],
  ["Settlement authority matrix tax", "uncertain tax positions", "matrices who can settle tax controversies by amount.", "£1.5m needs CFO+Head Tax; followed.", "Local settle material."],
  ["Public CbCR recon to private", "Tax", "recons public CbCR drafts to private CbCR where required.", "Bridge drafted; sensitivities reviewed.", "No public readiness."],
  ["Deal tax W&I exclusion map", "Tax", "maps tax W&I exclusions to escrow/indemnity gaps.", "TP excluded; escrow sized.", "W&I = full tax cover myth."],
  ["Emergency tax code ageing payroll", "Tax", "ages emergency tax codes and forces correction SLAs.", "Corrections within two pays; complaints down.", "Emergency forever."],
  ["Tax heat map IA focus feed", "Tax", "feeds tax heat maps into IA planning automatically.", "High TP heat → IA this year.", "Heat map unused."],
  ["IP migration NPV with exit and royalty", "Tax", "NPVs IP migrations with exit charge and ongoing royalty together.", "Exit £6m + royalty 4%; still positive—approved with cash plan.", "Substance slides only."],
  ["Tax journal access quarterly review", "Tax", "reviews tax provision journal access quarterly.", "Ex-staff removed; SOD OK.", "No access review."],
  ["Vendor VAT invoice education pack", "VAT", "educates vendors on invoice fields for recovery.", "Invalid invoices −35%.", "Recovery on invalids."],
  ["Central management diary overseas", "Tax", "diaries overseas meetings to evidence they were not decision forums.", "Diary supports UK residency.", "Decisioning abroad silently."],
  ["Regulatory capital instrument tax ALCO", "Tax", "analyses tax of regulatory capital instruments at ALCO.", "AT1 non-deductible priced in.", "Tax after issuance."],
  ["Tax close digital checklist SLA", "close process", "SLAs digital tax close checklist completion before sign-off.", "100% T-1; two lates RCA'd.", "Email close."],
  ["WHT matrix to payment system sync", "Tax", "syncs WHT rate matrix to payment systems overnight.", "Sync catches treaty update.", "Stale payment WHT."],
  ["R&D competent professional register", "Tax", "registers competent professionals signing R&D technical narratives.", "Named engineers on three projects.", "Finance-only narratives."],
  ["Ownership change loss restriction test", "Tax", "tests ownership changes for loss trafficking restrictions.", "55% shift triggers test; losses restricted.", "Losses used blindly."],
  ["Special partial exemption approval file", "VAT", "files authority approvals for special partial exemption methods.", "Approval on file; calcs automated.", "Unapproved special method."],
  ["Business combination tax true-up goodwill", "Tax", "routes measurement-period tax true-ups to goodwill not P&L when required.", "TP true-up to goodwill; documented.", "All through P&L."],
  ["Tax holiday substance headcount evidence", "Tax", "evidences headcount/substance for tax holidays continuously.", "Headcount dip risks holiday; hiring plan.", "Holiday after substance gone."],
  ["Controversy settle versus litigate EV", "uncertain tax positions", "EVs settle versus litigate with tail risk for material cases.", "Settle approved despite lower mean litigate EV due to tail.", "Litigate by habit."],
  ["Benchmark refresh versus fact-change", "transfer pricing", "refreshes benchmarks on cadence or sooner on fact change.", "Refresh after restructure; still in IQR.", "Decade-old set."],
  ["Tax system ICFR key control map", "close process", "maps tax engine controls into ICFR key controls when tax in scope.", "Access + calc review key-tested.", "Tax outside ICFR."],
  ["Cross-border loss surrender legality", "Tax", "checks legality of cross-border loss surrender before planning.", "Blocked; local only.", "Assumed allowed."],
  ["E-invoicing mandate country tracker", "VAT", "tracks e-invoicing mandates and system readiness by country.", "One country amber; project funded.", "Paper where e-invoice mandated."],
  ["Incentive clawback probability accrual", "Tax", "accrues clawbacks of incentives when conditions likely fail.", "Clawback probable; payable booked.", "Wait for cash demand."],
  ["Tax three lines RACI map", "Tax", "maps tax prep, review, and assurance lines with RACI.", "IA every two years; second-line reviews returns.", "One team does all."],
  ["Deferred tax on pensions OCI bridge", "deferred tax", "bridges pension OCI and deferred tax movements each close.", "OCI DT ties; note clear.", "P&L/OCI mix-ups."],
  ["Uncertain tax interest monthly accrual", "uncertain tax positions", "accrues UTP interest monthly per policy.", "Interest on £3m UTP monthly; penalties when probable.", "Principal only."],
  ["GloBE safe harbour data dry run", "effective tax rate", "dry-runs transitional safe harbour data before year-end.", "Dry run fails two entities; remediation before close.", "First attempt at close."],
  ["TP master file annual refresh gate", "transfer pricing", "gates year-end on master file refresh completeness.", "Master file refreshed; gate passed.", "Stale master file."],
  ["VAT group joiner leaver invoice cutover", "VAT", "controls invoice tax treatment cutover on VAT group joiners/leavers.", "Leaver cutover same day; no dual VAT.", "Legal leave, VAT unchanged."],
  ["Balancing charge proceeds versus TWDV", "Tax", "computes balancing charges using tax WDV not accounting NBV.", "Proceeds > TWDV; charge taxed.", "NBV used wrong."],
  ["R&D qualifying cost filter evidence", "Tax", "evidences filters removing non-qualifying R&D support costs.", "Filter −25% costs; claim still robust.", "All overhead in."],
  ["Consortium ownership condition test", "Tax", "tests consortium ownership conditions before relief claims.", "Fails; group relief used.", "Assumed consortium OK."],
  ["Instalment interest sensitivity dashboard", "Tax", "dashboards sensitivity of instalment interest to forecast error.", "Dashboard drives earlier refresh.", "Interest surprise."],
  ["CbCR notification owner calendar", "Tax", "calendars CbCR local notification owners by country.", "Late notifications fixed via calendar.", "Parent filing myth."],
  ["UK tax strategy alignment check", "Tax", "checks published tax strategy against actual governance annually.", "Strategy updated for Pillar Two.", "Stale strategy."],
  ["APA annual report filing control", "transfer pricing", "controls timely APA annual report filings.", "Report filed; assumption OK.", "Skipped reports."],
  ["WHT reclaim recoverability provision", "Tax", "provisions aged WHT reclaims for recoverability.", "2-year reclaim 50% provided.", "Full carry forever."],
  ["Assignee shadow payroll completeness", "Tax", "tests completeness of shadow payroll for assignees.", "Missed assignee caught; £35k corrected.", "Home payroll only."],
  ["Legal letter to UTP recon year-end", "uncertain tax positions", "recons external legal letters to recorded UTPs at year-end.", "Aligned within policy.", "Letters disagree books."],
  ["Lease payment tax timing schedule", "deferred tax", "schedules tax timing of lease payments versus IFRS 16 expense.", "Payment-based deduction; DTA supported.", "Expense = deduction myth."],
  ["ECL write-off tax deduction calendar", "deferred tax", "calendars when ECL becomes deductible by jurisdiction.", "Write-off basis UK; DTA timed.", "Immediate global DTA."],
  ["Tax code change emergency path", "VAT", "defines emergency path for urgent tax code changes with after-the-fact review.", "Emergency used once; reviewed in 48h.", "Emergency without review."],
  ["Origin preference claim sampling", "Tax", "samples preferential origin claims for document completeness.", "12 weak claims; duty exposure accrued.", "Blind preference."],
  ["Residency certificate renewal bot", "Tax", "bots renewal alerts for residency certificates pre-expiry.", "Bot blocks two payments; certs renewed.", "Manual expiry misses."],
  ["Patent box streaming election log", "Tax", "logs streaming elections and affected IP income streams.", "Log complete; nexus updated.", "Election undocumented."],
  ["Enquiry privilege waiver checklist", "uncertain tax positions", "checklists privilege before sending documents to authorities.", "Counsel memo withheld appropriately.", "Accidental waiver."],
  ["Service recharge allocation key change", "transfer pricing", "change-controls allocation keys for service recharges.", "Key to headcount approved; benefit memos OK.", "Silent key changes."],
  ["Tax cash downside liquidity reserve", "Tax", "reserves liquidity for downside tax cash scenarios.", "£8m reserved for audit settlement path.", "No reserve."],
  ["Agency PE checklist after CRM change", "Tax", "re-runs agency PE checklist after CRM/authority system changes.", "CRM rights narrowed; PE OK.", "System change without PE test."],
  ["DST and corporate tax double counting", "Tax", "prevents treating DST as creditable CIT without analysis.", "DST separate; CIT interaction memo.", "DST as CIT credit wrong."],
  ["Deferred tax inventory freeze date", "Tax", "freezes deferred tax inventory inputs at a dated cut-off.", "Freeze T-0; post items next period.", "Moving freeze."],
  ["CFC substance site visit evidence", "Tax", "evidences CFC substance with site/people evidence not only contracts.", "Site evidence fails; inclusion computed.", "Paper substance."],
  ["MAP correlative relief probability gate", "transfer pricing", "gates receivable recognition on MAP probability criteria.", "Probable → receivable; possible → disclose.", "Always book receivable."],
  ["IR35 status flip payroll accrual", "Tax", "accrues NIC/PAYE when IR35 status flips to inside.", "Three flips; £0.2m accrued.", "Flip without accrual."],
  ["Tax engine recon to TB sign-off", "Tax", "dual-signs tax engine recon to trial balance each return.", "£0 variance; signed.", "No recon."],
  ["Branch versus sub tax model refresh", "Tax", "refreshes branch vs subsidiary tax models before expansions.", "Germany sub selected; model filed.", "Form chosen first."],
  ["SDLT on share versus asset deal", "Tax", "compares stamp/land tax on share versus asset deal structures.", "Share deal SDRT lower; chosen with other factors.", "Stamp ignored."],
  ["Tax risk appetite KRI dictionary", "Tax", "dictionaries formulas for tax risk appetite KRIs.", "Dictionary stops metric debates.", "Undefined KRIs."],
  ["Hybrid instrument accounting-tax bridge", "Tax", "bridges accounting classification to tax treatment for hybrids.", "Equity account / non-deductible tax; ETR bridged.", "Account = tax myth."],
  ["Tax cut-off enactment evidence", "close process", "evidences substantive enactment status at cut-off for rates.", "Not enacted; sensitivity only.", "Proposed rate booked."],
  ["Treaty network MLI impact refresh", "Tax", "refreshes MLI impact on treaty network annually.", "PPT applies two treaties; WHT updated.", "Pre-MLI matrix."],
  ["ETS free allowance tax basis schedule", "Tax", "schedules tax basis of free ETS allowances.", "Taxed on use; schedule maintained.", "Ignored free allowances."],
  ["Tax CSA evidence attachment rule", "Tax", "requires evidence attachments for any green CSA score.", "Greens without evidence downgraded.", "Bare greens."],
  ["Migration exit charge board paper", "Tax", "boards exit charge and cash timing before migration approval.", "£7m exit in board paper; approved with plan.", "Migration without exit model."],
  ["Carry-back refund receivable criteria", "Tax", "criteria for booking carry-back refund receivables.", "Virtually certain → book £1.3m.", "Book too early."],
  ["Beneficial ownership questionnaire refresh", "Tax", "refreshes BO questionnaires on ownership/finance changes.", "Questionnaire shows conduit risk; full WHT.", "Stale BO."],
  ["Partnership allocation to K-1 recon", "Tax", "recons tax allocations to investor K-1 equivalents.", "Within £1k; notices out.", "FS shares as tax."],
  ["Related-party debt capacity file", "Tax", "files debt capacity and arm's length interest for related-party debt.", "3.1x OK; £3m deductible after limitation.", "Debt to ceiling blindly."],
  ["Tax disclosure pre-clear checklist", "Tax", "checklists tax items requiring disclosure committee pre-clear.", "UTP + Pillar Two pre-cleared.", "Finance-only final."],
  ["Remote PE and payroll joint review", "Tax", "jointly reviews PE and payroll nexus for remote cohorts.", "Spain cohort triggers both; actions joint.", "PE-only or payroll-only."],
  ["M&A tax due diligence leakage quant", "Tax", "quantifies locked-box tax leakage in diligence for price chips.", "£0.85m chip agreed.", "Qualitative only."],
  ["VAT code emergency aftercare review", "VAT", "reviews emergency VAT code changes within 48 hours.", "Aftercare finds wrong rate; corrected.", "Emergency uncleansed."],
  ["Tax adjustment booking threshold policy", "close process", "policies when tax adjustments book versus disclose-only.", "£120k booked; £35k logged disclose-only.", "Inconsistent booking."],
  ["Dual-use loss prevention checklist", "Tax", "checklists prevent dual use of the same loss cross-border.", "Checklist blocks plan; structure changed.", "Dual use."],
  ["GRI 207 governance narrative pack", "Tax", "packs GRI 207 governance narrative with country metrics.", "AC reviews; published.", "Metrics without governance."],
  ["UTP measurement method election log", "uncertain tax positions", "logs whether EV or most-likely amount is used per UTP.", "EV used on R&D; MLE on transfer pricing; logged.", "Method undocumented."],
  ["TP year-end true-up GL cut-off", "transfer pricing", "cuts off TP true-up journals to the correct period.", "True-up in year; FX in year.", "True-up next year wrong."],
  ["Tax analytics model light governance", "Tax", "light-governs models scoring tax risk from data lakes.", "Model documented; recon daily.", "Black-box tax risk scores."],
  ["Reverse charge self-assessment recon", "VAT", "recons reverse charge output to input postings daily.", "Break found; fixed same day.", "One-sided RC."],
  ["AIA utilisation versus capex forecast", "Tax", "aligns AIA utilisation plans to approved capex forecasts.", "AIA fully used; forecast match.", "AIA surprise shortfall."],
  ["Group relief anti-abuse condition check", "Tax", "checks anti-abuse conditions for group relief claims.", "Condition OK; claim proceeds.", "Relief without anti-abuse check."],
  ["Tax provision automation SOD", "Tax", "enforces SOD between tax provision preparer and approver in system.", "SOD conflict removed.", "Same person both."],
  ["Indirect tax health-check theme track", "VAT", "tracks themes across indirect tax health-checks group-wide.", "Theme: RC errors; training funded.", "Local findings siloed."],
  ["Customs valuation subsequent proceeds", "Tax", "captures subsequent proceeds that adjust customs value.", "Proceeds uplift duty £0.15m.", "Subsequent proceeds missed."],
  ["Tax residency emergency board meeting site", "Tax", "protocols emergency board meeting locations for residency risk.", "Emergency call recorded as UK-chaired.", "Emergency abroad unmanaged."],
  ["Patent box qualifying income stream map", "Tax", "maps qualifying IP income streams for patent box claims.", "Map complete; non-qual filtered.", "Blended income claimed."],
  ["Enquiry settlement negotiation brief", "uncertain tax positions", "briefs settlement negotiations with authority matrix and EV.", "Brief used; settled £1.1m within authority.", "Unbriefed negotiation."],
  ["Intra-group financing LOB interaction", "Tax", "analyses LOB/PPT interaction on intra-group financing treaties.", "PPT risk high; WHT modelled full.", "Treaty rate assumed."],
  ["Tax cash forecast owner attestation", "Tax", "attests tax cash forecast ownership monthly to treasury.", "Attestation catches missed true-up.", "Orphan forecast."],
  ["PE inventory of construction sites", "Tax", "inventories construction/installation sites for PE duration tests.", "Site day-count near limit; contract split reviewed.", "Sites untracked."],
  ["Digital services tax scoping refresh", "Tax", "refreshes DST scoping when products/revenue mixes change.", "Marketplace expansion in scope; £0.4m accrued.", "Stale DST scope."],
  ["Deferred tax rate sensitivity pack", "Tax", "packs rate sensitivity when enactment is imminent but not done.", "Sensitivity +1pp; not booked.", "Booked early."],
  ["CFC exemption gateway tests file", "Tax", "files gateway exemption tests for CFCs with evidence.", "Gateway fails; inclusion computed.", "Exemption assumed."],
  ["MAP file chronology control", "transfer pricing", "controls chronology and completeness of MAP case files.", "Chronology complete; competent authority status clear.", "Scattered MAP emails."],
  ["Contractor status determination audit sample", "Tax", "samples contractor status determinations for quality each quarter.", "Sample flips two to inside; accrual £0.1m.", "Never sampled."],
  ["Tax technology lineage diagram annual", "Tax", "updates tax data lineage diagrams annually for key returns.", "Diagram shows GL→engine→return; audit OK.", "Undocumented lineage."],
  ["Branch accounts functional currency tax", "Tax", "aligns branch tax comps to correct functional currency rules.", "Functional OK; translation bridge clear.", "Wrong currency tax."],
  ["Stamp tax share deal relief checklist", "Tax", "checklists reliefs on share deals with timing of liability.", "Relief pack archived; SDRT paid correctly.", "Relief after payment late."],
  ["Tax appetite breach notification SLA", "Tax", "SLAs notification of tax appetite breaches to committee chair.", "Hard breach notified 12h.", "Quarterly surprise."],
  ["Hybrid regulatory capital holder tax", "Tax", "analyses holder-side tax on hybrid regulatory capital investments.", "Holder tax per local rules; ALM informed.", "Issuer-only analysis."],
  ["Tax close blocker severity matrix", "close process", "matrices which tax close blockers can delay group sign-off.", "Material UTP blocks; small recon does not.", "Everything or nothing."],
  ["WHT refund litigation EV", "Tax", "EVs litigating aged WHT refunds versus writing down.", "Litigate EV positive; pursued.", "Write-off habit."],
  ["R&D claim project boundary test", "Tax", "tests project boundaries so routine work is not in R&D claims.", "Boundary test cuts two projects.", "Blurred projects."],
  ["Group relief timing with return amendments", "Tax", "times group relief with return amendments and deadlines.", "Amendment path used; relief saved.", "Deadline miss."],
  ["Tax provision commentary for auditors", "Tax", "prepares structured tax provision commentary for auditors at close.", "Commentary reduces PBC churn.", "Ad-hoc answers."],
  ["VAT partial exemption special method change", "VAT", "governs changes to special methods with authority engagement.", "Change approved; calculations updated.", "Silent method drift."],
  ["Customs broker instruction control", "Tax", "controls instructions to customs brokers on valuation/assists.", "Instructions updated after assist finding.", "Broker freelancing."],
  ["Tax residency emergency protocol card", "Tax", "pocket cards residency protocols for company secretaries.", "Card used in crisis call; OK.", "Improvised residency."],
  ["Patent box election revocation analysis", "Tax", "analyses when to revoke patent box elections if nexus collapses.", "Revoke modelled; kept with remediation.", "Blind keep."],
  ["Enquiry document production log", "uncertain tax positions", "logs every document produced to tax authorities.", "Log complete; privilege preserved.", "Unlogged productions."],
  ["Service centre markup benchmarking", "transfer pricing", "benchmarks mark-ups for shared service centres periodically.", "Markup 5% still in range; kept.", "Stale markup."],
  ["Tax cash actual versus forecast bridge", "Tax", "bridges actual tax cash to forecast monthly for treasury.", "Bridge explains £2m timing; forecast tuned.", "No bridge."],
  ["PE risk in seconded employee programmes", "Tax", "assesses PE risk in secondment programmes with host activities.", "Secondment PE risk amber; contracts tightened.", "Secondment ignored."],
  ["DST return to provision recon", "Tax", "recons DST returns to amounts provided in accounts.", "Recon clean; true-up £50k.", "Return orphan."],
  ["Deferred tax inventory by jurisdiction pack", "Tax", "packs deferred tax inventories by jurisdiction for the note.", "Pack ties multi-country note.", "Blended inventory."],
  ["CFC financing income categorisation", "Tax", "categorises financing income for CFC rules correctly.", "Category triggers inclusion; computed.", "Wrong category."],
  ["MAP correlative relief FX", "transfer pricing", "accounts FX on MAP correlative relief receivables.", "FX £0.1m in P&L; explained.", "FX ignored."],
  ["Off-payroll agency worker SDS flow", "Tax", "flows SDS responsibilities correctly for agency workers.", "Agency flow documented; sample OK.", "Broken SDS flow."],
  ["Tax engine calc version freeze", "Tax", "freezes tax engine calculation versions at filing.", "Version frozen; reproducible.", "Unversioned calcs."],
  ["Asset deal versus share tax model", "Tax", "models tax of asset versus share deals holistically.", "Asset deal steps up basis; chosen.", "Legal form first."],
  ["Tax KRI to appetite mapping", "Tax", "maps each tax KRI to an appetite statement line.", "Mapping complete; amber clear.", "Orphan KRIs."],
  ["Hybrid mismatch deduction/non-inclusion", "Tax", "tests deduction/non-inclusion outcomes on cross-border instruments.", "D/NI denies deduction; ETR hit.", "Instrument ignored."],
  ["Tax adjusting event legal advice date", "close process", "uses advice dates to classify adjusting tax events.", "Advice after date → non-adjusting.", "Wrong classification."],
  ["MLI synthetic PE vigilance", "Tax", "vigilates artificial PE avoidance under MLI PE rules.", "Commissionaire reviewed; terms safe.", "Old PE planning."],
  ["Carbon border adjustment awareness", "Tax", "assesses CBAM/similar costs for import-heavy businesses.", "CBAM estimate £0.6m; pricing updated.", "CBAM ignored."],
  ["Tax CSA remediation verification", "Tax", "verifies tax CSA remediations with evidence not status flips.", "Verification sample 20; 2 fails.", "Status flip only."],
  ["Exit tax security for instalments", "Tax", "assesses security requirements for exit tax instalments.", "Security posted; instalments OK.", "Instalments without security check."],
  ["Loss carry-forward evidence of profits", "deferred tax", "evidences future profits for loss DTA beyond hope.", "Three-year plan approved; DTA held.", "Hopeful DTA."],
  ["BO questionnaire financing side", "Tax", "includes financing/side agreements in BO questionnaires.", "Side letter shows conduit; full WHT.", "Ownership only."],
  ["Partnership tax distribution timing", "Tax", "aligns tax distributions timing to capital account rules.", "Timing bridge in investor pack.", "Cash = tax distribution myth."],
  ["Thin-cap local versus group ratio", "Tax", "tests thin-cap on local and group ratios as required.", "Local binds; group OK; file both.", "Group-only test."],
  ["Tax note critical judgement list", "Tax", "lists critical tax judgements for the accounting note.", "UTP + DTA recoverability listed.", "Judgements buried."],
  ["Remote worker PE insurance myth", "Tax", "debunks reliance on insurance as PE mitigator in memos.", "Insurance ≠ no PE; day-count still rules.", "Insurance comfort wrong."],
  ["SPA tax indemnity basket interaction", "Tax", "models tax indemnity baskets/de minimis in deal risk.", "Basket leaves small leaks; ops focus.", "Assume full indemnity."],
  ["VAT recovery blocked supplies screen", "VAT", "screens blocked supplies where input VAT never recovers.", "Blocked entertains filtered; no reclaim.", "Reclaim on blocked."],
  ["Tax materiality versus audit materiality", "close process", "aligns tax booking materiality with group audit materiality consciously.", "Tax threshold set at 10% audit materiality.", "Random thresholds."],
  ["Dual resident company screen", "Tax", "screens dual resident company risks in structures.", "Dual resident risk; planning changed.", "Dual residence missed."],
  ["Tax transparency assurance readiness", "Tax", "readies controls for assurance over tax transparency metrics.", "Lineage + recon ready; limited assurance possible.", "Unauditable metrics."],
  ["UTP statute of limitations tracker", "uncertain tax positions", "tracks statutes of limitations for UTP release timing.", "SOL expiry releases £0.4m; controlled.", "Forgotten SOLs."],
  ["TP interquartile range update mid-year", "transfer pricing", "updates IQR when peer sets change materially mid-year.", "Peer delisting updates IQR; true-up path set.", "Stale IQR."],
  ["Tax data quality score for e-file", "Tax", "scores data quality before e-file release.", "Score amber blocks file until fixed.", "File dirty data."],
  ["Reverse charge digital services imports", "VAT", "controls RC on imported digital/B2B services specifically.", "Digital vendors flagged RC; OK.", "Expense without VAT."],
  ["Capital allowances disposal election options", "Tax", "evaluates elections on disposals affecting balancing charges.", "Election modelled; chosen lower NPV tax.", "Default without model."],
  ["R&D claim HMRC enquiry playbook", "Tax", "playbooks responses to R&D enquiries with evidence owners.", "Playbook used; enquiry closed.", "Scramble response."],
  ["Group relief claimant priority policy", "Tax", "policies priority among claimants when losses are scarce.", "Policy maximises NPV; applied.", "First-come chaos."],
  ["Tax provision narrative for AC minutes", "Tax", "prepares AC minute-ready tax provision narratives.", "Narrative used; challenge logged.", "Verbal only."],
  ["VAT fuel scale and private use controls", "VAT", "controls private use and fuel scale charges where relevant.", "Scale charges posted; sample OK.", "Private use missed."],
  ["Customs classification advance ruling log", "Tax", "logs advance classification rulings and expiry.", "Ruling guides entries; duty correct.", "Classification freestyle."],
  ["Tax residency POEM versus incorporation", "Tax", "analyses place of effective management versus incorporation tests.", "POEM UK; incorporation foreign—memo clear.", "Incorporation-only view."],
  ["Patent box R&D subcontractor nexus hit", "Tax", "models nexus hits from subcontracted R&D for patent box.", "Subcontract up; nexus down; benefit cut.", "Subcontract ignored."],
  ["Enquiry tolling agreement tracker", "uncertain tax positions", "tracks tolling agreements that extend assessment periods.", "Tolling logged; SOL adjusted.", "Missed tolling."],
  ["Cost plus service centre local file", "transfer pricing", "keeps local files current for cost-plus service centres.", "File refreshed; markup OK.", "Stale service file."],
  ["Tax cash vs ETR bridge education", "Tax", "educates stakeholders that ETR ≠ near-term tax cash.", "Education pack used in QBR.", "ETR as cash myth."],
  ["PE risk in warehouse/consignment", "Tax", "assesses PE risk in warehouses and consignment arrangements.", "Consignment PE risk; terms revised.", "Stock abroad ignored."],
  ["DST registration threshold monitor", "Tax", "monitors DST registration thresholds as revenues grow.", "Threshold crossed; registered; accrued.", "Threshold surprise."],
  ["Deferred tax on FV OCI equity", "deferred tax", "handles deferred tax on FVOCI equity elections correctly.", "No recycle; DT through equity; OK.", "Wrong P&L DT."],
  ["CFC offshore receipt categorisation", "Tax", "categorises offshore receipts for CFC/anti-diversion rules.", "Category triggers inclusion.", "Miscategorised receipt."],
  ["MAP APA interplay strategy", "transfer pricing", "strategies MAP versus APA paths for recurring TP disputes.", "APA pursued; MAP paused.", "Both chaotic."],
  ["Off-payroll umbrella company risk", "Tax", "assesses umbrella company risks for off-payroll compliance.", "Umbrella risk high; direct engage preferred.", "Umbrella = safe myth."],
  ["Tax engine disaster recovery test", "Tax", "tests DR for tax engines before filing season.", "DR test OK; RTO met.", "Untested DR."],
  ["Share deal tax attribute continuity", "Tax", "assesses continuity of tax attributes in share deals.", "Loss continuity restricted; model updated.", "Attributes assumed survive."],
  ["Tax appetite soft breach trend", "Tax", "trends soft tax appetite breaches for rewrite triggers.", "Three softs → appetite rewrite proposed.", "Softs ignored."],
  ["Hybrid entity classification mismatch", "Tax", "identifies entity classification mismatches causing hybrid outcomes.", "Mismatch denies deduction; fix planned.", "Classification ignored."],
  ["Tax close dependency on payroll calendar", "close process", "maps tax close dependencies on payroll/share scheme calendars.", "Dependency delay risk; buffer added.", "Surprise payroll tax."],
  ["WHT treaty shopping PPT screen", "Tax", "screens treaty shopping risk under PPT before reduced WHT.", "Screen fails; full WHT.", "Treaty rate shopping."],
  ["Free allocation ETS clawback tax", "Tax", "accounts tax on clawback of ETS free allocations.", "Clawback probable; accrued.", "Clawback ignored."],
  ["Tax CSA cross-region peer review", "Tax", "peer-reviews CSA scores across regions for calibration.", "Peer review cuts two greens.", "Silo scores."],
  ["Exit charge versus step-up benefit", "Tax", "compares exit charge cost to step-up tax benefits in migrations.", "Step-up NPV < exit; migration redesigned.", "Exit only view."],
  ["Loss DTA expiry schedule", "deferred tax", "schedules loss expiry dates against utilisation plans.", "Expiry in 3 years; utilisation plan tight.", "Expiry ignored."],
  ["BO change of control refresh", "Tax", "refreshes BO analysis on change of control.", "Refresh shows new conduit risk.", "Stale BO post-deal."],
  ["Partnership tax election tracker", "Tax", "tracks partnership tax elections and deadlines.", "Election filed on time; benefit kept.", "Missed election."],
  ["Earnings stripping group ratio election", "Tax", "evaluates group ratio elections under interest limitation rules.", "Election modelled; adopted.", "Default without model."],
  ["Tax critical accounting estimate note", "Tax", "drafts tax critical estimate disclosures with sensitivity.", "Sensitivity on UTP ±£1m disclosed.", "No sensitivity."],
  ["Remote work PE safe harbour reliance", "Tax", "documents reliance—or not—on temporary PE safe harbours for remote work.", "Safe harbour ended; day-count rules apply.", "Expired safe harbour relied."],
  ["Indemnity tax cap versus escrow", "Tax", "sizes tax indemnity caps versus escrow for residual deal tax risk.", "Cap 10%; escrow for TP gap.", "Unsized residual."],
  ["VAT input tax blocked partial exempt", "VAT", "correctly blocks and partially exempts input VAT together.", "Blocked first; then PE on remainder.", "Order wrong."],
  ["Tax booking versus reporting materiality", "close process", "separates booking materiality from disclosure reporting materiality for tax.", "Small item disclosed qualitatively.", "Same threshold both."],
  ["Dual resident loss surrender block", "Tax", "blocks loss surrender involving dual residents where restricted.", "Block applied; planning changed.", "Surrender attempted."],
  ["Tax transparency restatement protocol", "Tax", "protocols restating prior tax transparency metrics if wrong.", "Protocol used once; restated clearly.", "Silent corrections."],
  ["UTP interest reverse on settlement", "uncertain tax positions", "reverses accrued UTP interest correctly on settlement.", "Settlement reverses £0.2m interest; OK.", "Interest left hanging."],
  ["TP comparable set confidential data", "transfer pricing", "controls confidential data in comparable sets and local files.", "Redactions applied; file safe.", "Confidential peers leaked."],
  ["Tax e-file rejection replay control", "Tax", "controls replay after e-file rejection with versioning.", "Rejection fixed; replay v2 filed.", "Chaos replay."],
  ["RC on imported advertising services", "VAT", "specifically controls RC on imported advertising/marketing services.", "£1.5m RC posted correctly.", "Expensed clean."],
  ["Capital allowances AI vs special rate conflict", "Tax", "resolves conflicts between AIA eligibility and special rate classification.", "Integral features special rate; AIA plan adjusted.", "AIA claimed wrong."],
  ["R&D claim subcontracted overseas filter", "Tax", "filters overseas subcontracted R&D per scheme rules.", "Overseas cut; claim compliant.", "All subcontracts in."],
  ["Group relief consent after ownership change", "Tax", "revalidates group relief consents after ownership changes.", "Consent re-signed; relief OK.", "Stale consent."],
  ["Tax provision auditor PBC index", "Tax", "indexes PBC for tax provision to cut repeat requests.", "Index reused; churn down.", "Repeated PBCs."],
  ["VAT MOSS/OSS registration tracker", "VAT", "tracks OSS/IOSS registrations for digital supplies.", "OSS registered; returns filed.", "Registration gap."],
  ["Customs assist tooling valuation", "Tax", "values tooling assists correctly in customs value.", "Tooling £0.35m added; duty paid.", "Assist missed."],
  ["Tax residency tie-breaker treaty analysis", "Tax", "analyses treaty tie-breakers for dual residence risk.", "Tie-breaker to UK; memo filed.", "Dual residence unmanaged."],
  ["Patent box streaming vs tracking choice", "Tax", "chooses streaming versus tracking approaches with modelled outcomes.", "Streaming chosen; model filed.", "Choice undocumented."],
  ["Enquiry settlement within SOL", "uncertain tax positions", "ensures settlements occur with SOL awareness.", "Settlement before SOL; interest stopped.", "SOL surprise."],
  ["Shared service benefit test refresh", "transfer pricing", "refreshes benefit tests when service catalogues change.", "Catalogue change; two recipients fail benefit—recharge stopped.", "Stale benefit."],
  ["Tax cash actuals feed to FP&A", "Tax", "feeds tax cash actuals to FP&A for forecast learning.", "Feed reduces forecast error 20%.", "Tax cash siloed."],
  ["Secondment PE and employment tax joint", "Tax", "jointly assesses PE and employment tax on secondments.", "Joint review flips two to host payroll.", "Separate siloed views."],
  ["DST accounting gross presentation", "Tax", "presents DST gross in accounts per policy consistently.", "Gross presentation; ETR bridge clear.", "Netting DST wrongly."],
  ["Deferred tax inventory lock after freeze", "Tax", "locks deferred tax inventory edits after freeze without controller approval.", "Lock prevents silent edits.", "Post-freeze edits."],
  ["CFC exempt period tracking", "Tax", "tracks exempt periods/thresholds for CFC regimes.", "Exempt period ends; inclusion starts.", "Missed end."],
  ["MAP interest on correlative relief", "transfer pricing", "accounts interest on MAP correlative relief where applicable.", "Interest £0.05m; booked.", "Interest ignored."],
  ["Off-payroll reasonable care defence file", "Tax", "files reasonable care evidence for off-payroll decisions.", "Care file supports SDS positions.", "No care file."],
  ["Tax calc reproducibility pack", "Tax", "packs inputs to reproduce tax computations years later.", "Pack used in enquiry; OK.", "Unreproducible comps."],
  ["Share vs asset stamp and VAT interplay", "Tax", "models stamp and VAT interplay in share versus asset deals.", "Asset deal VAT on property; share preferred.", "One tax only viewed."],
  ["Tax KRI forecast leading indicators", "Tax", "adds leading KRIs (e.g. enquiry opens, TP true-up size) not only lagging filings.", "Leading KRI amber; prep starts early.", "Lagging only."],
  ["Hybrid mismatch imported mismatch treaty", "Tax", "checks treaty interactions with imported mismatch denials.", "Denial stands; treaty no save.", "Treaty myth save."],
  ["Tax close FX on uncertain tax", "close process", "FXs foreign-currency UTPs each close.", "FX on UTP £0.1m; explained.", "FX ignored on UTP."],
  ["WHT rate change legislative watch", "Tax", "watches legislative WHT rate changes into the payment matrix fast.", "Rate change synced in 48h.", "Lagged matrix."],
  ["R&D claim cloud cost qualifying test", "Tax", "tests which cloud/compute costs qualify under R&D schemes.", "Cloud filter applied; claim accurate.", "All cloud in."],
  ["Group relief arrangement anti-avoidance", "Tax", "reviews arrangements for group relief anti-avoidance risks.", "Arrangement clean; claim OK.", "Avoidance risk missed."],
  ["Tax provision change log for auditors", "Tax", "keeps a dated change log of tax provision movements for auditors.", "Log explains every movement >£50k.", "Mystery movements."],
  ["VAT reverse charge domestic reports", "VAT", "files any required domestic RC reports/listings on time.", "Listing filed; penalty avoided.", "Listing missed."],
  ["Customs preferential origin supplier decl", "Tax", "collects supplier declarations for preferential origin claims.", "Missing decls → preference denied.", "Preference without decls."],
  ["POEM board pack evidence hyperlinks", "Tax", "hyperlinks POEM evidence in residency memos to minute packs.", "Hyperlinks speed audit.", "Memo without links."],
  ["Patent box IP ownership chain", "Tax", "evidences IP ownership chain for patent box qualifying IP.", "Chain break found; fixed before claim.", "Broken chain claimed."],
  ["UTP statistical method portfolio", "uncertain tax positions", "uses portfolio statistical methods where many similar UTPs exist.", "Portfolio EV on transfer pricing micros; OK.", "Item-by-item noise."],
  ["TP DEMPE workshop annual cadence", "transfer pricing", "runs DEMPE workshops annually or on restructure.", "Workshop after R&D move; returns updated.", "DEMPE once ever."],
  ["Tax cash stress in going concern", "Tax", "includes tax cash stresses in going-concern liquidity analysis when material.", "Tax audit downside in GC pack.", "GC without tax cash."],
  ["Warehouse PE safe harbour conditions", "Tax", "checks warehouse PE exemptions/safe harbours conditions continuously.", "Conditions fail; PE risk raised.", "Warehouse always exempt myth."],
  ["DST and VAT on same digital supply", "Tax", "clarifies DST and VAT both may apply without one replacing the other.", "Both accrued; pricing updated.", "One replaces other myth."],
  ["Deferred tax on FV hedge OCI", "deferred tax", "handles DT on cash-flow hedge OCI consistently.", "DT through OCI; recycle aligned.", "P&L DT wrong."],
  ["CFC low profit exclusion test", "Tax", "tests low-profit/low-margin CFC exclusions with evidence.", "Exclusion fails; inclusion computed.", "Exclusion assumed."],
  ["MAP multilateral versus bilateral choice", "transfer pricing", "chooses bilateral vs multilateral MAP paths with strategy memo.", "Bilateral chosen; memo filed.", "Path undocumented."],
  ["Off-payroll personal service company risk", "Tax", "assesses PSC structures for off-payroll risk beyond labels.", "PSC fails status; inside IR35.", "Label reliance."],
  ["Tax system user access joiner-leaver", "Tax", "controls joiner-leaver access to tax systems within SLA.", "Leaver removed day 1; OK.", "Leaver access lingers."],
  ["Asset step-up tax versus book deal model", "Tax", "models tax step-up versus book in asset deals for NPV.", "Step-up NPV valued in bid.", "Step-up ignored."],
  ["Tax appetite rewrite trigger log", "Tax", "logs triggers that force tax appetite rewrite.", "Three soft breaches trigger rewrite.", "Never rewrite."],
  ["Hybrid regulatory capital issuer deduction", "Tax", "confirms issuer deduction outcomes for hybrids before pricing.", "Non-deductible; coupon priced up.", "Deduction assumed."],
  ["Tax close dependency matrix", "close process", "matrices dependencies between tax, payroll, FA, and consolidation closes.", "Matrix prevents sequence fails.", "Sequence chaos."],
  ["Treaty residence certificate digital vault", "Tax", "vaults digital treaty residence certificates with checksum.", "Checksum detects corrupt file; re-obtained.", "Corrupt cert used."],
  ["R&D claim AI compute qualifying boundary", "Tax", "boundaries which AI training/inference costs qualify as R&D.", "Inference excluded; training partly in; evidenced.", "All AI cost in."],
  ["Group relief extinctive loss tracking", "Tax", "tracks losses that become extinct on arrangements/changes.", "Extinct loss removed from capacity map.", "Phantom losses."],
  ["Tax provision sensitivity tornado", "Tax", "presents tornado sensitivities for key tax judgements to AC.", "UTP and DTA tornado used.", "Point only."],
  ["VAT bad debt relief ageing evidence", "VAT", "evidences aged debt criteria for bad debt relief claims.", "Ageing evidence complete; claim OK.", "Early BDR."],
  ["Customs subsequent proceeds royalty link", "Tax", "links royalty agreements to customs subsequent proceeds tests.", "Royalty linked; duty uplift.", "Royalty siloed from customs."],
  ["Tax residency video board meeting protocol", "Tax", "protocols video board meetings for residency evidence quality.", "Protocol records UK chair and quorum location.", "Video meetings unmanaged."],
  ["Patent box qualifying IP infringement income", "Tax", "tests whether infringement/damages income qualifies for patent box.", "Damages partly qualify; streamed correctly.", "All damages in."],
  ["Enquiry confidentiality ring control", "uncertain tax positions", "controls confidentiality rings for sensitive enquiry documents.", "Ring members logged; leak none.", "Wide sensitive sends."],
  ["TP seasonal business comparable adjust", "transfer pricing", "adjusts comparables for seasonal businesses in benchmarking.", "Seasonal adjust keeps tested party in IQR.", "Unadjusted seasonal mismatch."],
  ["Tax cash covenant headroom link", "Tax", "links tax cash forecasts to debt covenant cash definitions when relevant.", "Tax cash in covenant model; headroom OK.", "Covenant ignores tax cash."],
  ["Server PE risk cloud assessment", "Tax", "assesses server/cloud PE risk under local rules for digital businesses.", "Cloud PE low; people PE higher—focus people.", "Server PE obsession."],
  ["DST double tax relief interaction", "Tax", "analyses whether DST obtains double tax relief against CIT.", "No credit; ETR bridge shows.", "Assumed credit."],
  ["Deferred tax on crypto accounting", "deferred tax", "addresses deferred tax on crypto asset accounting mismatches where held.", "Mismatch identified; DT booked.", "Crypto tax ignored."],
  ["CFC diversion of profits interaction", "Tax", "analyses CFC versus diverted profits overlaps to avoid double provision.", "One path selected; memo avoids double.", "Double provision."],
  ["MAP arbitration clause readiness", "transfer pricing", "readies arbitration clauses/timelines in MAP strategies.", "Arbitration timeline in strategy; pressure applied.", "MAP without endgame."],
  ["Off-payroll CEST tool evidence limits", "Tax", "treats CEST outputs as evidence inputs not conclusive status.", "CEST + facts → SDS; not CEST alone.", "CEST sole reliance."],
  ["Tax DR filing season capacity test", "Tax", "tests capacity/DR specifically in filing season peak.", "Peak DR test OK.", "Off-peak-only DR."],
  ["Share deal tax warranty schedule", "Tax", "schedules tax warranties and disclosure letters in share deals.", "Schedule complete; residual escrow.", "Warranties unread."],
  ["Tax KRI board versus committee split", "Tax", "splits which tax KRIs go to board versus tax committee.", "Board: enquiries >£1m; committee: filings—clear.", "Board overload."],
  ["Hybrid mismatch disregarded entity", "Tax", "identifies disregarded entity hybrids causing D/NI outcomes.", "Disregarded hybrid denied; fixed.", "Entity form ignored."],
  ["Tax close XBRL tagging control", "close process", "controls tax-related XBRL/tagging where required for filings.", "Tagging reviewed; error fixed.", "Untagged chaos."],
  ["WHT refund power of attorney tracker", "Tax", "tracks POAs needed for WHT refund claims abroad.", "POA expired; renewed; claim proceeds.", "Stuck refund."],
  ["R&D claim subsidised expenditure filter", "Tax", "filters subsidised expenditure from R&D claims per rules.", "Grant-funded costs out; claim clean.", "Subsidised in."],
  ["Group relief overlapping period rules", "Tax", "applies overlapping period rules for joiners/leavers in relief.", "Overlap computed; relief correct.", "Full year wrong."],
  ["Tax provision disclosure committee redlines", "Tax", "tracks disclosure committee redlines on tax note wording.", "Redlines accepted; wording tighter.", "Ignored redlines."],
  ["VAT capital goods scheme tracking", "VAT", "tracks capital goods scheme adjustments over the adjustment period.", "CGS adjustment year 3 posted.", "CGS forgotten."],
  ["Customs transfer pricing interplay", "Tax", "aligns customs valuation with transfer pricing where required.", "TP true-up triggers customs review.", "TP and customs silos."],
  ["Tax residency emergency quorum location", "Tax", "records quorum physical/video locations in emergency meetings.", "Quorum UK; residency OK.", "Quorum location unknown."],
  ["Patent box streaming election change", "Tax", "governs changes to streaming elections with modelled impacts.", "Change modelled; deferred.", "Silent election change."],
  ["UTP portfolio correlation assumption", "uncertain tax positions", "documents correlation assumptions in portfolio UTP measurements.", "Correlation 0.3; EV stable.", "Hidden correlation."],
  ["TP COVID abnormal year comparable", "transfer pricing", "handles abnormal years in comparable sets with documented policy.", "Abnormal year excluded; policy applied.", "Cherry abnormal."],
  ["Tax cash escrow release timing deal", "Tax", "models tax escrow release timing in deal cash plans.", "Escrow 18 months; seller IRR adjusted.", "Escrow ignored."],
  ["People functions PE AOA pack", "Tax", "packs significant people functions analysis for PE profit attribution.", "SPF pack gives routine to PE.", "Whole profit to PE."],
  ["DST marketplace facilitator rules", "Tax", "applies marketplace facilitator DST/VAT rules correctly.", "Facilitator rules in scope; accrued.", "Seller-only view."],
  ["Deferred tax on own shares reserve", "deferred tax", "handles DT on own-share/treasury reserves per local rules.", "DT through equity; OK.", "P&L DT wrong."],
  ["CFC insurance cell risk", "Tax", "assesses CFC/cell company risks for captive insurance.", "Cell fails substance; inclusion.", "Captive assumed exempt."],
  ["MAP confidentiality versus disclosure", "transfer pricing", "balances MAP confidentiality with financial statement disclosure needs.", "Disclosure qualitative; MAP intact.", "Over-disclosure harms MAP."],
  ["Off-payroll group company exemptions", "Tax", "tests group company off-payroll exemptions carefully.", "Exemption fails; SDS required.", "Group exemption myth."],
  ["Tax system change freeze filing window", "Tax", "freezes tax system changes in filing windows except emergencies.", "Freeze held; filing clean.", "Change mid-file."],
  ["Share deal stamp and loan relationship", "Tax", "considers loan relationship and stamp interactions in share deals.", "Model complete; structure OK.", "Stamp-only view."],
  ["Tax appetite metric assurance sample", "Tax", "samples tax appetite metrics to source quarterly.", "One metric breaks; fixed.", "Unaudited metrics."],
  ["Hybrid mismatch reverse hybrid", "Tax", "identifies reverse hybrid outcomes affecting investors/payers.", "Reverse hybrid; withholding path changed.", "Reverse hybrid missed."],
  ["Tax close narrative for going concern", "close process", "includes material tax cash/controversies in going-concern narratives.", "Enquiry downside in GC.", "GC tax-blind."],
  ["Treaty principal purpose contemporaneous", "Tax", "keeps contemporaneous PPT evidence when structures set up.", "Contemporaneous file exists; relief OK.", "Retro narrative."],
  ["R&D claim AI model training boundary", "Tax", "boundaries experimental development versus routine model ops for R&D.", "Training experimental in; ops out.", "All ML in."],
  ["Group relief claimant insolvency screen", "Tax", "screens claimant/surrenderer insolvency risks affecting relief.", "Screen clear; claim OK.", "Insolvency risk missed."],
  ["Tax provision Monte Carlo rare use", "Tax", "documents when statistical simulation is used for UTP portfolios.", "Simulation used once; method noted.", "Black-box sim."],
  ["VAT call-off stock arrangements", "VAT", "controls call-off stock VAT simplifications and conditions.", "Conditions fail; full registration path.", "Simplification assumed."],
  ["Customs related-party valuation test", "Tax", "tests related-party import valuations for customs acceptability.", "Test supports TP price; duty OK.", "Related-party customs risk ignored."],
  ["Tax residency director travel log", "Tax", "logs director travel for residency/POEM risk management.", "Log shows majority UK; OK.", "Travel unlogged."],
  ["Patent box infringement damages stream", "Tax", "streams infringement damages correctly between qualifying/non.", "Stream applied; benefit accurate.", "All in box."],
  ["Enquiry alternative dispute resolution", "uncertain tax positions", "evaluates ADR paths for tax disputes with EV.", "ADR chosen; EV better.", "Litigate default."],
  ["TP COVID government support adjust", "transfer pricing", "adjusts tested party results for abnormal government support.", "Support adjusted out; margin comparable.", "Unadjusted support."],
  ["Tax cash in liquidity covenant defs", "Tax", "checks whether tax payments are in liquidity covenant definitions.", "Included; forecast aligned.", "Covenant surprise."],
  ["Dependent agent commissionaire review", "Tax", "reviews commissionaire/agent models under PE rules post-MLI.", "Terms agency-safe; checklist signed.", "Old commissionaire risk."],
  ["DST registration multi-country", "Tax", "tracks multi-country DST registrations as footprint grows.", "Two countries registered; calendars live.", "Single-country view."],
  ["Deferred tax on climate provisions", "deferred tax", "assesses DT on climate/environmental provisions by deductibility timing.", "Deduction on spend; DTA timed.", "Immediate DTA wrong."],
  ["CFC excluded territories list update", "Tax", "updates excluded/territorial lists for CFC screening.", "List update catches one entity.", "Stale list."],
  ["MAP correlative relief collection risk", "transfer pricing", "assesses collection risk on MAP relief receivables.", "Collection risk low; full carry.", "Ignore collection."],
  ["Off-payroll end-client risk transfer myth", "Tax", "rejects myths that contractual risk transfer defeats off-payroll.", "Status by facts; contract secondary.", "Contractual defeat myth."],
  ["Tax calc hash immutability filing", "Tax", "hashes filed computations for immutability evidence.", "Hash stored; enquiry reproducible.", "Editable comps."],
  ["Share deal tax due diligence red flag", "Tax", "standardises tax DD red-flag lists for share deals.", "Red flags drive price chips.", "Ad-hoc DD."],
  ["Tax KRI leading enquiry open rate", "Tax", "tracks new enquiry open rates as a leading tax risk KRI.", "Open rate up; prep capacity added.", "Lagging only."],
  ["Hybrid mismatch imported mismatch hybrid", "Tax", "traces imported mismatch through chains of hybrids.", "Chain denial £0.6m; restructure.", "Single-hop only."],
  ["Tax close SOX evidence binder", "close process", "binds SOX/ICFR evidence for tax key controls each quarter.", "Binder complete; OE tested.", "Evidence scattered."],
  ["WHT reclaim statute tracker", "Tax", "tracks statutes for WHT reclaim filing abroad.", "SOL near; claim filed.", "SOL miss."],
  ["R&D claim dual scheme anti-double", "Tax", "prevents double claiming under overlapping R&D schemes.", "Anti-double check clean.", "Double claim risk."],
  ["Group relief payment for delivery", "Tax", "documents payment arrangements for group relief delivery where used.", "Payment agreed; transfer priced if needed.", "Informal delivery."],
  ["Tax note contingency wording library", "Tax", "libraries approved contingency wordings for tax notes.", "Library speeds disclosure committee.", "Rewrite each time."],
  ["VAT postponed VAT accounting control", "VAT", "controls postponed VAT accounting on imports.", "PVA postings recon daily.", "PVA breaks age."],
  ["Customs transfer pricing year-end sync", "Tax", "syncs year-end TP adjustments to customs valuation processes.", "Sync triggers customs true-up review.", "TP adjust; customs stale."],
  ["Tax residency alternate director risk", "Tax", "assesses alternate director decision locations for POEM risk.", "Alternates briefed; decisions UK.", "Alternates decide abroad."],
  ["Patent box qualifying expenditure nexus", "Tax", "tracks qualifying expenditure for nexus including acquisitions.", "Acquired IP nexus fraction computed.", "Acquisition ignored in nexus."],
  ["UTP interest rate selection policy", "uncertain tax positions", "policies interest rates used on UTP accruals.", "Statutory underpayment rate used; consistent.", "Ad-hoc rates."],
  ["TP local file language translation control", "transfer pricing", "controls quality of translated local files where required.", "Translation QA catch; fixed.", "Bad translation filed."],
  ["Tax cash board liquidity appendix", "Tax", "appendixes material tax cash to board liquidity packs when large.", "Appendix shows instalment cliff.", "Tax cash invisible."],
  ["Fixed place PE home office test", "Tax", "tests home-office fixed place PE risk under local guidance.", "Home office not PE; agency risk higher—focus agency.", "Home office panic only."],
  ["DST safe harbour or threshold monitor", "Tax", "monitors DST thresholds/safe harbours as groups restructure.", "Threshold crossed post-acquisition; registered.", "Restructure threshold miss."],
  ["Deferred tax on leasehold improvements", "deferred tax", "addresses DT on leasehold improvements versus tax capital allowances.", "Temps inventoried; DT booked.", "Improvements ignored."],
  ["CFC upstream loan rules", "Tax", "applies upstream loan CFC/anti-avoidance rules where relevant.", "Upstream loan triggers inclusion.", "Loan ignored."],
  ["MAP corresponding adjustment cash timing", "transfer pricing", "models cash timing of corresponding adjustments in MAP.", "Cash lag 18 months; receivable held.", "Assume instant cash."],
  ["Off-payroll statement of work control", "Tax", "controls SOWs so they match SDS status determinations.", "SOW contradicts SDS; both fixed.", "SOW vs SDS mismatch."],
  ["Tax system privileged access review", "Tax", "reviews privileged access to tax engines monthly in filing season.", "Privilege excess removed.", "Everyone admin."],
  ["Asset deal VAT option to tax property", "Tax", "evaluates option to tax on property in asset deals.", "Option exercised; VAT recovery path clear.", "Option ignored."],
  ["Tax appetite soft/hard definition card", "Tax", "cards soft versus hard tax appetite breach definitions.", "Card used; escalation correct.", "Soft/hard confusion."],
  ["Hybrid mismatch disregarded transaction", "Tax", "identifies disregarded transactions creating hybrid outcomes.", "Disregarded repo denied; restructure.", "Form over substance miss."],
  ["Tax close estimate versus final return", "close process", "bridges tax provision estimates to final returns with true-up discipline.", "True-up £0.3m within threshold; OK.", "Huge unexplained true-ups."],
  ["Treaty shopping financing conduit test", "Tax", "tests financing conduits for treaty shopping risk before WHT relief.", "Conduit risk; full WHT.", "Treaty rate to conduit."],
  ["R&D claim overseas EPW rules", "Tax", "applies overseas externally provided worker rules in R&D claims.", "Overseas EPW limited; claim compliant.", "All EPW in."],
  ["Group relief arrangement commercial purpose", "Tax", "evidences commercial purpose for group relief arrangements.", "Purpose memo filed; claim OK.", "Tax-only arrangement risk."],
  ["Tax provision AC challenge log", "Tax", "logs AC challenges on tax judgements and management responses.", "Challenge on DTA; evidence strengthened.", "Unlogged challenges."],
  ["VAT retail scheme eligibility", "VAT", "checks ongoing eligibility for retail schemes where used.", "Eligibility fails; standard method adopted.", "Scheme after ineligible."],
  ["Customs related-party first sale claim", "Tax", "evidences first-sale customs valuation claims carefully.", "First-sale evidence weak; claim dropped.", "First-sale without evidence."],
  ["Tax residency secretary protocol card", "Tax", "cards company secretary protocols for residency-sensitive actions.", "Card prevents overseas decision minutes.", "Secretary improvises."],
  ["Patent box streaming IP income map", "Tax", "maps IP income to streams under streaming elections.", "Map complete; elections match.", "Unmapped streams."],
  ["Enquiry joint defence privilege", "uncertain tax positions", "manages joint defence privilege when multi-entity enquiries overlap.", "Joint defence protocol; privilege kept.", "Privilege fractured."],
  ["TP terminal loss comparable adjust", "transfer pricing", "adjusts for terminal losses in comparable sets with policy.", "Terminal loss excluded; policy applied.", "Cherry terminal."],
  ["Tax cash scenario in recovery plan", "Tax", "includes severe tax cash scenarios in recovery/liquidity plans when relevant.", "Tax audit severe in recovery options.", "Recovery tax-blind."],
  ["Agent PE habitually concludes test", "Tax", "tests whether persons habitually conclude or play principal role.", "Test fails; authority cut.", "Title 'agent' reliance."],
  ["DST group threshold aggregation", "Tax", "aggregates group revenues correctly for DST thresholds.", "Aggregation crosses threshold; registered.", "Entity-only threshold."],
  ["Deferred tax on decommissioning", "deferred tax", "handles DT on decommissioning provisions versus tax deductions.", "Deduction on spend; DTA timed.", "Immediate full DTA."],
  ["CFC excluded dividend categories", "Tax", "categorises dividends for CFC exclusions carefully.", "Category fails; inclusion.", "All dividends excluded myth."],
  ["MAP advance pricing after dispute", "transfer pricing", "considers APA after MAP to prevent repeat disputes.", "APA launched post-MAP; recurrence down.", "MAP then repeat."],
  ["Off-payroll medium-sized exemption test", "Tax", "tests medium-sized client exemptions under off-payroll rules.", "Exemption fails growth; SDS now required.", "Stale exemption."],
  ["Tax filing calendar mega-critical path", "Tax", "maintains critical path across multi-country filing calendars.", "Critical path prevents clash; filings on time.", "Calendar collisions."],
  ["Share deal locked-box tax leakage SPA", "Tax", "drafts SPA leakage schedules covering tax specifically.", "Schedule catches £0.5m; chipped.", "Leakage tax-blind."],
  ["Tax KRI data lineage certificate", "Tax", "certificates lineage of board tax KRIs quarterly.", "Certificate fails one KRI; footnoted.", "Unknown lineage."],
  ["Hybrid mismatch dual inclusion income", "Tax", "identifies dual inclusion income that can turn off hybrid denials.", "DII present; deduction allowed with evidence.", "Denial without DII check."],
  ["Tax close remote working evidence", "close process", "evidences remote close controls still operate effectively.", "Remote OE sample OK.", "Remote assumed fine."],
  ["WHT rate most-favoured treaty check", "Tax", "checks most-favoured/protocol rates before applying WHT.", "Protocol rate better; applied with cert.", "Main treaty only."],
  ["R&D claim consumables boundary", "Tax", "boundaries consumables/quantifiable materials in R&D claims.", "Boundary applied; claim accurate.", "All materials in."],
  ["Group relief notional transfer pricing", "Tax", "considers whether payments for group relief need arm's length review.", "Payment at value; TP note filed.", "Payment ignored."],
  ["Tax provision estimation uncertainty note", "Tax", "drafts estimation uncertainty disclosures for material tax estimates.", "Uncertainty note on Pillar Two first year.", "False precision."],
  ["VAT TOGC conditions checklist", "VAT", "checklists transfer of going concern VAT conditions on deals.", "TOGC conditions met; no VAT on assets.", "TOGC assumed wrongly."],
  ["Customs royalty trademark link", "Tax", "links trademark royalties to customs dutiability tests.", "Trademark royalty dutiable; uplifted.", "Royalty customs miss."],
  ["Tax residency hybrid meeting minutes", "Tax", "minutes hybrid physical/video meetings with location of decision-makers.", "Minutes show UK majority; OK.", "Hybrid location unclear."],
  ["Patent box acquired IP nexus fraction", "Tax", "computes nexus for acquired IP under relevant rules.", "Acquired IP nexus lower; benefit cut.", "Acquired as self-developed."],
  ["UTP release on SOL expiry control", "uncertain tax positions", "controls UTP releases on SOL expiry with evidence.", "SOL evidence → £0.5m release.", "Early release."],
  ["TP regional hub characterisation", "transfer pricing", "characterises regional hubs as routine versus entrepreneurial correctly.", "Hub routine; residual to principal.", "Hub takes residual wrongly."],
  ["Tax cash instalment holiday rules", "Tax", "applies instalment holiday/threshold rules correctly when available.", "Holiday applies; cash smoothed.", "Holiday missed."],
  ["Server location PE cloud multi-region", "Tax", "assesses multi-region cloud footprints for PE risk prioritisation.", "People functions dominate risk; cloud low.", "Cloud region obsession."],
  ["DST accounting policy consistency", "Tax", "keeps DST accounting policy consistent across periods.", "Policy unchanged; comparatives OK.", "Policy flip."],
  ["Deferred tax on warranty provisions", "deferred tax", "times DT on warranty provisions to tax deduction rules.", "Deduction on claim; DTA timed.", "Immediate DTA."],
  ["CFC insurance captive diversion", "Tax", "assesses captives for diversion/CFC insurance rules.", "Captive fails; inclusion.", "Captive safe myth."],
  ["MAP file retention schedule", "transfer pricing", "schedules retention for MAP files beyond normal tax retention.", "Retention 12 years; vaulted.", "Early destruction."],
  ["Off-payroll agency failing SDS flow", "Tax", "detects agency failures to pass SDS downstream.", "Failure detected; payments held.", "Broken chain."],
  ["Tax engine calc parallel run filing", "Tax", "parallel-runs tax engine versions before filing season upgrades.", "Parallel OK; upgrade proceeds.", "Upgrade mid-season blind."],
  ["Share deal tax disclosure letter process", "Tax", "processes tax disclosure letters against warranty schedules systematically.", "Process catches undisclosed enquiry.", "Unread disclosures."],
  ["Tax appetite metric owner RACI", "Tax", "assigns RACI owners for each tax appetite metric.", "Owners clear; breaches escalate.", "Orphan metrics."],
  ["Hybrid mismatch imported mismatch hybrid2", "Tax", "re-tests imported mismatch after structure tweaks.", "Tweak fails; denial remains.", "Assume tweak fixes."],
  ["Tax close estimate roll to return", "close process", "rolls tax estimates to returns with controlled true-ups.", "Roll variance explained; OK.", "Mystery true-up."],
  ["Treaty LOB derivative benefits test", "Tax", "applies derivative benefits LOB tests where available.", "Derivative benefits pass; reduced WHT.", "LOB fail without derivative test."],
  ["R&D claim prototype sale proceeds", "Tax", "adjusts R&D claims for prototype sale proceeds per rules.", "Proceeds reduce qualifying; claim adjusted.", "Proceeds ignored."],
  ["Group relief jurisdiction mismatch", "Tax", "prevents relief claims across mismatched tax jurisdictions wrongly.", "Mismatch blocked; local only.", "Cross-jurisdiction myth."],
  ["Tax note Pillar Two qualitative first year", "Tax", "drafts first-year Pillar Two qualitative disclosures with known gaps stated.", "Gaps stated; AC OK.", "False completeness."],
  ["VAT reverse charge domestic listing recon", "VAT", "recons domestic RC listings to GL.", "Recon clean; filed.", "Listing ≠ GL."],
  ["Customs first sale related-party ban", "Tax", "checks first-sale claims are not defeated by related-party rules.", "Related-party defeats first sale; dropped.", "First sale despite related."],
  ["Tax residency quorum video majority", "Tax", "assesses whether video majorities satisfy POEM expectations.", "Majority UK locations; OK.", "Majority abroad risk."],
  ["Patent box streaming IP cost share", "Tax", "allocates IP costs across streams under streaming.", "Cost share matches income streams.", "Unallocated costs."],
  ["Enquiry ADR outcome accounting", "uncertain tax positions", "accounts ADR outcomes promptly into UTP measurements.", "ADR settle £1m; UTP updated.", "ADR then delay."],
  ["TP hub financing characterisation", "transfer pricing", "characterises hub financing as treasury routine versus risk-bearing.", "Routine treasury; thin return.", "Hub takes credit residual."],
  ["Tax cash downside in revolver sizing", "Tax", "includes downside tax cash in revolver sizing analyses.", "Revolver +£50m for tax downside.", "Revolver tax-blind."],
  ["Dependent agent warehouse combo PE", "Tax", "assesses combined warehouse + agent PE risks together.", "Combo elevates PE; model revised.", "Separate silo tests."],
  ["DST threshold currency translation", "Tax", "translates revenues to DST threshold currencies consistently.", "Translation policy fixed; threshold correct.", "Inconsistent FX."],
  ["Deferred tax on share buyback tax", "deferred tax", "addresses DT impacts of share buyback taxes/surcharges where applicable.", "Buyback tax current; DT considered.", "Buyback tax ignored."],
  ["CFC diverted profits overlap memo", "Tax", "memos CFC/DPT overlap to choose accounting path.", "CFC path; DPT not notified; memo filed.", "Double count."],
  ["MAP interest correlative relief policy", "transfer pricing", "policies interest on MAP relief per competent authority outcomes.", "Interest per outcome; booked.", "Interest policy none."],
  ["Off-payroll status determination audit", "Tax", "audits SDS quality sample each quarter with flips accrued.", "Audit flips one; £40k accrued.", "Never audit SDS."],
  ["Tax system immutable calc archive", "Tax", "archives immutable calculation packs per return year.", "Archive used in enquiry; OK.", "Lost calcs."],
  ["Asset deal capital allowances continuity", "Tax", "models capital allowances continuity/elections in asset deals.", "Election preserves pools; valued.", "Pools lost surprise."],
  ["Tax KRI threshold recalibration volume", "Tax", "recalibrates tax KRI thresholds when volumes change.", "Return volume up; late-filing KRI recalibrated to rate.", "Stale count thresholds."],
  ["Hybrid mismatch dual inclusion evidence", "Tax", "evidences dual inclusion income to support deductions.", "DII evidence pack; deduction kept.", "DII claimed bare."],
  ["Tax close foreign rate enactment watch", "close process", "watches foreign rate enactments into deferred tax cut-off.", "Enactment post-date; disclose.", "Wrong rate."],
  ["WHT beneficial ownership financing ROE", "Tax", "includes ROE/financing returns in BO analysis for holding companies.", "Thin ROE; conduit risk; full WHT.", "Ownership certificate only."],
  ["R&D claim cloud GPU qualifying split", "Tax", "splits GPU cloud costs between experimental and routine ops.", "Split 60/40; evidenced.", "All GPU in."],
  ["Group relief payment TP documentation", "Tax", "documents TP for payments made for group relief delivery.", "Payment at arm's length; file OK.", "Payment undocumented."],
  ["Tax provision first-year Pillar Two range", "Tax", "discloses estimation ranges for first-year Pillar Two accruals.", "Range £1–3m; midpoint accrued.", "False point precision."],
  ["VAT TOGC anti-avoidance conditions", "VAT", "checks TOGC anti-avoidance conditions beyond basic checklist.", "Anti-avoidance OK; TOGC stands.", "Basic TOGC only."],
  ["Customs royalty know-how dutiability", "Tax", "tests know-how royalties for customs dutiability.", "Know-how dutiable; uplifted.", "Know-how missed."],
  ["Tax residency director decision log", "Tax", "logs which directors took which decisions for POEM evidence.", "Log supports UK POEM.", "Anonymous decisions."],
  ["Patent box qualifying IP licence chain", "Tax", "evidences licence chains for qualifying IP income.", "Chain complete; claim OK.", "Broken licence chain."],
  ["UTP measurement most likely vs EV switch", "uncertain tax positions", "documents switches between MLE and EV methods with rationale.", "Switch to EV on portfolio; logged.", "Silent method switch."],
  ["TP entrepreneurial residual loss share", "transfer pricing", "allocates residual losses to entrepreneurs consistently with residual profits.", "Residual loss to principal; routine protected.", "Routine eats residual loss."],
  ["Tax cash in going concern severe case", "Tax", "puts severe tax cash in GC severe but plausible cases when material.", "Severe enquiry in GC severe case.", "GC mild on tax."],
  ["Fixed place PE server farm test", "Tax", "tests server farm/fixed place PE with people function overlay.", "Servers alone low; people onsite higher.", "Servers = PE always."],
  ["DST marketplace seller versus facilitator", "Tax", "distinguishes seller versus facilitator DST obligations.", "Facilitator obligations apply; accrued.", "Seller-only wrong."],
  ["Deferred tax on onerous contracts", "deferred tax", "times DT on onerous contract provisions to tax rules.", "Deduction on spend; DTA timed.", "Immediate DTA."],
  ["CFC low-tax marker list update", "Tax", "updates low-tax marker lists used in CFC screens.", "Update catches one territory.", "Stale markers."],
  ["MAP arbitration timeline tracker", "transfer pricing", "tracks MAP arbitration timelines to pressure resolution.", "Timeline nearing; strategy escalates.", "MAP endless."],
  ["Off-payroll group exemption growth fail", "Tax", "retests group exemptions when headcount/turnover growth may fail them.", "Growth fails exemption; SDS now.", "Stale exemption."],
  ["Tax filing critical path owner", "Tax", "names a single critical-path owner across multi-country filings.", "Owner prevents collisions.", "No owner."],
  ["Share deal tax leakage locked-box quant", "Tax", "quantifies locked-box tax leakage with diligence support.", "£0.6m quant; chip agreed.", "Qual leakage."],
  ["Tax appetite hard breach 24h pack", "Tax", "assembles 24h packs for hard tax appetite breaches.", "Pack to chair in 16h.", "Slow pack."],
  ["Hybrid mismatch reverse hybrid investor", "Tax", "traces reverse hybrid outcomes to investors' tax treatments.", "Investor inclusion; payer path clear.", "Reverse hybrid miss."],
  ["Tax close ICFR OE sample tax engine", "close process", "OE-samples tax engine access and calc review controls.", "OE sample 25; 1 fail remediated.", "Design-only."],
  ["Treaty protocol MFN rate apply", "Tax", "applies MFN protocol rates when beneficial and evidenced.", "MFN rate applied with cert.", "MFN ignored."],
  ["R&D claim dual listing cost allocate", "Tax", "allocates dual-purpose costs between R&D and non-R&D rigorously.", "Allocate 40% R&D; evidenced.", "100% dual-purpose in."],
  ["Group relief surrenderer capacity proof", "Tax", "proves surrenderer has capacity/losses before claimant plans.", "Proof attached; claim OK.", "Phantom surrender."],
  ["Tax note estimation range first Pillar", "Tax", "ranges first Pillar Two estimates in the tax note.", "Range disclosed; midpoint booked.", "Point only."],
  ["VAT call-off stock condition fail path", "VAT", "paths actions when call-off stock conditions fail.", "Fail → register; done in 10 days.", "Fail ignored."],
  ["Customs TP year-end true-up sync", "Tax", "syncs TP true-ups to customs entries/adjustments.", "Sync triggers customs amendment.", "TP yes; customs no."],
  ["Tax residency alternate director briefing", "Tax", "briefs alternate directors on residency-sensitive decision rules.", "Briefing done; no overseas decisions.", "Alternates unbriefed."],
  ["Patent box nexus subcontractor overseas", "Tax", "hits nexus for overseas subcontractors under patent box rules.", "Overseas sub hits nexus; benefit down.", "Overseas ignored."],
  ["Enquiry production log checksum", "uncertain tax positions", "checksums document productions to authorities for integrity.", "Checksum mismatch caught; resent.", "Corrupt production."],
  ["TP seasonal adjust policy note", "transfer pricing", "notes policy for seasonal adjustments in benchmarks.", "Policy applied consistently.", "Ad-hoc seasonal."],
  ["Tax cash revolver headroom link", "Tax", "links tax cash cliffs to revolver headroom dashboards.", "Cliff visible; headroom OK.", "Hidden cliff."],
  ["Agent PE CRM authority report", "Tax", "reports CRM authority levels that create agent PE risk.", "Report finds conclude rights; cut.", "CRM authority unknown."],
  ["DST multi-country calendar owner", "Tax", "owns multi-country DST filing calendars centrally.", "Owner prevents miss.", "Local orphans."],
  ["Deferred tax on restructuring provisions", "deferred tax", "times DT on restructuring provisions to local deductibility rules.", "Deduction on spend; DTA timed with recoverability.", "Immediate DTA on announcement."],
  ["CFC upstream hybrid financing screen", "Tax", "screens upstream hybrid financing for CFC and hybrid overlaps.", "Screen triggers inclusion path; double count avoided.", "Overlaps missed."],
  ["MAP endgame arbitration readiness", "transfer pricing", "readies arbitration evidence packs before MAP stalls.", "Pack ready; timeline pressure applied.", "MAP without endgame."],
  ["Off-payroll SDS quality scorecard", "Tax", "scorecards SDS quality by business unit quarterly.", "Scorecard drives coaching; flips down.", "No SDS QA."],
  ["Tax engine filing season freeze window", "Tax", "freezes non-emergency tax engine changes in filing windows.", "Freeze held; one emergency aftercare OK.", "Change mid-file."],
  ["Share deal tax attribute continuity model", "Tax", "models continuity and restriction of tax attributes in share deals.", "Loss restriction modelled; price adjusted.", "Attributes assumed survive."],
  ["Tax KRI soft breach rewrite trigger", "Tax", "triggers appetite rewrite consideration after repeated soft KRI breaches.", "Three softs → rewrite paper.", "Softs ignored."],
  ["Hybrid mismatch dual inclusion pack", "Tax", "packs evidence of dual inclusion income to support deductions.", "DII pack keeps deduction.", "Bare DII claim."],
  ["Tax close foreign UTP FX policy", "close process", "policies FX on foreign-currency UTPs each close.", "FX £0.12m; explained.", "FX ignored."],
  ["Treaty shopping conduit financing test", "Tax", "tests financing conduits for treaty shopping before reduced WHT.", "Conduit; full WHT.", "Treaty to conduit."],
  ["R&D claim experimental vs routine AI", "Tax", "splits experimental AI development from routine model operations in claims.", "Training in; inference ops out.", "All AI in."],
  ["Group relief commercial purpose memo", "Tax", "memos commercial purpose for group relief arrangements.", "Purpose memo filed; claim OK.", "Tax-only arrangement."],
  ["Tax provision tornado for AC", "Tax", "presents tornado sensitivities of key tax judgements to AC.", "UTP/DTA tornado used.", "Point only."],
  ["VAT postponed accounting recon", "VAT", "recons postponed VAT accounting postings to import entries.", "Recon daily; breaks aged.", "PVA breaks roll."],
  ["Customs TP true-up amendment path", "Tax", "paths customs amendments when TP year-end true-ups change import values.", "Amendment filed; duty true-up.", "TP adjust; customs stale."],
  ["Tax residency hybrid meeting location", "Tax", "records decision-maker locations in hybrid board meetings.", "UK majority; POEM OK.", "Locations unclear."],
  ["Patent box licence chain evidence", "Tax", "evidences licence chains for qualifying IP income.", "Chain complete; claim OK.", "Broken chain."],
  ["UTP method switch control", "uncertain tax positions", "controls switches between EV and most-likely methods with rationale.", "Switch logged; EV on portfolio.", "Silent switch."],
  ["TP residual loss to entrepreneur", "transfer pricing", "allocates residual losses to entrepreneurs consistently with residual profits.", "Loss to principal; routine protected.", "Routine absorbs residual loss."],
  ["Tax cash in severe GC case", "Tax", "includes severe tax cash in going-concern severe cases when material.", "Severe enquiry in GC pack.", "GC tax-mild."],
  ["Fixed place PE people overlay", "Tax", "overlays people functions on fixed-place/server PE analyses.", "People dominate; servers secondary.", "Servers = PE always."],
  ["DST facilitator versus seller", "Tax", "distinguishes marketplace facilitator versus seller DST roles.", "Facilitator applies; accrued.", "Seller-only wrong."],
  ["Deferred tax onerous contract timing", "deferred tax", "times DT on onerous contracts to deduction rules.", "Deduction on spend; DTA timed.", "Immediate DTA."],
  ["CFC low-tax list refresh", "Tax", "refreshes low-tax marker lists used in CFC screens.", "Refresh catches one entity.", "Stale list."],
  ["MAP arbitration tracker", "transfer pricing", "tracks MAP arbitration timelines to force resolution strategy.", "Timeline near; escalate.", "Endless MAP."],
  ["Off-payroll exemption growth retest", "Tax", "retests size exemptions when growth may cause failure.", "Growth fails; SDS required.", "Stale exemption."],
  ["Tax filing critical path single owner", "Tax", "names one owner for multi-country filing critical path.", "Owner prevents clashes.", "No owner."],
  ["Locked-box tax leakage quant DD", "Tax", "quantifies locked-box tax leakage in diligence for chips.", "£0.55m chip agreed.", "Qual only."],
  ["Tax hard breach 24h evidence", "Tax", "assembles evidence within 24h of hard tax appetite breaches.", "Pack in 14h to chair.", "Slow notify."],
  ["Reverse hybrid investor trace", "Tax", "traces reverse hybrid outcomes through to investors.", "Investor inclusion; payer clear.", "Reverse hybrid miss."],
  ["Tax engine OE sample quarterly", "close process", "OE-samples tax engine access and calculation review controls.", "Sample 25; one fail fixed.", "Design-only."],
  ["Treaty MFN protocol rate", "Tax", "applies MFN/protocol rates when better and evidenced.", "MFN applied with cert.", "MFN ignored."],
  ["R&D dual-purpose cost allocate", "Tax", "allocates dual-purpose costs between R&D and non-R&D with evidence.", "40% R&D; evidenced.", "100% dual in."],
  ["Group relief surrender proof", "Tax", "proves surrenderer losses/capacity before claimant plans.", "Proof attached.", "Phantom surrender."],
  ["Pillar Two first-year range note", "Tax", "discloses ranges for first-year Pillar Two estimates.", "£1–3m range; midpoint accrued.", "False precision."],
  ["Call-off stock fail path", "VAT", "paths registration when call-off stock conditions fail.", "Fail → register in 10 days.", "Fail ignored."],
  ["Customs amendment after TP true-up", "Tax", "amends customs when TP true-ups change values.", "Amendment + duty true-up.", "Customs stale."],
  ["Alternate director residency brief", "Tax", "briefs alternate directors on residency-sensitive rules.", "No overseas decisions.", "Unbriefed alternates."],
  ["Patent box overseas sub nexus", "Tax", "applies nexus hits for overseas subcontractors.", "Benefit down; correct.", "Overseas ignored."],
  ["Enquiry production integrity checksum", "uncertain tax positions", "checksums productions to authorities for integrity.", "Mismatch caught; resent.", "Corrupt send."],
  ["Seasonal TP adjust policy", "transfer pricing", "applies a documented seasonal adjustment policy in benchmarks.", "Policy consistent.", "Ad-hoc seasonal."],
  ["Tax cash cliff on liquidity dash", "Tax", "shows tax cash cliffs on liquidity dashboards.", "Cliff visible; OK.", "Hidden cliff."],
  ["CRM authority agent PE report", "Tax", "reports CRM authorities that create agent PE risk.", "Conclude rights cut.", "Authority unknown."],
  ["DST multi-country owner", "Tax", "centrally owns multi-country DST calendars.", "Miss prevented.", "Local orphans."],
  ["Deferred tax restructuring timing", "deferred tax", "times DT on restructuring to deductibility.", "Spend basis; DTA timed.", "Announce-time DTA."],
]);
