import { expand } from "./wave3-shared.mjs";

/** Wave-3 COSO drafts — unique vs waves 1–2. */
export const COSO_WAVE3 = expand([
  ["Speak-up anonymity technical test", "Control environment", "tests whether speak-up channels technically preserve anonymity as promised.", "Pen-test finds metadata leak; fixed before campaign.", "Anonymity claimed, not tested."],
  ["Board ICFR private session minutes", "Control environment", "minutes private sessions where directors challenge ICFR without management.", "Private session challenges revenue cut-off; follow-up dated.", "No private ICFR time."],
  ["Control owner leave coverage test", "Control environment", "tests that backup owners actually operate controls during leave.", "Leave test fails; training funded.", "Backup named, never tested."],
  ["Valuation specialist independence from desk", "Control environment", "ensures valuation specialists used in ICFR are independent of profit-taking desks.", "Specialist reports to finance risk; OK.", "Desk marks own Level 3."],
  ["DOA system path sampling", "Control environment", "samples live system approval paths against the DOA matrix.", "Sample finds bypass; workflow fixed.", "Paper DOA only."],
  ["Commission plan fraud risk addendum", "Risk assessment", "adds fraud risk addenda whenever commission plans change.", "SPIFF addendum tightens cut-off tests.", "Plan change without fraud lens."],
  ["Hypercare control risk register", "Risk assessment", "keeps a hypercare risk register for 90 days post go-live.", "Hypercare finds recon gap; fixed before exit.", "Go-live then forget."],
  ["Objective-to-risk owner cascade", "Risk assessment", "cascades objective owners to process risk owners explicitly.", "Cascade clears orphan risks.", "Orphan process risks."],
  ["Deepfake payment fraud scenario", "Risk assessment", "adds deepfake/CEO fraud scenarios to the fraud library.", "Callback control designed after scenario.", "Cheque-era scenarios only."],
  ["Tolerance breach appetite bridge", "Risk assessment", "bridges repeated tolerance breaches into appetite discussions.", "Three breaches → appetite item.", "Tolerances reset quietly."],
  ["Assertion coverage gap sprint", "Control activities", "sprints to close RCM assertion coverage gaps before OE season.", "Inventory completeness gap closed in two weeks.", "Gaps into OE season."],
  ["Detective control time-to-detect SLA", "Control activities", "SLAs time-to-detect for detective controls on high risks.", "SLA 3 days; median 2.", "Unlimited detect lag."],
  ["Automated control drift alert tuning", "Control activities", "tunes drift alerts on automated control configurations.", "False positives down 50%; real disable caught.", "Alert fatigue."],
  ["SOD conflict exception register", "Control activities", "registers SOD conflicts with compensating controls and expiry.", "Conflict expires; access split.", "Eternal conflicts."],
  ["MRC investigation ticket standard", "Control activities", "standards tickets evidencing MRC investigations above thresholds.", "Tickets required >5% variance; sample OK.", "Signature-only MRC."],
  ["SOC CUC OE calendar sync", "Control activities", "syncs complementary control OE tests to SOC report periods and gaps.", "Gap period OE done; bridge OK.", "CUC listed, untested."],
  ["Policy exception mobile approval audit", "Control activities", "audits mobile/email approvals of policy exceptions for authenticity.", "Audit finds forwarded 'ok'; process tightened.", "Email ok forever."],
  ["High-risk vendor approval uplift", "Control activities", "uplifts approval tiers for high-risk vendors/jurisdictions.", "Uplift catches one risky vendor.", "Flat thresholds."],
  ["IPE checksum binding control", "Information and communication", "binds checksums on IPE spreadsheets used in key controls.", "Checksum change alerts reviewer.", "Editable IPE."],
  ["Control change quiz gate", "Information and communication", "gates period-end on quiz completion for changed controls.", "Incomplete quiz → backup operator used.", "Untrained operators."],
  ["APM definition freeze control", "Information and communication", "freezes APM definitions mid-year unless change-controlled.", "Silent change caught; reversed.", "Moving APM goalposts."],
  ["Retaliation analytics after speak-up", "Information and communication", "runs analytics for retaliation patterns after speak-up cases.", "Analytics clear; AC summary issued.", "No retaliation monitor."],
  ["Deficiency aggregation monetary factor", "Monitoring", "applies monetary aggregation factors alongside qualitative judgement.", "Five misses exceed factor; SD evaluated.", "Always inconsequential."],
  ["CCM precision quarterly review", "Monitoring", "reviews continuous monitoring precision/recall quarterly.", "Precision to 55%; investigators return.", "Ignored alerts."],
  ["Remediation OE sample size guide", "Monitoring", "guides OE sample sizes after remediation by risk.", "High control 25 samples; applied.", "One-item retest."],
  ["AC dashboard to memo drill path", "Monitoring", "ensures directors can drill from deficiency counts to memos.", "Drill used thrice; questions sharper.", "Counts only."],
  ["Points of focus evidence ageing", "Internal control framework", "ages points-of-focus evidence and forces refresh.", "Stale policy refreshed pre-assessment.", "Ancient evidence."],
  ["Weak information component contagion", "Internal control framework", "rates how weak information infects control activities ratings.", "Contagion analysis downgrades activities.", "Isolated component scores."],
  ["Scope complexity factors beyond size", "Internal control framework", "scopes entities using complexity/change/error history not only size.", "Small derivatives desk in scope.", "Size-only."],
  ["Manual journal night-time analytics", "Control environment", "analytics night/weekend manual journals for override risk.", "Night round-numbers investigated; reversed.", "No time analytics."],
  ["Strategy appetite workshop artefacts", "ERM", "files artefacts proving appetite considered at strategy setting.", "Canvas in board strategy pack.", "Appetite after strategy."],
  ["Portfolio correlation board commentary", "ERM", "adds correlation commentary to portfolio heat maps.", "Cyber-resilience correlation funded jointly.", "Dots without story."],
  ["Tolerance formula dictionary", "ERM", "dictionaries tolerance metric formulas and sources.", "Dictionary ends LCR maths debates.", "Undefined tolerances."],
  ["EXCO integrated pack template", "ERM", "templates integrated performance-risk packs for EXCO.", "Template shortens meetings.", "Two packs forever."],
  ["ERM trigger watcher RACI", "ERM", "assigns RACI watchers for each ERM refresh trigger.", "M&A trigger fired; refresh done.", "No watchers."],
  ["Emerging risk flash ack SLA", "ERM", "requires acknowledgement of emerging risk flashes within SLA.", "Ack in 20h; OK.", "Flash into void."],
  ["Culture KRI joint CRO-CHRO", "ERM", "joints CRO/CHRO ownership of culture KRI dashboards.", "Joint actions on challenge rate.", "HR-only culture."],
  ["Residual risk ROI budget ranking", "ERM", "ranks budget asks by residual risk reduction per pound.", "Top reducers funded; pet project cut.", "Loudest wins."],
  ["ELC attestation follow-up OE", "Control environment", "OE-tests follow-up on ELC attestation non-responders.", "Follow-ups complete; ELC OE OK.", "Non-responders ignored."],
  ["CUC OE in SOC gap period", "Control activities", "OE-tests complementary controls covering SOC bridge gaps.", "Gap OE done; reliance OK.", "Bridge unread."],
  ["MW early indicator set live", "Monitoring", "lives early indicators that may foreshadow MW evaluation.", "Restatement talk + ITGC fails → MW memo early.", "Wait for auditor letter."],
  ["SD communication SLA clock", "Monitoring", "clocks SD communication to AC/auditor within policy.", "Day 7 of 10; OK.", "Informal months."],
  ["Root-cause taxonomy trend board", "Monitoring", "boards trending deficiency root causes for systemic fixes.", "Training 50% → academy funded.", "Symptom fixes."],
  ["Provision 29 evidence hyperlink index", "Internal control framework", "indexes Provision 29 evidence with hyperlinks to artefacts.", "Dry-run external review passes.", "Declaration bare."],
  ["IA coverage confirmation letter", "Risk assessment", "letters confirm IA/second-line coverage of top residuals with gaps listed.", "One gap accepted with rationale.", "Assumed coverage."],
  ["Control library local deviation expiry", "Control activities", "expires local deviations from standard control library.", "Deviation expires; standard adopted.", "Eternal locals."],
  ["Data exception auto-escalate ICFR", "Information and communication", "auto-escalates aged data exceptions to ICFR lead.", "Escalate at day 14; cleared.", "Ops-only ageing."],
  ["Board cyber literacy assessment", "Control environment", "assesses board cyber literacy after modules.", "Assessment gap filled with adviser.", "Module without assessment."],
  ["Opportunity register appetite tag", "ERM", "tags opportunities as inside/outside appetite with mitigations.", "Outside appetite blocked.", "Silent outside pursuits."],
  ["Evidence WORM repository control", "Control activities", "stores key control evidence in WORM/immutable repositories.", "WORM on; audit clean.", "Editable shares."],
  ["IA reliance memo template enforce", "Monitoring", "enforces reliance memo templates with reperformance %.", "Template blocks blind reliance.", "One-line reliance."],
  ["Assertion support file hyperlink", "Internal control framework", "hyperlinks assertion support files for walkthroughs.", "Auditor walkthrough smooth.", "Memory assertion."],
  ["Reassessment SLA breach report", "Risk assessment", "reports SLA breaches on post-trigger reassessments.", "One breach explained; median OK.", "No SLA."],
  ["CCM bot RACI finance-IT", "Monitoring", "splits RACI for CCM bots between finance rules and IT platform.", "RACI clear; tuning owned.", "Orphan bot."],
  ["Points of focus policy crosswalk", "Internal control framework", "crosswalks points of focus to policies; gaps drafted.", "Two policies drafted.", "No anchors."],
  ["Shared service KPI to entity CFO", "Information and communication", "sends shared-service control KPIs to entity CFOs monthly.", "Challenge improves close.", "Opaque SSC."],
  ["Crisis compensating catalogue exit", "Control activities", "catalogues crisis compensating controls with hard exit criteria.", "Exited day 40; OK.", "Crisis forever."],
  ["SOC bridge completeness weeks", "Monitoring", "checks bridge letters cover all weeks to period-end.", "Missing week → extra CUC test.", "Bridge filed unread."],
  ["Attestation exception auto-log", "Control environment", "auto-logs attestation-disclosed exceptions into deficiency log.", "Three auto-logged; none lost.", "Exceptions vanish."],
  ["ICAAP ERM scenario recon annual", "ERM", "recons ICAAP scenarios to ERM principal risks annually.", "Adds supply scenario from ERM.", "Diverge unexplained."],
  ["Control skip missing-data escalate", "Information and communication", "escalates control skips caused by missing data.", "Skip escalates; feed fixed.", "Silent skips."],
  ["Monitoring rule change reason codes", "Monitoring", "requires reason codes for monitoring rule changes.", "Reason logged; false positives cut.", "Live unapproved edits."],
  ["Realised loss score feedback", "ERM", "feeds realised losses back to recalibrate prior risk scores.", "Missed scores uplifted.", "Scores never checked."],
  ["Anti-fraud suite integrated OE", "Control environment", "OE-tests anti-fraud ELC suite as an integrated set annually.", "Hotline awareness gap found.", "Fragmented tests."],
  ["Risk score confidence flag enforced", "Risk assessment", "enforces low-confidence flags when input data poor.", "Cyber low confidence until inventory 95%.", "False precision."],
  ["Spreadsheet IPE quarterly certify", "Control activities", "certifies ICFR spreadsheet inventory quarterly.", "Two new high-risk sheets controlled.", "Unknown sheets."],
  ["Director challenge action rate", "Monitoring", "metrics rate at which director challenges produce dated actions.", "Rate 65%; target 80%.", "Challenges die."],
  ["Outsourcer ICFR vendor day", "Control activities", "holds annual ICFR expectation days with critical outsourcers.", "Evidence formats aligned.", "Annual surprise."],
  ["Incentive feed to fraud assessment", "Risk assessment", "feeds incentive plan data into fraud risk assessment automatically.", "SPIFF spike flagged; assessment updated.", "Blind to incentives."],
  ["Customer-impact deficiency tag", "Monitoring", "tags deficiencies with customer impact for remediation priority.", "Customer-impacting first.", "Equal priority."],
  ["Digital risk taxonomy ERM update", "ERM", "updates ERM taxonomy for digital/AI risks as products change.", "Adds data poisoning.", "Legacy taxonomy."],
  ["Crisis information cadence playbook", "Information and communication", "playbooks crisis cadences for control-relevant information.", "Twice-daily close calls in outage.", "BAU cadence in crisis."],
  ["Monitoring coverage heat map live", "Monitoring", "heats ongoing vs separate evaluation coverage by process.", "Treasury sparse; IA added.", "Unknown coverage."],
  ["New control owner COSO onboarding", "Control environment", "onboards new control owners on COSO duties within 30 days.", "100% onboarding this quarter.", "Owners unbriefed."],
  ["Inherent score example guide", "Risk assessment", "guides inherent scoring with monetary/reputational examples.", "Variance across units falls.", "Incomparable scores."],
  ["Design effectiveness pre-OE gate", "Control activities", "gates OE testing behind design effectiveness pass.", "Design fail redesigns cheaper.", "OE on broken design."],
  ["Board ICFR mini-case education", "Control environment", "educates boards with anonymised ICFR mini-cases.", "Aggregation case used in AC hour.", "Framework lecture only."],
  ["Appetite breach simulation annual", "ERM", "simulates appetite breaches annually to rehearse paths.", "Soft/hard path clarified in ToR.", "First breach is first drill."],
  ["External auditor reliance dialogue", "Monitoring", "structures dialogue on external auditor reliance on management testing.", "Reliance areas documented.", "Surprise retesting all."],
  ["Control pressure pulse survey", "Control environment", "pulses short surveys on pressure to override controls.", "Sales pressure spike; intervene.", "Annual only."],
  ["Emerging tech risk lens workshop", "Risk assessment", "applies emerging-tech lens in risk workshops.", "Adds AI hallucination risk.", "Legacy questions only."],
  ["Key report hash binding", "Information and communication", "binds hashes on key system reports used in controls.", "Hash change alerts ICFR lead.", "Silent report edits."],
  ["Severity matrix worked examples", "Monitoring", "provides worked examples for SD vs MW judgements.", "Debates shorten.", "Reinvented each time."],
  ["COSO component section owners", "Internal control framework", "names owners for each COSO component assessment section.", "On-calendar delivery.", "One writer alone."],
  ["Subprocessor ICFR visibility", "Control activities", "extends vendor risk to subprocessors affecting ICFR processes.", "Payroll subprocessor flagged high.", "Prime-only diligence."],
  ["Detection model light model-risk", "Monitoring", "applies light model-risk discipline to detection models.", "Tuning log documented.", "Black-box detectors."],
  ["ERM deep-dive calendar conflict", "ERM", "avoids scheduling deep-dives on close/blackout weeks.", "Attendance up.", "Bad timing."],
  ["Supplier code ICFR-relevant align", "Control environment", "aligns supplier codes with integrity expectations for ICFR vendors.", "Critical vendors re-attested.", "Suppliers outside code."],
  ["Impact likelihood monetary anchors", "Risk assessment", "anchors impact/likelihood scales to money and reputation yearly.", "£5m = high firm-wide.", "Scale Babel."],
  ["Automated control disable paging", "Control activities", "pages owners when automated controls fail or are disabled.", "Disable paged in 2 minutes; restored.", "Silent disable weeks."],
  ["Population completeness pre-OE", "Information and communication", "tests population completeness before OE on that population.", "Completeness fail fixed pre-OE.", "OE on incomplete."],
  ["Board appetite simulation choices", "ERM", "simulates board choices to calibrate appetite words to numbers.", "Cyber appetite tightened.", "Words untested."],
  ["Tone consequence evidence library", "Control environment", "libraries consequence management evidence for tone assertions.", "Two dismissals evidenced.", "Code PDF only."],
  ["Override journal analytics model", "Control environment", "models risk scores on manual journals for override detection.", "Late credits investigated.", "No journal model."],
  ["Go-live temporary control inventory", "Control activities", "inventories temporary controls post go-live with exit dates.", "Two temps still live at day 120; escalated.", "Temps forgotten."],
  ["Fraud scenario library versioning", "Risk assessment", "versions the fraud scenario library with change logs.", "v6 adds deepfake; dated.", "Unversioned list."],
  ["RCM acquisition day-1 build", "Control activities", "builds RCMs for acquired entities within a dated SLA.", "SLA 90 days; met for two entities.", "Acquisition out of scope forever."],
  ["IPE access review quarterly", "Information and communication", "reviews access to IPE stores quarterly.", "Excess access removed.", "Open IPE folders."],
  ["Disclosure KPI evidence map", "Information and communication", "maps each disclosed KPI to evidence and owner.", "Map complete for ARA KPIs.", "Orphan KPIs."],
  ["Hotline vendor AC direct report", "Information and communication", "ensures hotline vendor can report directly to AC chair.", "Direct report used twice.", "Local manager filter."],
  ["Aggregation qualitative factors guide", "Monitoring", "guides qualitative aggregation factors with examples.", "Pervasiveness example applied.", "Qualitative chaos."],
  ["Separate evaluation calendar risk-based", "Monitoring", "calendars separate evaluations (IA) risk-based not rotational only.", "High residual brought forward.", "Pure rotation."],
  ["Remediation verification independence", "Monitoring", "keeps remediation verification independent of the fixer.", "Verifier ≠ fixer; OK.", "Self-verify."],
  ["Board deficiency ageing chart", "Monitoring", "charts deficiency ageing for the board with SLA breaches highlighted.", "Overdue highs red; cleared.", "Ageing invisible."],
  ["Present and functioning evidence index", "Internal control framework", "indexes present-and-functioning evidence per principle.", "Principle 8 evidenced fully.", "Poster green."],
  ["Component interdependence workshop", "Internal control framework", "workshops component interdependencies before annual rating.", "Workshop changes two ratings.", "Isolated ratings."],
  ["ICFR scope revisit trigger list", "Internal control framework", "lists triggers that force ICFR scope revisit mid-year.", "Threshold cross adds entity.", "Annual-only scope."],
  ["Management override analytics dashboard", "Control environment", "dashboards override analytics for controllers and AC.", "Dashboard used in AC.", "Analytics unused."],
  ["ERM opportunity upside register", "ERM", "registers upsides with risk mitigations not only threats.", "Opportunity pursued under appetite.", "Threats-only ERM."],
  ["Risk appetite soft hard card", "ERM", "cards soft versus hard appetite breaches with escalations.", "Card used correctly twice.", "Confusion soft/hard."],
  ["Performance KPI risk KRI pairing", "ERM", "pairs each major performance KPI with a risk KRI on the same page.", "Bookings with returns rate paired.", "Separate worlds."],
  ["ERM revision after M&A SLA", "ERM", "SLAs ERM revision after M&A close.", "90-day SLA met.", "ERM stale post-deal."],
  ["Cross-unit risk information latency", "ERM", "measures latency of risk information flowing across units.", "Latency 10 days; cut to 3.", "Stale cross-unit risk."],
  ["Culture leading indicator set", "ERM", "sets leading culture indicators beyond annual surveys.", "Exception ageing leading; acted.", "Survey-only."],
  ["Control budget residual ranked", "ERM", "ranks control investments by residual risk reduction.", "Ranking funds cyber first.", "Inertia budget."],
  ["ELC code attestation chase SLA", "Control environment", "SLAs chasing non-attestors on code of conduct.", "Chase complete pre-assertion.", "Non-attestors ignored."],
  ["Outsourced payroll CUC OE", "Control activities", "OE-tests user complementary controls for outsourced payroll.", "Access review OE OK.", "SOC alone."],
  ["Material weakness indicator checklist live", "Monitoring", "lives MW indicator checklist in deficiency evaluations.", "Checklist triggers MW memo.", "Isolated view."],
  ["SD remediation plan AC clock", "Monitoring", "clocks SD remediation plans presented to AC.", "Plan in 60 days; OK.", "Plan-less SD."],
  ["Root cause training versus design split", "Monitoring", "splits remediations into training versus design fixes by taxonomy.", "Design root → system fix not training.", "Training for design bugs."],
  ["UK CGC monitoring declaration pack", "Internal control framework", "packs monitoring declaration evidence mapped to COSO.", "Pack supports Provision 29.", "Bare declaration."],
  ["Risk score to audit hours formula", "Risk assessment", "formulas how residual scores convert to audit/assurance hours.", "Formula redistributes hours.", "Heat unused."],
  ["Standard control library v-next", "Control activities", "versions standard control library with deviation tracking.", "v6 published; deviations listed.", "Uncontrolled variants."],
  ["Exception ageing to process owner page", "Information and communication", "pages process owners on aged recon exceptions.", "Page at day 10; cleared.", "Ageing quiet."],
  ["Board skills cyber gap close", "Control environment", "closes board cyber skills gaps with hiring or advisers.", "Adviser retained.", "Gap open."],
  ["ERM review trigger catalogue", "ERM", "catalogues ERM review triggers with owners.", "Regulatory trigger fired; review done.", "Ad-hoc reviews."],
  ["Risk flash distribution ack", "ERM", "requires ack on risk flashes to EXCO distribution.", "Ack rate 100% this quarter.", "Dead list."],
  ["Culture KRI breach playbook", "ERM", "playbooks responses to culture KRI breaches.", "Playbook used after speak-up dip.", "No playbook."],
  ["Resource allocation residual first", "ERM", "allocates scarce control resources to highest residual first.", "Allocation meeting uses residual rank.", "Politics first."],
  ["Entity-level control OE sampling guide", "Control environment", "guides OE sampling for ELCs annually.", "Guide applied; OK.", "Design-only ELC."],
  ["Vendor SOC bridge letter SLA", "Monitoring", "SLAs obtaining SOC bridge letters before reliance.", "Letter late; extra testing.", "Rely without bridge."],
  ["Control owner quarterly attestation", "Control environment", "requires quarterly key control operation attestations with exception disclosure.", "100% returned; exceptions logged.", "Annual only."],
  ["ERM capital stress link certificate", "ERM", "certificates that top risks appear in capital stress scenarios.", "Certificate adds one scenario.", "Disconnected ICAAP."],
  ["Missing data escalate without blame", "Information and communication", "lets operators escalate missing data without blame culture.", "Escalation used; source fixed.", "Silent skip culture."],
  ["Monitoring analytics false-positive KPI", "Monitoring", "KPIs false-positive rates for monitoring analytics.", "KPI drives tuning.", "Untuned floods."],
  ["ERM outcome feedback loop annual", "ERM", "feeds outcomes into appetite/risk score calibration annually.", "Loop tightens product stage gates.", "No feedback."],
  ["Anti-fraud investigation KPI board", "Control environment", "boards investigation timeliness KPIs for anti-fraud.", "Median 32 days; target 30.", "Investigations opaque."],
  ["Risk assessment data quality gate", "Risk assessment", "gates final risk scores on minimum data quality.", "Gate holds cyber score.", "Score on junk data."],
  ["Spreadsheet IPE migration plan", "Control activities", "plans migration of high-risk IPEs to system reports.", "Three sheets migrated.", "Eternal Excel."],
  ["Board challenge log effectiveness", "Monitoring", "logs whether board challenges close with evidence.", "Log shows 4/5 closed.", "Open challenges."],
  ["Third-party ICFR right-to-audit use", "Control activities", "plans use of audit rights on ICFR-critical vendors.", "Right used once; access findings.", "Rights unused."],
  ["Fraud risk pressure indicator feed", "Risk assessment", "feeds pressure indicators (targets, SPIFF) into fraud risk.", "Feed triggers reassessment.", "Pressure blind."],
  ["Monitoring deficiency customer tag", "Monitoring", "tags monitoring findings with customer impact.", "Priority shifts to customer-impacting.", "Internal-only view."],
  ["COSO principle owner RACI", "Internal control framework", "assigns RACI owners per COSO principle for assessment.", "Owners deliver on time.", "One hero assessment."],
  ["Outsourced process responsibility matrix", "Control activities", "matrices management versus vendor control responsibilities.", "Matrix clarifies payroll CUCs.", "Vendor does all myth."],
  ["Material weakness restatement link", "Monitoring", "links restatement discussions automatically to MW evaluation workflow.", "Link opens MW memo same day.", "Restatement siloed."],
  ["Significant deficiency tone guide", "Monitoring", "guides tone/language when communicating SDs to AC.", "Guide used; clear communication.", "Softened SD."],
  ["Monitoring taxonomy to investment", "Monitoring", "routes taxonomy themes to investment cases.", "Training theme → academy case.", "Themes unused."],
  ["Framework present-functioning test pack", "Internal control framework", "packs tests for present and functioning per relevant principle.", "Pack complete for annual assessment.", "Checkbox only."],
  ["Information component investment case", "Internal control framework", "cases investment when information component weakness undermines others.", "Case funds data quality.", "Ignore contagion."],
  ["ICFR scope M&A day-1 checklist", "Internal control framework", "checklists day-1 ICFR scope decisions for M&A.", "Checklist brings two entities in.", "M&A out of mind."],
  ["Journal analytics AC demo", "Control environment", "demos journal analytics to AC annually for override oversight.", "Demo drives one investigation.", "Analytics unseen."],
  ["ERM strategy objective workshop minutes", "ERM", "minutes strategy-risk workshops with decisions.", "Minutes show two initiatives re-scoped.", "Workshop without minutes."],
  ["Portfolio view concentration metric", "ERM", "metrics concentration of residual risk across units.", "Three ambers = group red; funded.", "Unit silo view."],
  ["Appetite versus tolerance training", "ERM", "trains leaders on appetite versus tolerance differences.", "Training cuts synonym misuse.", "Words conflated."],
  ["Integrated MI adoption metric", "ERM", "metrics adoption of integrated performance-risk MI.", "Adoption 80% EXCO packs.", "Template unused."],
  ["ERM trigger M&A auto", "ERM", "auto-creates ERM refresh tasks on M&A close events.", "Auto-task met SLA.", "Manual forget."],
  ["Flash risk to scenario criteria", "ERM", "criteria promote flashes to formal scenarios.", "AI flash promoted after 2 quarters.", "Flash forever."],
  ["Culture indicator to loss lag study", "ERM", "studies lag from culture indicators to losses.", "Study informs leading set.", "No lag study."],
  ["Budget residual reduction dashboard", "ERM", "dashboards residual reduction achieved per budget pound.", "Dashboard reshapes next budget.", "Spend without outcome."],
  ["ELC board oversight evidence", "Control environment", "evidences board oversight ELCs with minutes and packs.", "Evidence supports assertion.", "Oversight assumed."],
  ["SOC report user consideration map", "Control activities", "maps each SOC user consideration to a CUC.", "Map complete; one gap filled.", "SOC shelfware."],
  ["MW indicator checklist forced", "Monitoring", "forces MW indicator checklist completion in the tool.", "Forced checklist opens MW path.", "Optional checklist."],
  ["SD auditor notify evidence", "Monitoring", "evidences timely SD notification to external auditor.", "Notify day 5; evidence filed.", "Late notify."],
  ["Root-cause systemic investment", "Monitoring", "invests in systemic fixes when taxonomy shows repeats.", "Repeat design fails → platform fix.", "Local patches."],
  ["Provision 29 dry-run external", "Internal control framework", "dry-runs Provision 29 evidence with external reviewer.", "Dry-run findings closed pre-year-end.", "First time live."],
  ["Assurance hours formula published", "Risk assessment", "publishes residual-to-hours formula to stakeholders.", "Formula accepted; debates down.", "Opaque hours."],
  ["Control standardisation benefit case", "Control activities", "cases benefits of standardising key controls across entities.", "Case funds standard OTC controls.", "Eternal bespoke."],
  ["IPE exception ageing page", "Information and communication", "pages owners of aged IPE exceptions.", "Page clears backlog.", "Backlog silent."],
  ["Board cyber adviser retained", "Control environment", "retains cyber adviser when skills matrix gap persists.", "Adviser at two AC sessions.", "Gap open."],
  ["Opportunity mitigations tracked", "ERM", "tracks mitigations attached to pursued opportunities.", "Mitigations 3/3 closed.", "Opportunity without mitigations."],
  ["Evidence retention legal hold", "Control activities", "applies legal holds to control evidence when needed.", "Hold applied; evidence preserved.", "Hold missed."],
  ["Reliance reperformance minimum", "Monitoring", "sets minimum reperformance by risk for reliance.", "High risk 25%; applied.", "Blind rely."],
  ["Assertion index auditor ready", "Internal control framework", "keeps assertion index auditor-ready continuously.", "Walkthrough day-1 ready.", "Scramble index."],
  ["Trigger-to-reassess clock dashboard", "Risk assessment", "dashboards clocks from trigger to reassessment complete.", "Median 16 days; SLA 30.", "No clock."],
  ["CCM ownership weekend cover", "Monitoring", "covers CCM alert ownership on weekends for critical rules.", "Weekend cover catches payment fraud attempt.", "Weekday-only cover."],
  ["Policy to principle crosswalk gaps", "Internal control framework", "closes gaps in policy-to-principle crosswalks.", "Gaps closed pre-assessment.", "Open gaps."],
  ["SSC control scorecard trend", "Information and communication", "trends shared-service control scorecards for entity CFOs.", "Trend drives SLA fix.", "Point scorecards."],
  ["Crisis catalogue board approve", "Control activities", "boards approval of crisis compensating control catalogue.", "Catalogue approved; used once.", "Unapproved crisis controls."],
  ["Bridge letter week coverage test", "Monitoring", "tests week-by-week coverage of SOC bridge letters.", "Missing week tested via CUC.", "Assume coverage."],
  ["Attestation exception workflow bot", "Control environment", "bots attestation exceptions into deficiency workflow.", "Bot catches three; OK.", "Manual loss."],
  ["Stress scenario ERM recon tool", "ERM", "tools annual recon of stress scenarios to ERM risks.", "Tool adds missing scenario.", "Manual recon miss."],
  ["Skip escalate blameless KPI", "Information and communication", "KPIs blameless escalations of control skips.", "KPI up; skips reported.", "Fear suppresses skips."],
  ["Rule change dual approve", "Monitoring", "dual-approves monitoring rule changes.", "Dual approve cuts bad edits.", "Solo edits."],
  ["Outcome versus score calibration", "ERM", "calibrates risk scores to realised outcomes annually.", "Calibration shifts two scores.", "Never calibrate."],
  ["Anti-fraud suite annual OE", "Control environment", "OE-tests anti-fraud suite annually integrated.", "Investigation KPI reviewed.", "Piecemeal."],
  ["Confidence flag blocks precision", "Risk assessment", "blocks presenting low-confidence scores as precise.", "Flag forces range disclosure.", "Fake precision."],
  ["IPE inventory certify fail escalate", "Control activities", "escalates failed IPE inventory certifications.", "Fail finds shadow sheet; controlled.", "Fail ignored."],
  ["Challenge action closure dashboard", "Monitoring", "dashboards closure of actions from director challenges.", "Dashboard clears backlog.", "Open forever."],
  ["Vendor day ICFR actions track", "Control activities", "tracks actions from ICFR vendor days to closure.", "Actions 5/5 closed.", "Vendor day theatre."],
  ["Incentive change auto fraud task", "Risk assessment", "auto-creates fraud reassessment tasks on incentive changes.", "Auto-task completed.", "Manual miss."],
  ["Customer impact remediation SLA", "Monitoring", "SLAs faster remediation for customer-impacting deficiencies.", "SLA met on two items.", "Same SLA all."],
  ["AI risk taxonomy ERM v-next", "ERM", "versions AI/digital risk taxonomy with product changes.", "v5 adds prompt injection.", "Stale AI taxonomy."],
  ["Crisis cadence ack required", "Information and communication", "requires ack on crisis cadence messages for close teams.", "Ack 100% in outage.", "Unread crisis notes."],
  ["Coverage heat map quarterly", "Monitoring", "updates monitoring coverage heat maps quarterly.", "Update schedules IA.", "Annual stale map."],
  ["Control owner 30-day COSO brief", "Control environment", "briefs new owners within 30 days with evidence.", "Brief records filed.", "No brief."],
  ["Inherent scale annual recalibrate", "Risk assessment", "recalibrates inherent scales annually with examples.", "Recalibration published.", "Drifted scales."],
  ["Design fail stop OE", "Control activities", "stops OE when design effectiveness fails.", "Stop saves waste.", "OE anyway."],
  ["Mini-case library board education", "Control environment", "libraries mini-cases for ongoing board ICFR education.", "Library used twice.", "One-off lecture."],
  ["Breach simulation soft hard", "ERM", "simulates both soft and hard appetite breaches.", "Paths clarified.", "Hard-only drill."],
  ["Reliance dialogue minutes", "Monitoring", "minutes external auditor reliance dialogues.", "Minutes guide testing.", "Undocumented reliance."],
  ["Pulse survey override pressure", "Control environment", "pulses override pressure monthly in high-risk units.", "Pulse spikes; intervene.", "Annual pulse."],
  ["Emerging tech lens checklist", "Risk assessment", "checklists emerging-tech risks in product assessments.", "Checklist adds model opacity.", "Legacy checklist."],
  ["Key report version bind", "Information and communication", "binds versions of key reports to control executions.", "Version mismatch caught.", "Wrong report version."],
  ["Severity examples annual refresh", "Monitoring", "refreshes severity worked examples annually.", "Refresh reduces debate.", "Stale examples."],
  ["Component owner backlog", "Internal control framework", "tracks component owner assessment backlogs.", "Backlog clear pre-deadline.", "Last-minute rush."],
  ["Subprocessor inventory ICFR", "Control activities", "inventories subprocessors for ICFR-critical vendors.", "Inventory complete; one high.", "Unknown subs."],
  ["Detection model tuning log", "Monitoring", "logs tuning of detection models with before/after precision.", "Log shows gain.", "Untuned."],
  ["Deep-dive versus close conflict", "ERM", "detects calendar conflicts between deep-dives and close.", "Conflict auto-moved.", "Conflict ignored."],
  ["Supplier integrity re-attest", "Control environment", "re-attests critical suppliers to integrity codes periodically.", "Re-attest 100%.", "One-time attest."],
  ["Scale anchor peer review", "Risk assessment", "peer-reviews monetary anchors for impact scales.", "Peer review adjusts anchors.", "Unreviewed anchors."],
  ["Control disable page test", "Control activities", "tests paging when controls are disabled in lower environments then prod.", "Test catches config gap.", "Untested page."],
  ["Completeness test mandatory pre-OE", "Information and communication", "makes completeness tests mandatory before OE.", "Mandatory gate works.", "Optional completeness."],
  ["Appetite sim results to metrics", "ERM", "feeds appetite simulation results into metric changes.", "Metrics updated post-sim.", "Sim theatre."],
  ["Consequence library update", "Control environment", "updates consequence evidence library annually.", "Update adds two cases.", "Stale library."],
  ["Journal model false positive tune", "Control environment", "tunes journal analytics false positives quarterly.", "Tune restores investigator trust.", "Flood ignored."],
  ["Temporary control exit evidence", "Control activities", "requires evidence to exit temporary controls.", "Exit evidenced; OK.", "Exit by date only."],
  ["Fraud library change log", "Risk assessment", "logs changes to fraud scenario library with owners.", "Log complete.", "Silent edits."],
  ["Acquired RCM SLA dashboard", "Control activities", "dashboards SLA for building acquired-entity RCMs.", "SLA green.", "SLA invisible."],
  ["IPE access certify", "Information and communication", "certifies IPE access reviews quarterly.", "Cert finds excess; removed.", "No cert."],
  ["KPI evidence map freeze", "Information and communication", "freezes KPI evidence maps for reporting periods.", "Freeze prevents silent KPI change.", "Moving KPIs."],
  ["Hotline direct AC test", "Information and communication", "tests hotline direct path to AC chair annually.", "Test call reaches chair office.", "Untested path."],
  ["Aggregation factor calculator", "Monitoring", "calculates monetary aggregation factors in the deficiency tool.", "Calculator used; SD path opened.", "Mental math."],
  ["IA calendar risk refresh", "Monitoring", "refreshes IA calendar when residual risk rankings change mid-year.", "Refresh brings forward treasury.", "Frozen calendar."],
  ["Verifier independence check", "Monitoring", "checks verifier ≠ fixer before remediation close.", "Check blocks self-verify.", "Self-close."],
  ["Ageing chart AC standing", "Monitoring", "makes deficiency ageing a standing AC chart.", "Standing chart clears overdues.", "Ad-hoc ageing."],
  ["Principle evidence pack template", "Internal control framework", "templates present-and-functioning packs per principle.", "Template speeds assessment.", "Ad-hoc packs."],
  ["Interdependence rating adjust", "Internal control framework", "adjusts ratings after interdependence workshops.", "Two adjustments logged.", "Workshop without effect."],
  ["Scope trigger auto task", "Internal control framework", "auto-tasks scope revisits on threshold triggers.", "Auto-task adds entity.", "Manual miss."],
  ["Override dashboard AC pack", "Control environment", "includes override analytics dashboard in AC packs periodically.", "Pack item drives question.", "Never shown."],
  ["Upside register mitigations OE", "ERM", "OE-tests whether opportunity mitigations operate.", "Mitigation fail; opportunity paused.", "Mitigations paper."],
  ["Soft hard appetite card quiz", "ERM", "quizzes leaders on soft/hard appetite card.", "Quiz scores drive coaching.", "Card unread."],
  ["KPI KRI pair adoption", "ERM", "tracks adoption of KPI-KRI pairing in packs.", "Adoption 75%.", "Pairs unused."],
  ["M&A ERM auto task", "ERM", "auto-tasks ERM refresh on M&A close.", "Task completed day 60.", "Forgot refresh."],
  ["Flash promote criteria tool", "ERM", "tools criteria for promoting flashes to scenarios.", "Tool promotes one flash.", "Subjective promote."],
  ["Culture lag study update", "ERM", "updates culture-to-loss lag studies periodically.", "Update changes leading set.", "Study once."],
  ["Budget ROI residual dashboard", "ERM", "dashboards residual reduction ROI of control spend.", "Dashboard reshapes asks.", "Spend opaque."],
  ["Board oversight ELC sample", "Control environment", "samples board oversight evidence for ELC OE.", "Sample OK.", "Assume oversight."],
  ["CUC map completeness gate", "Control activities", "gates SOC reliance on complete CUC maps.", "Gate blocks incomplete map.", "Rely incomplete."],
  ["MW checklist forced field", "Monitoring", "forces MW checklist fields in deficiency system.", "Forced fields open MW.", "Skippable."],
  ["SD notify evidence attach", "Monitoring", "requires attachment of auditor notify evidence on SDs.", "Attach filed.", "Notify claimed."],
  ["Taxonomy investment bridge", "Monitoring", "bridges taxonomy themes to funded investments.", "Bridge funds platform fix.", "Themes unused."],
  ["Present functioning pack QA", "Internal control framework", "QAs present-and-functioning packs before assessment sign-off.", "QA finds gap; fixed.", "No QA."],
  ["Information investment case template", "Internal control framework", "templates investment cases for information component weakness.", "Template funds data quality.", "Weak cases."],
  ["M&A scope day-1 checklist use", "Internal control framework", "tracks use of M&A day-1 ICFR scope checklist.", "Use 100% this year.", "Checklist shelfware."],
  ["Journal analytics tuning board", "Control environment", "boards journal analytics tuning outcomes periodically.", "Tuning restores trust.", "Untuned forever."],
  ["Strategy workshop decision log", "ERM", "logs decisions from strategy-risk workshops.", "Log shows re-scopes.", "No decisions logged."],
  ["Concentration metric board appetite", "ERM", "sets appetite on residual risk concentration metric.", "Appetite breached; investment.", "No concentration appetite."],
  ["Appetite tolerance training quiz", "ERM", "quizzes appetite vs tolerance after training.", "Quiz pass 90%.", "Training without quiz."],
  ["Integrated pack adoption EXCO", "ERM", "tracks EXCO adoption of integrated packs.", "Adoption 85%.", "Old dual packs."],
  ["Refresh trigger auto from M&A system", "ERM", "autos refresh tasks from M&A system events.", "Auto works.", "Manual bridge."],
  ["Scenario promote criteria published", "ERM", "publishes flash-to-scenario promote criteria.", "Criteria used twice.", "Opaque promote."],
  ["Leading culture set refresh", "ERM", "refreshes leading culture indicator set using lag studies.", "Set updated.", "Stale set."],
  ["Residual ROI rank meeting", "ERM", "holds residual-ROI ranking meetings for control budgets.", "Meeting funds top two.", "Politics meeting."],
  ["ELC OE sample documented", "Control environment", "documents ELC OE samples fully.", "Docs support assertion.", "Undocumented sample."],
  ["SOC reliance gate CUC", "Control activities", "gates SOC reliance on CUC OE evidence.", "Gate holds one vendor.", "Rely without CUC OE."],
  ["MW path from checklist", "Monitoring", "opens MW evaluation path from checklist triggers automatically.", "Auto path used once.", "Manual MW only."],
  ["SD plan AC date force", "Monitoring", "forces AC date for SD remediation plans in workflow.", "Date forced; plan on time.", "Dateless plans."],
  ["Systemic fix funding bridge", "Monitoring", "bridges systemic taxonomy themes to funding cases.", "Case funded.", "Unfunded themes."],
  ["Provision 29 pack version", "Internal control framework", "versions Provision 29 evidence packs.", "v3 used for declaration.", "Unversioned pack."],
  ["Hours formula stakeholder publish", "Risk assessment", "publishes residual-hours formula to auditees.", "Publish reduces pushback.", "Secret formula."],
  ["Standardisation case OTC", "Control activities", "cases standardising OTC controls across regions.", "Case approved; rollout.", "Bespoke forever."],
  ["IPE age page escalate", "Information and communication", "escalates aged IPE exceptions to ICFR lead.", "Escalate clears.", "Age quiet."],
  ["Cyber adviser AC attendance", "Control environment", "tracks cyber adviser attendance at relevant AC sessions.", "Attendance 2/2 planned.", "Adviser unused."],
  ["Opportunity mitigation OE", "ERM", "OE-tests opportunity mitigations before scale-up.", "Fail pauses scale.", "Paper mitigations."],
  ["Soft hard quiz annual", "ERM", "annual quizzes on soft/hard appetite.", "Pass rate 92%.", "No quiz."],
  ["Pair adoption pack review", "ERM", "reviews packs for KPI-KRI pair adoption.", "Review lifts adoption.", "Pairs rare."],
  ["ERM task M&A close bot", "ERM", "bots ERM tasks on M&A close events.", "Bot creates task.", "Forgot."],
  ["Promote criteria tool use", "ERM", "tracks use of promote-criteria tool for flashes.", "Use logged twice.", "Tool unused."],
  ["Lag study informs KRIs", "ERM", "ensures lag studies change KRI sets.", "KRI set changed.", "Study shelfware."],
  ["ROI dashboard next budget", "ERM", "uses residual ROI dashboard in next budget cycle.", "Dashboard used; reshaped.", "Ignored dashboard."],
  ["Oversight sample AC minutes", "Control environment", "samples AC minutes as ELC oversight evidence.", "Sample supports OE.", "Minutes unused."],
  ["CUC completeness gate SOC", "Control activities", "gates SOC reliance on CUC map completeness score.", "Score fail blocks reliance.", "Incomplete rely."],
  ["Checklist opens MW workflow", "Monitoring", "opens MW workflow from checklist automatically.", "Opened once correctly.", "Manual only."],
  ["SD plan date validation", "Monitoring", "validates SD plan dates against policy maxima.", "Validation blocks 120-day plan.", "Long plans."],
  ["Theme to case converter", "Monitoring", "converts repeated themes into investment case drafts.", "Converter used; case funded.", "Manual cases."],
  ["Pack QA before sign-off", "Internal control framework", "QAs assessment packs before CFO/CEO sign-off.", "QA gap fixed.", "Sign bare."],
  ["Info weakness case template use", "Internal control framework", "tracks use of information-weakness investment templates.", "Use funds data quality.", "Weak asks."],
  ["Day-1 checklist compliance", "Internal control framework", "metrics compliance with M&A day-1 ICFR checklist.", "100% compliance.", "Non-use."],
  ["Tuning outcomes AC note", "Control environment", "notes journal analytics tuning outcomes to AC periodically.", "Note restores confidence.", "Silent tuning."],
  ["Workshop decisions tracked", "ERM", "tracks strategy-risk workshop decisions to closure.", "Decisions closed.", "Open decisions."],
  ["Concentration appetite metric", "ERM", "operates concentration appetite metric with breach path.", "Breach funds diversification.", "No metric."],
  ["Tolerance quiz after training", "ERM", "quizzes tolerance concepts after training.", "Pass 88%.", "No quiz."],
  ["EXCO pack adoption metric", "ERM", "metrics EXCO integrated pack adoption.", "85% adoption.", "Dual packs."],
  ["M&A system event bridge", "ERM", "bridges M&A system events to ERM tasking reliably.", "Bridge SLA met.", "Broken bridge."],
  ["Criteria publish flash promote", "ERM", "publishes and applies flash promote criteria.", "Applied twice.", "Opaque."],
  ["KRI set from lag study", "ERM", "updates KRI sets from lag study results.", "Set updated.", "Stale KRIs."],
  ["Budget meeting uses ROI", "ERM", "requires residual ROI rank in control budget meetings.", "Rank used; funded top.", "Politics."],
  ["ELC sample workpapers", "Control environment", "keeps workpapers for ELC OE samples.", "Workpapers support assertion.", "No papers."],
  ["Reliance blocked incomplete CUC", "Control activities", "blocks reliance when CUC map incomplete.", "Block works.", "Rely anyway."],
  ["MW auto from indicators", "Monitoring", "autos MW evaluation from indicator triggers.", "Auto used once.", "Manual MW."],
  ["Plan date max enforced", "Monitoring", "enforces maximum SD plan dates in workflow.", "Enforce blocks long plan.", "Long plans."],
  ["Theme converter funded", "Monitoring", "funds cases from theme converter outputs.", "Case funded.", "Converter unused."],
  ["Sign-off after QA only", "Internal control framework", "allows assertion sign-off only after pack QA pass.", "Gate works.", "Sign without QA."],
  ["Template use tracked", "Internal control framework", "tracks information investment template use.", "Tracked; funded.", "Unused."],
  ["Checklist compliance metric", "Internal control framework", "metrics M&A checklist compliance.", "100%.", "Unknown."],
  ["AC note on tuning", "Control environment", "includes tuning notes in AC materials when material.", "Note included.", "Silent."],
  ["Decision closure rate", "ERM", "tracks closure rate of workshop decisions.", "90% closed.", "Open."],
  ["Breach funds diversification", "ERM", "links concentration breaches to diversification funding.", "Funding approved.", "Breach no money."],
  ["Quiz pass threshold", "ERM", "sets pass thresholds on appetite/tolerance quizzes.", "Threshold 80%; met.", "No threshold."],
  ["Adoption target EXCO", "ERM", "sets adoption targets for integrated packs.", "Target 90%; at 85%.", "No target."],
  ["Event bridge SLA", "ERM", "SLAs M&A-to-ERM event bridge.", "SLA met.", "No SLA."],
  ["Promote apply log", "ERM", "logs applications of promote criteria.", "Log complete.", "No log."],
  ["Study changes KRIs", "ERM", "evidences lag studies changing KRI sets.", "Evidence filed.", "No change."],
  ["Rank required agenda", "ERM", "requires residual ROI rank as standing budget agenda item.", "Standing item used.", "Optional."],
  ["Workpapers ELC OE", "Control environment", "requires workpapers for ELC OE.", "Required; filed.", "None."],
  ["Incomplete CUC block", "Control activities", "blocks SOC reliance on incomplete CUC scores.", "Block fired.", "Bypass."],
  ["Indicator MW auto", "Monitoring", "autos MW from indicator checklist.", "Auto OK.", "Off."],
  ["Max plan date", "Monitoring", "enforces max SD remediation plan date.", "Enforce OK.", "Off."],
  ["Converter to funding", "Monitoring", "routes converter outputs to funding workflow.", "Routed; funded.", "Dead end."],
  ["QA gate sign-off", "Internal control framework", "gates sign-off on QA pass.", "Gate OK.", "Bypass."],
  ["Template funding link", "Internal control framework", "links templates to funding workflow.", "Link used.", "Broken."],
  ["Compliance metric board", "Internal control framework", "boards M&A checklist compliance metric.", "Board sees 100%.", "Hidden."],
  ["Tuning materiality AC", "Control environment", "defines when tuning outcomes are AC-material.", "Definition used once.", "Undefined."],
  ["Workshop closure KPI", "ERM", "KPIs workshop decision closure.", "KPI 90%.", "No KPI."],
  ["Diversification funding path", "ERM", "paths concentration breaches to funding decisions.", "Path used.", "No path."],
  ["Quiz threshold enforce", "ERM", "enforces quiz pass thresholds for role access to risk packs.", "Enforce coaches fails.", "No enforce."],
  ["Adoption target track", "ERM", "tracks integrated pack adoption versus target.", "85% vs 90%.", "No track."],
  ["Bridge SLA report", "ERM", "reports M&A-ERM bridge SLA to CRO.", "Report green.", "No report."],
  ["Promote log audit", "ERM", "audits promote-criteria application logs.", "Audit clean.", "No audit."],
  ["KRI change evidence", "ERM", "evidences KRI set changes from studies.", "Evidence OK.", "None."],
  ["Agenda rank enforce", "ERM", "enforces residual rank on budget agendas.", "Enforce works.", "Skipped."],
  ["ELC papers required", "Control environment", "requires ELC OE papers in assertion support.", "Required met.", "Missing."],
  ["CUC score gate", "Control activities", "gates reliance on CUC completeness score ≥ threshold.", "Gate holds.", "No gate."],
  ["MW auto on", "Monitoring", "keeps MW auto-path enabled in tool.", "Enabled; used.", "Disabled."],
  ["Plan date max on", "Monitoring", "keeps max plan date validation on.", "On; blocks.", "Off."],
  ["Funding workflow link", "Monitoring", "links theme converter to funding workflow.", "Link live.", "Dead."],
  ["Sign-off QA on", "Internal control framework", "keeps QA gate on for sign-off.", "On.", "Off."],
  ["Funding link template", "Internal control framework", "keeps template-to-funding link live.", "Live.", "Broken."],
  ["Compliance board item", "Internal control framework", "keeps checklist compliance as board item when M&A active.", "Item shown.", "Hidden."],
  ["Tuning AC rule", "Control environment", "rules when tuning is AC-notable.", "Rule used.", "None."],
  ["Closure KPI CRO", "ERM", "reports workshop closure KPI to CRO.", "Reported.", "Not."],
  ["Funding path live", "ERM", "keeps diversification funding path live.", "Live.", "Dead."],
  ["Threshold role gate", "ERM", "gates risk pack edit roles on quiz pass.", "Gate coaches.", "Open."],
  ["Adoption track QBR", "ERM", "tracks adoption in QBR.", "Tracked.", "Not."],
  ["SLA CRO report", "ERM", "reports bridge SLA to CRO monthly.", "Reported.", "Not."],
  ["Log audit annual", "ERM", "audits promote logs annually.", "Audited.", "Not."],
  ["Evidence KRI change", "ERM", "files evidence when KRIs change from studies.", "Filed.", "Not."],
  ["Rank agenda on", "ERM", "keeps rank as mandatory agenda.", "On.", "Off."],
]);
