import { expand } from "./wave3-shared.mjs";

/** Wave-3 CRMA drafts — unique vs waves 1–2. */
export const CRMA_WAVE3 = expand([
  ["Appetite metric source recon quarterly", "Assurance", "recons board appetite metrics to source systems each quarter.", "Two fails removed until fixed.", "Narrative-only assurance."],
  ["ERM maturity benefit evidence", "Risk management", "evidences benefits realised from ERM maturity roadmap investments.", "Data programme lifts maturity 0.3 with evidence.", "Maturity score vanity."],
  ["Culture triangulation protocol", "Governance", "protocols triangulation of survey, outcomes, and observation for culture.", "Protocol finds survey/outcome clash.", "Survey-only."],
  ["Board pack assumption cite control", "Reporting", "requires cited versioned assumptions on stress pages.", "Uncited page blocked.", "Silent assumption drift."],
  ["RACI interview assurance method", "Risk management", "assures RACI via interviews not documents alone.", "Owners unaware; finding.", "Spreadsheet RACI."],
  ["Emerging disposition audit trail", "Risk management", "audits disposition trails on emerging risks.", "Six without disposition; finding.", "Endless list."],
  ["Scenario challenge evidence file", "Risk management", "files first-line challenge evidence on scenario losses.", "Challenge cuts £7m; filed.", "Facilitator numbers."],
  ["Acceptance expiry sample test", "Assurance", "samples acceptances for unexpired approvals.", "20% expired; reopened.", "Assume current."],
  ["Target residual milestone assure", "Risk management", "assures milestones from residual to target risk.", "Slip escalated.", "Fantasy dates."],
  ["Effectiveness evidence standard", "Control", "standards evidence for effectiveness ratings in ERM.", "Unevidenced greens downgraded.", "Self-green."],
  ["Key control change log test", "Control", "tests change logs on key control inventories after change events.", "Static through launch; finding.", "No log."],
  ["RMM ERM language recon", "Assurance", "recons RMM and ERM risk language annually.", "Fraud language aligned.", "Two languages."],
  ["Assurance collision monthly report", "Assurance", "reports assurance calendar collisions monthly.", "Collision avoided.", "Field surprise."],
  ["Regulatory inventory completeness", "Governance", "tests regulatory obligation inventory completeness.", "Two missing; risk raised.", "Assume complete."],
  ["Heat-to-hours recon assure", "Assurance", "recons heat colours to assurance hours.", "Under-hours redistributed.", "Heat unused."],
  ["Coverage legend conformance", "Reporting", "assures coverage map legends match work done.", "Three greens reclassed.", "Misleading greens."],
  ["Board KRI source sample", "Assurance", "samples board KRIs to source each quarter.", "Spreadsheet break fixed.", "Trust KRIs."],
  ["ToR practice divergence close", "Governance", "closes ToR-versus-practice divergences with owners.", "Cadence fixed.", "Open gaps."],
  ["Model inventory sample assure", "Assurance", "samples model inventory completeness in risk assurance.", "Shadow models onboarded.", "Attest only."],
  ["Reliance reperformance policy", "Assurance", "policies minimum reperformance % by risk for reliance.", "High 25%; applied.", "Blind rely."],
  ["Event root-cause theme quarterly", "Engagements", "themes root causes across risk events quarterly.", "Change-control theme funded.", "Case-by-case only."],
  ["Breach appetite rewrite link", "Assurance", "links repeated breaches to appetite rewrite consideration.", "Rewrite proposed after three.", "Static appetite."],
  ["Aggregation principle report test", "Assurance", "tests aggregation principles on a critical risk report.", "Manual plugs finding.", "Poster principles."],
  ["Product outcome gate assure", "Engagements", "assures outcome testing at product gates.", "Gate fail delays launch.", "Post-complaint only."],
  ["CFP monetisation realism", "Assurance", "tests CFP monetisation realism versus market capacity.", "Assumption cut; buffer up.", "Parachute sales."],
  ["Cascade break system test", "Assurance", "tests cascade breaks into booking systems.", "Paper-only limit found; fixed.", "Paper cascade."],
  ["Tolerance breach harm metrics", "Assurance", "requires customer harm metrics in tolerance breach reports.", "Harm included.", "Uptime only."],
  ["MI survey redesign follow-up", "Reporting", "follows MI surveys with tracked redesigns.", "Score +0.7 after redesign.", "Survey theatre."],
  ["Challenge outcome system", "Governance", "systems whether challenges change decisions.", "35% alter; playbook shared.", "Memo counts."],
  ["Acceptance issue taxonomy train", "Risk management", "trains taxonomy boundary acceptance versus issues.", "Misclass down 50%.", "Boundary blur."],
  ["Map colour calibration", "Assurance", "calibrates assurance map colours across teams.", "Amber aligned.", "Colour Babel."],
  ["CRO private access evidence", "Governance", "evidences CRO private access per charter.", "Two sessions evidenced.", "Rights unused."],
  ["Framework practice sample", "Engagements", "samples decisions against risk framework practice.", "20% fail; thematic.", "Policy = practice."],
  ["Stress use-of-results test", "Assurance", "tests whether stress results change limits/strategy.", "Unused two cycles; finding.", "Stress theatre."],
  ["Insurance residual match", "Risk management", "matches insurance schedules to accepted residuals.", "Sublimit gap; fixed.", "Insurance shopping."],
  ["Taxonomy migration map", "Risk management", "maps old-to-new taxonomy so trends survive.", "Trend preserved.", "History break."],
  ["Issue escalate bot", "Engagements", "bots escalation of aged issues to committees.", "Backlog down.", "Manual forget."],
  ["Champion capacity attest", "Governance", "attests risk champion capacity yearly.", "Under-capacity; +FTE.", "Name only."],
  ["GRC admin access review", "Control", "reviews GRC privileged access quarterly.", "Excess removed.", "Everyone admin."],
  ["Contagion minutes quality", "Risk management", "assesses contagion workshop minutes for actions.", "No owners; finding.", "Workshop fluff."],
  ["Limit method refresh trigger", "Assurance", "triggers limit methodology refresh on book change.", "New product without refresh; finding.", "Stale method."],
  ["Vendor risk activity scope", "Assurance", "scopes vendor-run risk activities into assurance universe.", "Hosting scoped; rights improved.", "Invisible vendor risk."],
  ["Director education log", "Governance", "logs director risk education attendance/gaps.", "AI gap closed.", "Unlogged."],
  ["External internal risk recon", "Reporting", "recons external principal risks to internal residuals.", "One corrected.", "Diverge."],
  ["Monitoring tool ops model", "Assurance", "assures operating model for continuous monitoring tools.", "No night cover; finding.", "Tool without ops."],
  ["Appetite field usability", "Governance", "field-tests appetite usability with first-line.", "Two statements rewritten.", "Board English only."],
  ["Capital risk same-day recon", "Reporting", "recons capital and risk packs same day.", "£70m mismatch fixed.", "Inconsistent packs."],
  ["Horizon ageing force", "Risk management", "ages horizon items and forces disposition.", "Zombies cleared.", "Forever list."],
  ["CSA bias analytics", "Assurance", "analytics CSA optimism versus losses/IA.", "Bias found; calibrate.", "Raw CSA."],
  ["Scope memo checklist", "Engagements", "checklists risk-based scoping memo quality.", "Out-of-scope rationale added.", "Weak scopes."],
  ["Agile DoD risk checkpoint", "Governance", "embeds risk checkpoints in agile DoD for high-risk features.", "Missed checkpoints coached.", "Agile waiver."],
  ["Post-go-live risk retire", "Engagements", "retires/accepts temporary go-live risks with evidence.", "Temps at 9 months; finding.", "Temporary forever."],
  ["Capacity stress anchor", "Assurance", "anchors capacity narratives to stress results.", "Overstated capacity corrected.", "Storytelling."],
  ["Conduct metric freeze", "Assurance", "freezes conduct metric definitions mid-year unless controlled.", "Silent change caught.", "Moving goalposts."],
  ["Committee effectiveness external", "Governance", "uses external input in committee effectiveness reviews.", "Pack shortened.", "Self-praise."],
  ["Geo scenario owners", "Risk management", "assigns operational owners to geo scenario actions.", "Logistics owner assigned.", "Ownerless slides."],
  ["Data ethics joint protocol", "Assurance", "protocols joint model-risk/conduct findings on data ethics.", "Joint fairness finding.", "Gap between teams."],
  ["Incident risk recon control", "Control", "controls recon of incident vs risk event systems.", "Daily recon catches gaps.", "Diverge."],
  ["Strategic EWI path", "Risk management", "paths strategic EWIs to strategy committee.", "Digital EWI reaches strategy; funded.", "Stuck in risk."],
  ["RWA override review", "Assurance", "requires secondary review of RWA overrides.", "Unreviewed found; control added.", "Solo overrides."],
  ["Vendor concentration board metric", "Risk management", "boards vendor concentration metric with appetite.", "Amber; diversify funded.", "Invisible."],
  ["Training behaviour test", "Governance", "tests whether risk training changes breach behaviour.", "No change; redesign.", "Completion vanity."],
  ["Sev-1 dynamic reassess", "Risk management", "forces dynamic reassessment after Sev-1 within SLA.", "72h met.", "Annual only."],
  ["Report tone independence", "Reporting", "checks draft tone for management smoothing.", "CAE restores balance.", "Smoothed issue."],
  ["Cascade system encode test", "Assurance", "tests cascade limits encoded in booking systems.", "Not encoded; P1 fix.", "Paper only."],
  ["Second-line OKR outcomes", "Governance", "aligns second-line OKRs to residual outcomes not activity.", "OKRs rewritten.", "Memo OKRs."],
  ["GRC freeze board pack", "Control", "freezes GRC changes around board pack production.", "Freeze prevents breaks.", "Change mid-pack."],
  ["Stress BAU residual recon", "Risk management", "recons stress views to BAU residuals.", "CRE mismatch reconciled.", "Incoherent."],
  ["Opinion phrase dictionary", "Reporting", "dictionaries allowed assurance opinion phrases.", "Inflation down.", "Invented language."],
  ["Risk data quality KRI", "Assurance", "tracks DQ KRIs feeding board metrics.", "Amber; feeds fixed.", "Bad data silent."],
  ["Challenge memo SLA", "Governance", "SLAs time to issue challenge memos.", "Median 7 of 10 days.", "Months late."],
  ["Residual capital link test", "Assurance", "tests high residuals have capital/liquidity reflections.", "Missing link; finding.", "Silos."],
  ["First-line MI attest", "Risk management", "attests first-line risk MI completeness monthly.", "Missing KRI caught.", "Unowned MI."],
  ["Blackout respect schedule", "Engagements", "respects business blackouts in scheduling with logged exceptions.", "Exception CRO-approved.", "Close-week audits."],
  ["Framework exception register", "Risk management", "registers framework exceptions with expiry.", "Expired closed/renewed.", "Silent permanent."],
  ["Appetite viz comprehension", "Reporting", "tests director comprehension of appetite visualizations.", "Redesign after fail.", "Pretty confusion."],
  ["Coverage gap acceptance", "Assurance", "requires formal acceptance of assurance map gaps.", "Gap accepted; revisit set.", "Unowned gaps."],
  ["Event severity calibrate", "Risk management", "calibrates risk event severity scales enterprise-wide.", "Critical inflation down.", "Everything critical."],
  ["Product opinion SLA", "Governance", "SLAs second-line product opinions at gates.", "Late holds launch; capacity fixed.", "Launch without opinion."],
  ["Risk-finance position recon", "Control", "assures recon between risk engines and finance positions.", "Breaks aged; strengthened.", "Diverge."],
  ["Horizon source list", "Risk management", "lists external horizon sources with owners.", "Noise down.", "Random scan."],
  ["Incentive redesign outcome", "Governance", "tests incentive redesigns against culture/risk outcomes.", "Late reporting −40%.", "Change without test."],
  ["CRMA skills matrix", "Engagements", "matrices CRMA engagement skills versus team.", "Model gap; co-source+transfer.", "Wrong skills."],
  ["Appetite sample to source", "Assurance", "samples appetite numbers to source monthly in volatile periods.", "One break; fixed.", "Quarterly only."],
  ["Maturity roadmap KPI", "Risk management", "KPIs maturity roadmap benefit delivery.", "KPI green with evidence.", "Roadmap theatre."],
  ["Culture outcome pair", "Governance", "pairs culture ratings with outcome metrics always.", "Pair used; nuanced rating.", "Survey alone."],
  ["Assumption version stamp", "Reporting", "stamps assumption versions on every stress page.", "Stamp enforced.", "Unstamped."],
  ["RACI interview sample size", "Risk management", "sets sample sizes for RACI interview assurance.", "Sample finds gaps.", "Tiny sample."],
  ["Disposition force report", "Risk management", "reports undisposed emerging items weekly.", "Force clears list.", "No force."],
  ["Scenario challenge % metric", "Risk management", "metrics % of scenarios with evidenced challenge.", "Metric 90%.", "Unknown."],
  ["Expiry sample expand", "Assurance", "expands acceptance expiry samples when fail rate high.", "Expand finds more.", "Fixed tiny sample."],
  ["Milestone slip escalate", "Risk management", "auto-escalates slipped target-residual milestones.", "Escalate works.", "Slip quiet."],
  ["Rating evidence gate", "Control", "gates effectiveness ratings on evidence presence.", "Gate downgrades.", "No gate."],
  ["Inventory change event link", "Control", "links inventory updates to change events automatically.", "Link catches miss.", "Manual update."],
  ["Language recon workshop", "Assurance", "workshops RMM-ERM language recon.", "Workshop aligns.", "No workshop."],
  ["Collision prevent tool", "Assurance", "tools collision detection on assurance calendars.", "Tool prevents double.", "Manual."],
  ["Obligation inventory test", "Governance", "tests obligation inventories with sampling.", "Sample finds gap.", "Assume."],
  ["Hours recon automate", "Assurance", "automates heat-to-hours recon checks.", "Auto flags under-hours.", "Manual."],
  ["Legend conformance test", "Reporting", "tests legend conformance on maps before board.", "Test reclasses.", "No test."],
  ["KRI recon expand fail", "Assurance", "expands KRI recon sample on fails.", "Expand finds second.", "Stop at one."],
  ["Divergence close KPI", "Governance", "KPIs closure of ToR practice divergences.", "KPI 100% this quarter.", "Open."],
  ["Inventory analytics detect", "Assurance", "uses analytics to detect inventory incompleteness.", "Detect finds shadows.", "Attest only."],
  ["Reperformance by rating", "Assurance", "varies reperformance by residual rating.", "High more reperform.", "Flat %."],
  ["Theme funding bridge", "Engagements", "bridges event themes to funding cases.", "Theme funded.", "Unused themes."],
  ["Rewrite trigger log", "Assurance", "logs breach-driven appetite rewrite triggers.", "Log leads to paper.", "No log."],
  ["Principle test pack", "Assurance", "packs tests for aggregation principles on reports.", "Pack finds plugs.", "No pack."],
  ["Outcome gate evidence", "Engagements", "requires outcome-test evidence at gates.", "Evidence missing; hold.", "Checkbox gate."],
  ["Monetisation capacity test", "Assurance", "tests monetisation capacity assumptions annually.", "Cut assumption.", "Untested."],
  ["System encode cascade", "Assurance", "tests system encoding of cascade limits.", "Fail; fix.", "Paper."],
  ["Harm metric required", "Assurance", "requires harm metrics field on breach reports.", "Field forced.", "Optional."],
  ["Survey action track", "Reporting", "tracks MI survey actions to closure.", "Closed; score up.", "Open."],
  ["Outcome % dashboard", "Governance", "dashboards challenge outcome percentages.", "Dashboard used.", "Unknown."],
  ["Taxonomy train refresh", "Risk management", "refreshes taxonomy boundary training annually.", "Refresh cuts misclass.", "One-time."],
  ["Colour calibrate annual", "Assurance", "calibrates map colours annually.", "Calibrate done.", "Drift."],
  ["Private access confirm", "Governance", "confirms private access occurred as scheduled.", "Confirmed twice.", "Skipped."],
  ["Practice sample expand", "Engagements", "expands framework practice samples when fail high.", "Expand thematic.", "Tiny."],
  ["Use-of-results KPI", "Assurance", "KPIs use-of-results from stress into decisions.", "KPI red; finding.", "No KPI."],
  ["Schedule residual match", "Risk management", "matches insurance schedules to residuals annually.", "Match finds gap.", "Annual miss."],
  ["Migration map required", "Risk management", "requires migration maps on taxonomy changes.", "Map preserves trend.", "No map."],
  ["Bot escalate rules", "Engagements", "rules bots for issue escalation thresholds.", "Rules tuned.", "No bot."],
  ["Capacity attest evidence", "Governance", "evidences champion capacity attestations.", "Evidence shows gap.", "Bare attest."],
  ["Admin review GRC", "Control", "reviews GRC admins quarterly.", "Excess gone.", "Never."],
  ["Minutes action force", "Risk management", "forces actions from contagion minutes.", "Owners assigned.", "No actions."],
  ["Refresh trigger product", "Assurance", "triggers methodology refresh on product add.", "Trigger fires.", "Miss."],
  ["Vendor scope universe", "Assurance", "adds vendor risk activities to universe systematically.", "Added; planned.", "Invisible."],
  ["Education gap close", "Governance", "closes director education gaps with dated briefs.", "Gap closed.", "Open."],
  ["Risk recon annual", "Reporting", "annual recon external/internal risks.", "Corrected one.", "Skip."],
  ["Ops model assure", "Assurance", "assures monitoring tool ops models.", "Night cover added.", "None."],
  ["Field test appetite", "Governance", "field-tests appetite annually with managers.", "Rewrite two lines.", "Never."],
  ["Same-day recon control", "Reporting", "controls same-day capital-risk recon.", "Mismatch caught.", "No control."],
  ["Ageing force weekly", "Risk management", "weekly forces horizon dispositions.", "Clears zombies.", "Monthly weak."],
  ["Bias analytics quarterly", "Assurance", "quarterly CSA bias analytics.", "Bias found.", "Never."],
  ["Memo checklist enforce", "Engagements", "enforces scoping memo checklist.", "Enforce adds rationale.", "Optional."],
  ["DoD sample agile", "Governance", "samples agile DoD risk checkpoints.", "Misses coached.", "No sample."],
  ["Retire evidence required", "Engagements", "requires evidence to retire temp go-live risks.", "Evidence forced.", "Date-only."],
  ["Anchor certificate", "Assurance", "certificates capacity anchors to stress.", "Fail restates.", "None."],
  ["Metric freeze control", "Assurance", "controls conduct metric freezes.", "Silent change blocked.", "Open edit."],
  ["External facilitator", "Governance", "uses external facilitator periodically for effectiveness.", "Used; pack cut.", "Never."],
  ["Owner assign geo", "Risk management", "assigns geo scenario owners mandatorily.", "Assigned.", "Optional."],
  ["Joint ethics protocol", "Assurance", "uses joint ethics finding protocol.", "Used once.", "Shelfware."],
  ["Recon daily incident", "Control", "daily incident-risk recon.", "Catches gaps.", "Weekly weak."],
  ["EWI strategy path", "Risk management", "paths strategic EWIs mandatorily.", "Path used.", "Stuck."],
  ["Override secondary", "Assurance", "secondary-reviews RWA overrides.", "Catch unreviewed.", "Solo."],
  ["Concentration metric live", "Risk management", "lives vendor concentration metric with appetite.", "Amber path.", "Off."],
  ["Behaviour test post-train", "Governance", "tests behaviour post risk training.", "No change; redesign.", "Completion only."],
  ["Dynamic SLA Sev-1", "Risk management", "SLA dynamic reassess after Sev-1.", "Met.", "Miss."],
  ["Tone check pre-issue", "Reporting", "pre-issue tone independence check.", "Restores balance.", "Skip."],
  ["Encode test cascade", "Assurance", "tests cascade encoding pre-board.", "Fail fixed.", "Skip."],
  ["OKR outcome align", "Governance", "aligns OKRs to outcomes annually.", "Rewritten.", "Activity OKRs."],
  ["Freeze GRC pack", "Control", "freezes GRC in pack week.", "Freeze held.", "Broken."],
  ["BAU stress recon", "Risk management", "recons BAU to stress residuals.", "Reconciled.", "Skip."],
  ["Dictionary enforce", "Reporting", "enforces opinion phrase dictionary.", "Inflation down.", "Off."],
  ["DQ KRI board", "Assurance", "boards risk DQ KRI.", "Amber acted.", "Hidden."],
  ["Memo SLA track", "Governance", "tracks challenge memo SLA.", "Median OK.", "No track."],
  ["Capital link test", "Assurance", "tests residual-capital links.", "Finding raised.", "Skip."],
  ["MI attest monthly", "Risk management", "monthly first-line MI attest.", "Catch miss.", "None."],
  ["Blackout exception log", "Engagements", "logs blackout exceptions with approver.", "Logged.", "Silent."],
  ["Exception register framework", "Risk management", "registers framework exceptions.", "Expired handled.", "None."],
  ["Viz test directors", "Reporting", "tests viz comprehension with directors.", "Redesign.", "Assume OK."],
  ["Gap accept formal", "Assurance", "formal gap acceptances on maps.", "Accepted+revisit.", "Informal."],
  ["Severity calibrate", "Risk management", "calibrates event severity annually.", "Done.", "Drift."],
  ["Opinion SLA gate", "Governance", "gates launches on opinion SLA.", "Hold works.", "Bypass."],
  ["Position recon assure", "Control", "assures risk-finance position recon.", "Strengthened.", "Weak."],
  ["Source list horizon", "Risk management", "maintains horizon source list.", "Curated.", "Random."],
  ["Incentive outcome test", "Governance", "tests incentive changes vs outcomes.", "Improved.", "No test."],
  ["Skills matrix CRMA", "Engagements", "maintains CRMA skills matrix.", "Gap filled.", "None."],
  ["Appetite recon monthly", "Assurance", "monthly appetite recon in stress periods.", "Break fixed.", "Quarterly."],
  ["Roadmap benefit KPI", "Risk management", "KPI maturity roadmap benefits.", "Evidenced.", "Vanity."],
  ["Triangulation forced", "Governance", "forces triangulation methods in culture assurance.", "Forced; clash found.", "Survey."],
  ["Cite control pack", "Reporting", "controls citation of assumptions in packs.", "Uncited blocked.", "Open."],
  ["Interview method RACI", "Risk management", "uses interview method for RACI assure.", "Unaware owners found.", "Docs only."],
  ["Trail audit emerging", "Risk management", "audits emerging disposition trails.", "Gaps found.", "Skip."],
  ["Challenge file required", "Risk management", "requires challenge files on scenarios.", "Required; cut loss.", "Optional."],
  ["Expiry sample risk-based", "Assurance", "risk-based samples acceptance expiry.", "Finds expired.", "Tiny."],
  ["Milestone auto escalate", "Risk management", "auto-escalates milestone slips.", "Works.", "Off."],
  ["Evidence gate rating", "Control", "gates ratings on evidence.", "Downgrades.", "Off."],
  ["Change link inventory", "Control", "links inventory to change events.", "Catch miss.", "Manual."],
  ["Workshop language", "Assurance", "runs language recon workshop.", "Aligns.", "Skip."],
  ["Collision tool on", "Assurance", "keeps collision tool on.", "Prevents double.", "Off."],
  ["Inventory sample", "Governance", "samples obligation inventory.", "Gap found.", "Assume."],
  ["Hours auto recon", "Assurance", "auto heat-hours recon.", "Flags under.", "Manual."],
  ["Legend test pre-board", "Reporting", "pre-board legend tests.", "Reclass.", "Skip."],
  ["KRI expand fail", "Assurance", "expands KRI samples on fail.", "Second found.", "Stop."],
  ["Divergence KPI", "Governance", "KPI ToR divergence closure.", "100%.", "Open."],
  ["Detect analytics inventory", "Assurance", "analytics detect inventory gaps.", "Shadows found.", "Attest."],
  ["Reperform vary", "Assurance", "varies reperformance by rating.", "High more.", "Flat."],
  ["Theme fund bridge", "Engagements", "bridges themes to funding.", "Funded.", "Dead."],
  ["Rewrite log", "Assurance", "logs rewrite triggers.", "Paper follows.", "None."],
  ["Principle pack", "Assurance", "packs principle tests.", "Plugs found.", "None."],
  ["Gate evidence", "Engagements", "evidence at outcome gates.", "Hold.", "Check."],
  ["Capacity test annual", "Assurance", "annual monetisation capacity test.", "Cut.", "None."],
  ["Encode pre-board", "Assurance", "encode test pre-board.", "Fix.", "Skip."],
  ["Harm field force", "Assurance", "force harm metric field.", "Forced.", "Opt."],
  ["Survey track", "Reporting", "track survey actions.", "Close.", "Open."],
  ["Outcome dash", "Governance", "challenge outcome dash.", "Used.", "Off."],
  ["Train refresh", "Risk management", "taxonomy train refresh.", "Misclass down.", "Once."],
  ["Colour annual", "Assurance", "colour calibrate annual.", "Done.", "Drift."],
  ["Access confirm", "Governance", "confirm private access.", "OK.", "Skip."],
  ["Sample expand", "Engagements", "expand practice sample.", "Thematic.", "Tiny."],
  ["Results KPI", "Assurance", "use-of-results KPI.", "Red.", "None."],
  ["Match annual", "Risk management", "insurance match annual.", "Gap.", "Miss."],
  ["Map required", "Risk management", "migration map required.", "Trend OK.", "None."],
  ["Bot rules", "Engagements", "escalate bot rules.", "Tuned.", "None."],
  ["Attest evidence", "Governance", "capacity attest evidence.", "Gap.", "Bare."],
  ["Admin quarterly", "Control", "admin review quarterly.", "Clean.", "Never."],
  ["Action force", "Risk management", "force contagion actions.", "Owners.", "None."],
  ["Product trigger", "Assurance", "product refresh trigger.", "Fire.", "Miss."],
  ["Universe vendor", "Assurance", "vendor in universe.", "Planned.", "Out."],
  ["Gap close edu", "Governance", "education gap close.", "Closed.", "Open."],
  ["Recon annual risk", "Reporting", "external recon annual.", "Fix.", "Skip."],
  ["Ops assure", "Assurance", "ops model assure.", "Cover.", "None."],
  ["Field annual", "Governance", "field test annual.", "Rewrite.", "Never."],
  ["Recon control", "Reporting", "same-day recon control.", "Catch.", "None."],
  ["Force weekly", "Risk management", "horizon force weekly.", "Clear.", "Weak."],
  ["Bias quarterly", "Assurance", "bias analytics quarterly.", "Find.", "Never."],
  ["Checklist on", "Engagements", "memo checklist on.", "Rationale.", "Off."],
  ["DoD sample", "Governance", "DoD sample.", "Coach.", "None."],
  ["Retire evidence", "Engagements", "retire evidence.", "Force.", "Date."],
  ["Certificate", "Assurance", "capacity certificate.", "Restate.", "None."],
  ["Freeze on", "Assurance", "metric freeze on.", "Block.", "Off."],
  ["Facilitator", "Governance", "external facilitator.", "Cut pack.", "Never."],
  ["Geo owners", "Risk management", "geo owners mandatory.", "Assign.", "Opt."],
  ["Protocol use", "Assurance", "ethics protocol use.", "Once.", "Shelf."],
  ["Daily recon", "Control", "daily recon.", "Catch.", "Week."],
  ["Path EWI", "Risk management", "EWI path.", "Fund.", "Stuck."],
  ["Secondary", "Assurance", "override secondary.", "Catch.", "Solo."],
  ["Metric live", "Risk management", "concentration live.", "Amber.", "Off."],
  ["Post-train test", "Governance", "post-train test.", "Redesign.", "Complete."],
  ["SLA Sev1", "Risk management", "Sev-1 SLA.", "Met.", "Miss."],
  ["Tone pre", "Reporting", "tone pre-issue.", "Balance.", "Skip."],
  ["Encode test", "Assurance", "encode test.", "Fix.", "Skip."],
  ["OKR annual", "Governance", "OKR align annual.", "Rewrite.", "Activity."],
  ["GRC freeze", "Control", "GRC freeze.", "Hold.", "Break."],
  ["Stress recon", "Risk management", "stress BAU recon.", "OK.", "Skip."],
  ["Dict on", "Reporting", "dictionary on.", "Down.", "Off."],
  ["DQ board", "Assurance", "DQ KRI board.", "Act.", "Hide."],
  ["SLA track", "Governance", "memo SLA track.", "OK.", "None."],
  ["Link test", "Assurance", "capital link test.", "Find.", "Skip."],
  ["Attest MI", "Risk management", "MI attest.", "Catch.", "None."],
  ["Exception log", "Engagements", "blackout exception log.", "Log.", "Silent."],
  ["Register on", "Risk management", "exception register on.", "Handle.", "None."],
  ["Viz test", "Reporting", "viz test.", "Redesign.", "Assume."],
  ["Accept formal", "Assurance", "gap accept formal.", "Revisit.", "Informal."],
  ["Calibrate", "Risk management", "severity calibrate.", "Done.", "Drift."],
  ["SLA gate", "Governance", "opinion SLA gate.", "Hold.", "Bypass."],
  ["Recon assure", "Control", "position recon.", "Strong.", "Weak."],
  ["List horizon", "Risk management", "source list.", "Curate.", "Random."],
  ["Outcome test", "Governance", "incentive outcome.", "Improve.", "None."],
  ["Matrix skills", "Engagements", "skills matrix.", "Fill.", "None."],
]);
