import { expand } from "./wave3-shared.mjs";

/** Wave-3 IIA drafts — unique vs waves 1–2. */
export const IIA_WAVE3 = expand([
  ["Charter safeguard operating test", "Profession", "tests that charter independence safeguards operate in practice annually.", "AC pay approval evidenced; OK.", "Safeguards paper."],
  ["Admin conflict mitigation log", "Profession", "logs administrative reporting conflicts with mitigations.", "Budget pressure logged; AC informed.", "Unlogged conflicts."],
  ["Conformance gap AC visibility", "Standards", "gives AC visibility of conformance gaps and closure.", "Gaps 4/5 closed; one to EQA.", "Gaps hidden."],
  ["EQA action closure dashboard", "Standards", "dashboards EQA action closure to AC.", "100% closed in 12 months.", "Shelfware EQA."],
  ["QAIP feedback to methodology", "Standards", "feeds stakeholder QAIP feedback into methodology changes.", "Clarity feedback changes template.", "Feedback unused."],
  ["Universe risk-weighted coverage", "Engagements", "reports risk-weighted universe coverage to AC.", "70% weighted; explained.", "Vanity coverage."],
  ["Planning memo AC material", "Engagements", "summarises material engagement plans to AC for challenge.", "CRE plan challenged; scope tightened.", "Reports only."],
  ["Work programme risk matrix", "Engagements", "matrices work programme steps to risks for review.", "Orphan steps cut.", "Untethered steps."],
  ["Evidence hierarchy enforce", "Engagements", "enforces evidence reliability hierarchy in file review.", "Confirmations added.", "Inquiry-heavy."],
  ["Root cause standard high findings", "Engagements", "requires root-cause standard on all high findings.", "Design cause found.", "Staff error stop."],
  ["Action SMART verify standard", "Reporting", "standards SMART actions and verification evidence.", "Vague actions rewritten.", "Email close."],
  ["Follow-up quality sample", "Reporting", "samples follow-up verification quality periodically.", "25% fail; train.", "Unknown quality."],
  ["Opinion calibration library", "Reporting", "libraries calibration cases for ratings.", "Library used quarterly.", "Inconsistent."],
  ["AC assurance glossary", "Reporting", "glossaries assurance language for AC.", "Confusion down.", "Jargon."],
  ["Consulting threat assess", "Engagements", "assesses independence threats before consulting accept.", "Declines impairing ask.", "Yes to all."],
  ["External reliance notes", "Profession", "notes external audit reliance discussions each cycle.", "ITGC path agreed.", "No notes."],
  ["Fraud escalate card", "Fraud", "cards red flags requiring immediate specialist escalate.", "Privilege day 1.", "Slow escalate."],
  ["ITGC factor scope", "IT audit", "factors materiality/connectivity/change into ITGC scope.", "CRM out with rationale.", "Everything in."],
  ["App control change tickets", "IT audit", "requires change tickets as app control OE evidence.", "Missing ticket finding.", "Screenshot only."],
  ["Cyber multi-year matrix", "IT audit", "plans cyber assurance multi-year by domain.", "Detection added.", "Password repeat."],
  ["Analytics population recon", "Engagements", "requires population recon before analytics conclusions.", "QAIP checks mandatory.", "Unknown pop."],
  ["Sample rationale template", "Engagements", "templates sample size rationales.", "Template on high-risk tests.", "Habit sizes."],
  ["Remote authenticity checks", "Engagements", "checks authenticity of remote evidence.", "Live video required.", "Staged photos."],
  ["Agile backlog risk groom", "Engagements", "grooms assurance backlogs by risk continuously.", "High first.", "Fake agile."],
  ["Soft control outcome pair", "Governance", "pairs soft control ratings with outcomes.", "Speak-up outcomes paired.", "Survey only."],
  ["ESG control catalogue", "Engagements", "catalogues controls for ESG disclosure readiness.", "Gaps remediate pre-external.", "Vague ready."],
  ["Vendor audit right plan", "Engagements", "plans annual use of vendor audit rights by criticality.", "Two rights used.", "Unused rights."],
  ["Guest objectivity declare", "Profession", "requires guest expert objectivity declarations.", "Filed; clear.", "No declare."],
  ["Co-source transfer KPI", "Profession", "KPIs knowledge transfer from co-source.", "KPI met; reduce next year.", "Forever co-source."],
  ["Rating guide workshop", "Reporting", "workshops rating guides with management.", "Debates down.", "Surprise ratings."],
  ["Acceptance memo template", "Reporting", "templates CAE memos on above-appetite acceptance.", "Used; appetite change once.", "Ad-hoc email."],
  ["Private session agenda", "Governance", "standing agendas for CAE-AC private sessions.", "Pressure/resources items.", "Empty private."],
  ["Partial conformance plan", "Standards", "plans closure of periodic assessment partials.", "Closed pre-EQA.", "Linger."],
  ["Mid-engagement supervise", "Engagements", "requires mid-engagement supervision on long jobs.", "Scope change saves rework.", "End only."],
  ["Workpaper PII minimise", "Engagements", "minimises PII in workpapers by design.", "Checklist; GDPR clean.", "Excess PII."],
  ["Risk-weighted hours page", "Engagements", "discloses risk-weighted hours to AC.", "Page in plan pack.", "Opaque hours."],
  ["Cooling-off register", "Engagements", "registers cooling-off after consulting before assurance.", "Blocks early assure.", "Forgot cool."],
  ["Mandatory guidance quiz", "Standards", "quizzes mandatory vs recommended guidance.", "Scores coach.", "Confusion."],
  ["Public VfM guide", "Profession", "guides VfM engagements in public sector IA.", "Used on procurement.", "No VfM."],
  ["Regulatory theme plan", "Engagements", "rolls regulatory themes into three-year plan visibly.", "Consumer duty scheduled.", "Missing themes."],
  ["Model gov approach memo", "IT audit", "memos IA approach to model governance vs revalidation.", "AC approves; inventory tested.", "Reperform all."],
  ["Treasury specialist brief", "Engagements", "briefs specialists with IA owning the opinion.", "IA owns opinion.", "Specialist-led."],
  ["Project gate checklist", "Engagements", "checklists assurance at project gates.", "Weak case stopped gate 1.", "Post-overrun only."],
  ["Leakage analytics playbook", "Engagements", "playbooks revenue leakage analytics steps.", "£0.9m recovered.", "Ad-hoc."],
  ["Ghost payroll routine", "Engagements", "routines ghost-employee analytics in payroll audits.", "One ghost; access fixed.", "Payslip only."],
  ["RP completeness beyond list", "Fraud", "procedures beyond management RP lists.", "Undisclosed vendor found.", "List only."],
  ["Disclosure IA briefing", "Reporting", "briefs disclosure committee on IA control themes.", "APM wording influenced.", "Siloed IA."],
  ["Management letter joint", "Reporting", "joint-tracks management letter and IA issues.", "Three themes merged.", "Parallel."],
  ["Tone multi-method pack", "Governance", "packs multi-method tone evidence.", "Balanced pack.", "Video only."],
  ["Three lines interview", "Governance", "interviews testing three-lines role clarity.", "Second-line doing first-line.", "Org chart."],
  ["KRI timing engagement", "Engagements", "times engagements using leading KRIs.", "Complaints bring conduct forward.", "Calendar only."],
  ["CSA facilitate script", "Engagements", "scripts facilitation so management owns CSA scores.", "Scores with management.", "IA scores."],
  ["Walkthrough OE train", "Engagements", "trains walkthrough versus OE boundary.", "Over-rely down.", "Walkthrough=OE."],
  ["Dual-purpose note", "Engagements", "templates dual-purpose design notes.", "Justifies both objectives.", "Undesigned dual."],
  ["Exception examples", "Engagements", "worked examples for exception evaluation.", "Inflation down.", "All high."],
  ["Draft distribution register", "Reporting", "registers draft recipients need-to-know.", "Leaks down.", "Wide email."],
  ["Privilege pocket card", "Fraud", "pocket cards privilege steps on fraud paths.", "Counsel day 1.", "Miss privilege."],
  ["Change pipeline checklist", "Engagements", "checklists assurance in change pipelines.", "Two holds.", "None."],
  ["Benefits audit guide", "Engagements", "guides benefits realisation audits.", "Untracked savings found.", "No benefits audit."],
  ["Lessons methodology bridge", "Profession", "bridges lessons into methodology with owners.", "Population recon mandatory.", "Unread lessons."],
  ["Conformance performance split", "Standards", "splits AC packs conformance vs performance.", "Debate clearer.", "Mixed."],
  ["Soft interview guide", "Governance", "updates soft-control interview guides anti-leading.", "Richer evidence.", "Leading Qs."],
  ["Continuous script change", "IT audit", "change-controls continuous audit scripts.", "Peer review catches error.", "Unchecked edits."],
  ["H&S scope factors", "Engagements", "factors harm into H&S assurance scope.", "High-harm in.", "H&S ignored."],
  ["Procurement red-flag list", "Engagements", "lists procurement integrity red flags.", "£2.4m variations found.", "Policy ack only."],
  ["Issue ageing AC dash", "Reporting", "dashboards issue ageing for AC.", "Clears >180d.", "Invisible."],
  ["Skill match pre-field", "Engagements", "checks skill match before fieldwork.", "Adds IT auditor.", "Wrong skills."],
  ["Finding customer tag", "Reporting", "tags findings with customer impact.", "Priority shifts.", "Equal all."],
  ["Assurance map cell own", "Profession", "owns IA map cells with update cadence.", "Quarterly update.", "Stale cells."],
  ["Remote inventory standard", "Engagements", "standards remote inventory observation quality.", "Live location video.", "Staged photo."],
  ["Factual accuracy SLA", "Reporting", "SLAs factual accuracy meetings pre-issue.", "Disputes down.", "Post-issue fight."],
  ["CAE succession plan", "Profession", "plans CAE succession with independence preserved.", "AC owns appoint.", "No plan."],
  ["Safeguard annual test", "Profession", "annual tests charter safeguards operate.", "Evidence OK.", "Paper."],
  ["Conflict log review", "Profession", "reviews admin conflict log quarterly.", "Mitigations OK.", "Stale log."],
  ["Gap visibility pack", "Standards", "packs conformance gaps for AC.", "Visible.", "Hidden."],
  ["EQA dash standing", "Standards", "standing EQA action dash at AC.", "Closed.", "Shelf."],
  ["Feedback change log", "Standards", "logs methodology changes from QAIP feedback.", "Logged.", "Unused."],
  ["Coverage page AC", "Engagements", "AC page for risk-weighted coverage.", "Explained.", "Vanity."],
  ["Plan summary material", "Engagements", "material plan summaries to AC.", "Challenge.", "None."],
  ["Matrix review gate", "Engagements", "gates file review on risk matrix complete.", "Orphans cut.", "Skip."],
  ["Hierarchy file review", "Engagements", "file review checks evidence hierarchy.", "Confirm add.", "Inquiry."],
  ["Root cause gate high", "Engagements", "gates high findings on root cause.", "Design found.", "Symptom."],
  ["SMART gate actions", "Reporting", "gates actions on SMART criteria.", "Rewrite.", "Vague."],
  ["Follow-up sample expand", "Reporting", "expands follow-up samples on fail.", "Train.", "Tiny."],
  ["Calibration quarterly", "Reporting", "quarterly opinion calibration.", "Library use.", "Drift."],
  ["Glossary AC pack", "Reporting", "glossary in AC pack.", "Less jargon.", "None."],
  ["Threat assess form", "Engagements", "form for consulting threat assess.", "Decline.", "No form."],
  ["Reliance note file", "Profession", "files reliance notes.", "Path agreed.", "None."],
  ["Escalate card use", "Fraud", "tracks escalate card use.", "Day 1.", "Slow."],
  ["Factor scope doc", "IT audit", "documents ITGC factor scope.", "CRM out.", "All in."],
  ["Ticket OE require", "IT audit", "requires tickets for OE.", "Finding.", "Shot."],
  ["Cyber matrix live", "IT audit", "lives cyber multi-year matrix.", "Domain cover.", "Repeat."],
  ["Pop recon QAIP", "Engagements", "QAIP checks pop recon.", "Mandatory.", "Skip."],
  ["Rationale template on", "Engagements", "rationale template on.", "Used.", "Habit."],
  ["Authenticity check", "Engagements", "authenticity checks remote.", "Live video.", "Staged."],
  ["Backlog groom risk", "Engagements", "risk groom backlog.", "High first.", "Fake."],
  ["Outcome pair soft", "Governance", "outcome pair soft controls.", "Paired.", "Survey."],
  ["ESG catalogue use", "Engagements", "ESG catalogue use.", "Remediate.", "Vague."],
  ["Rights plan annual", "Engagements", "audit rights plan annual.", "Two used.", "None."],
  ["Declare guest", "Profession", "guest declare.", "Filed.", "None."],
  ["Transfer KPI", "Profession", "transfer KPI.", "Met.", "Forever."],
  ["Guide workshop", "Reporting", "rating guide workshop.", "Debates down.", "Surprise."],
  ["Memo template", "Reporting", "acceptance memo template.", "Used.", "Email."],
  ["Agenda private", "Governance", "private agenda standing.", "Items.", "Empty."],
  ["Partial plan", "Standards", "partial plan close.", "Pre-EQA.", "Linger."],
  ["Supervise mid", "Engagements", "mid supervise.", "Rework save.", "End."],
  ["PII minimise", "Engagements", "PII minimise.", "Clean.", "Excess."],
  ["Hours page", "Engagements", "hours page AC.", "Clear.", "Opaque."],
  ["Cool register", "Engagements", "cooling register.", "Block.", "Forgot."],
  ["Guidance quiz", "Standards", "guidance quiz.", "Coach.", "Confuse."],
  ["VfM guide", "Profession", "VfM guide.", "Used.", "None."],
  ["Theme plan", "Engagements", "theme plan.", "Schedule.", "Miss."],
  ["Approach memo", "IT audit", "model approach memo.", "Approve.", "Reperform."],
  ["Specialist brief", "Engagements", "specialist brief.", "IA owns.", "Led."],
  ["Gate checklist", "Engagements", "gate checklist.", "Stop weak.", "Late."],
  ["Leak playbook", "Engagements", "leak playbook.", "Recover.", "Adhoc."],
  ["Ghost routine", "Engagements", "ghost routine.", "Find.", "Payslip."],
  ["RP beyond", "Fraud", "RP beyond list.", "Find.", "List."],
  ["Brief disclosure", "Reporting", "disclosure brief.", "Wording.", "Silo."],
  ["Letter joint", "Reporting", "letter joint track.", "Merge.", "Parallel."],
  ["Tone pack", "Governance", "tone pack multi.", "Balance.", "Video."],
  ["Lines interview", "Governance", "lines interview.", "Find blur.", "Chart."],
  ["KRI time", "Engagements", "KRI timing.", "Forward.", "Cal."],
  ["CSA script", "Engagements", "CSA script.", "Mgmt owns.", "IA score."],
  ["OE train", "Engagements", "OE boundary train.", "Rely down.", "Walk=OE."],
  ["Dual note", "Engagements", "dual note.", "Justify.", "Undesign."],
  ["Except examples", "Engagements", "except examples.", "Inflation down.", "All high."],
  ["Draft register", "Reporting", "draft register.", "Leak down.", "Wide."],
  ["Privilege card", "Fraud", "privilege card.", "Day1.", "Miss."],
  ["Pipeline check", "Engagements", "pipeline check.", "Holds.", "None."],
  ["Benefits guide", "Engagements", "benefits guide.", "Find.", "None."],
  ["Lessons bridge", "Profession", "lessons bridge.", "Method.", "Unread."],
  ["Split pack", "Standards", "split pack.", "Clear.", "Mix."],
  ["Interview guide", "Governance", "interview guide.", "Rich.", "Lead."],
  ["Script change", "IT audit", "script change.", "Catch.", "Edit."],
  ["H&S factors", "Engagements", "H&S factors.", "In scope.", "Ignore."],
  ["Red flag list", "Engagements", "red flag list.", "Find £.", "Ack."],
  ["Ageing dash", "Reporting", "ageing dash.", "Clear old.", "Hide."],
  ["Skill check", "Engagements", "skill check.", "Add IT.", "Wrong."],
  ["Customer tag", "Reporting", "customer tag.", "Priority.", "Equal."],
  ["Map cell", "Profession", "map cell own.", "Update.", "Stale."],
  ["Remote std", "Engagements", "remote std.", "Live video.", "Photo."],
  ["Facts SLA", "Reporting", "facts SLA.", "Less fight.", "Late."],
  ["Succession", "Profession", "succession plan.", "AC appoint.", "None."],
  ["Safeguard test", "Profession", "safeguard test.", "OK.", "Paper."],
  ["Conflict review", "Profession", "conflict review.", "OK.", "Stale."],
  ["Gap pack", "Standards", "gap pack.", "Visible.", "Hide."],
  ["EQA standing", "Standards", "EQA standing.", "Closed.", "Shelf."],
  ["Feedback log", "Standards", "feedback log.", "Change.", "Unused."],
  ["Coverage AC", "Engagements", "coverage AC.", "Explain.", "Vanity."],
  ["Plan AC", "Engagements", "plan AC.", "Challenge.", "None."],
  ["Matrix gate", "Engagements", "matrix gate.", "Cut.", "Skip."],
  ["Hierarchy check", "Engagements", "hierarchy check.", "Confirm.", "Inquiry."],
  ["Root gate", "Engagements", "root gate.", "Design.", "Symptom."],
  ["SMART gate", "Reporting", "SMART gate.", "Rewrite.", "Vague."],
  ["Follow expand", "Reporting", "follow expand.", "Train.", "Tiny."],
  ["Calibrate Q", "Reporting", "calibrate Q.", "Use lib.", "Drift."],
  ["Glossary pack", "Reporting", "glossary pack.", "Less jargon.", "None."],
  ["Threat form", "Engagements", "threat form.", "Decline.", "None."],
  ["Reliance file", "Profession", "reliance file.", "Agree.", "None."],
  ["Card track", "Fraud", "card track.", "Day1.", "Slow."],
  ["Scope doc", "IT audit", "scope doc.", "Out CRM.", "All."],
  ["Ticket require", "IT audit", "ticket require.", "Find.", "Shot."],
  ["Matrix cyber", "IT audit", "matrix cyber.", "Cover.", "Repeat."],
  ["Recon QAIP", "Engagements", "recon QAIP.", "Must.", "Skip."],
  ["Template on", "Engagements", "template on.", "Use.", "Habit."],
  ["Auth check", "Engagements", "auth check.", "Live.", "Stage."],
  ["Groom risk", "Engagements", "groom risk.", "High.", "Fake."],
  ["Pair soft", "Governance", "pair soft.", "Pair.", "Survey."],
  ["Catalogue ESG", "Engagements", "catalogue ESG.", "Remediate.", "Vague."],
  ["Rights annual", "Engagements", "rights annual.", "Use 2.", "None."],
  ["Guest declare", "Profession", "guest declare.", "File.", "None."],
  ["KPI transfer", "Profession", "KPI transfer.", "Met.", "Forever."],
  ["Workshop rate", "Reporting", "workshop rate.", "Down debate.", "Surprise."],
  ["Template accept", "Reporting", "template accept.", "Use.", "Email."],
  ["Agenda stand", "Governance", "agenda stand.", "Items.", "Empty."],
  ["Plan partial", "Standards", "plan partial.", "Close.", "Linger."],
  ["Mid supervise", "Engagements", "mid supervise.", "Save.", "End."],
  ["Minimise PII", "Engagements", "minimise PII.", "Clean.", "Excess."],
  ["Page hours", "Engagements", "page hours.", "Clear.", "Opaque."],
  ["Register cool", "Engagements", "register cool.", "Block.", "Forgot."],
  ["Quiz guide", "Standards", "quiz guide.", "Coach.", "Confuse."],
  ["Guide VfM", "Profession", "guide VfM.", "Use.", "None."],
  ["Plan theme", "Engagements", "plan theme.", "Sched.", "Miss."],
  ["Memo model", "IT audit", "memo model.", "OK.", "Reperf."],
  ["Brief treas", "Engagements", "brief treas.", "Own.", "Led."],
  ["Check gate", "Engagements", "check gate.", "Stop.", "Late."],
  ["Book leak", "Engagements", "book leak.", "£ recover.", "Adhoc."],
  ["Routine ghost", "Engagements", "routine ghost.", "Find.", "Slip."],
  ["Beyond RP", "Fraud", "beyond RP.", "Find.", "List."],
  ["Brief disc", "Reporting", "brief disc.", "Word.", "Silo."],
  ["Joint letter", "Reporting", "joint letter.", "Merge.", "Para."],
  ["Pack tone", "Governance", "pack tone.", "Bal.", "Vid."],
  ["Interview 3L", "Governance", "interview 3L.", "Blur.", "Chart."],
  ["Time KRI", "Engagements", "time KRI.", "Fwd.", "Cal."],
  ["Script CSA", "Engagements", "script CSA.", "Mgmt.", "IA."],
  ["Train OE", "Engagements", "train OE.", "Down rely.", "Walk."],
  ["Note dual", "Engagements", "note dual.", "Just.", "None."],
  ["Examples ex", "Engagements", "examples ex.", "Down.", "High."],
  ["Register draft", "Reporting", "register draft.", "Down leak.", "Wide."],
  ["Card priv", "Fraud", "card priv.", "D1.", "Miss."],
  ["Check pipe", "Engagements", "check pipe.", "Hold.", "None."],
  ["Guide ben", "Engagements", "guide ben.", "Find.", "None."],
  ["Bridge less", "Profession", "bridge less.", "Method.", "Unread."],
  ["Pack split", "Standards", "pack split.", "Clear.", "Mix."],
  ["Guide soft", "Governance", "guide soft.", "Rich.", "Lead."],
  ["Change script", "IT audit", "change script.", "Catch.", "Edit."],
  ["Factor H&S", "Engagements", "factor H&S.", "In.", "Out."],
  ["List red", "Engagements", "list red.", "£ find.", "Ack."],
  ["Dash age", "Reporting", "dash age.", "Clear.", "Hide."],
  ["Check skill", "Engagements", "check skill.", "Add.", "Wrong."],
  ["Tag cust", "Reporting", "tag cust.", "Prio.", "Eq."],
  ["Own cell", "Profession", "own cell.", "Upd.", "Stale."],
  ["Std remote", "Engagements", "std remote.", "Live.", "Photo."],
  ["SLA facts", "Reporting", "SLA facts.", "Less fight.", "Late."],
  ["Plan succ", "Profession", "plan succ.", "AC.", "None."],
]);
